### ISSUE TITLE
Build error: Windows: Severity	Code	Description	Project	File	Line	Suppression State Error	C2039	'get_min_object_size': is not a member of 'dlib::random_cropper'	

### ISSUE THREAD

**Issue by deepakkumar1984** [takuya-takeuchi/DlibDotNet#10]
Getting the following error while doing the build:

Severity	Code	Description	Project	File	Line	Suppression State
Error	C2039	'get_min_object_size': is not a member of 'dlib::random_cropper'	DlibDotNet.Native	c:\git\dlibdotnet\src\dlibdotnet.native\dlib\image_transforms\random_cropper.h	85	

Error	C2660	'dlib::random_cropper::set_min_object_size': function does not take 1 arguments	DlibDotNet.Native	c:\git\dlibdotnet\src\dlibdotnet.native\dlib\image_transforms\random_cropper.h	119	

Any idea how to solve this issue?

**Comment by takuya-takeuchi** [comment]
I'm verry sorry to trouble you. I found that get_min_object_size was added after 19.4. Please use 19.7.

**Comment by deepakkumar1984** [comment]
No problem. Will do

Thanks
