### ISSUE TITLE
Add new method to Dlib which used to Load Data From SoftwareBitmap

### ISSUE THREAD

**Issue by zhuxb711** [takuya-takeuchi/DlibDotNet#100]
Please add this method to Dlib
It would be easier to transform SoftwareBitmap

```
public Array2D<RgbPixel> LoadFromSoftwareBitmap(SoftwareBitmap Bitmap)
        {
            uint BufferSize = (uint)(Bitmap.PixelHeight * Bitmap.PixelWidth * 4);
            byte[] DlibImageArray = new byte[BufferSize];
            Windows.Storage.Streams.Buffer buffer = new Windows.Storage.Streams.Buffer(BufferSize);
            Bitmap.CopyToBuffer(buffer);
            using (var Reader = DataReader.FromBuffer(buffer))
            {
                Reader.ReadBytes(DlibImageArray);
            }
            return Dlib.LoadImageData<RgbPixel>(ImagePixelFormat.Bgra, DlibImageArray, (uint)Bitmap.PixelHeight, (uint)Bitmap.PixelWidth, (uint)Bitmap.PixelWidth * 4);
        }
```

**Comment by valerysntx** [comment]
@zhuxb711 - fork DlibDotNet, be free to add anything, - such way maybe it could be helpful for someone.. if not fit's here

Regarding your gist - does `Windows.Storage.Streams.Buffer` work on osx?

**Comment by takuya-takeuchi** [comment]
Everyone, sorry late reply.

I created DlibDotNet.Extension.UWP (UWP library) to use softwarebitmap. It is for only Windows.
But it does not work.
UWP library is difficult to use p/invoke. so library failed to call p/invoke.
I could have any wrong. But I do not know what is wrong.

@valerysntx Thank you for kindly support as always.
`Windows.Storage.Streams.Buffer` could be for only Windows.
In the first place, DlibDotNet.Extension is not targeting cross platform.
Yes, .net core 3.0 will support System.Drawing and WPF classes and it will help supporting to get cross platform.
So in the future, Extension may be for cross platform.

**Comment by takuya-takeuchi** [comment]
No Response
