### ISSUE TITLE
`DlibDotNet.Extensions` migration to netstandard2.0 review

### ISSUE THREAD

**Issue by valerysntx** [takuya-takeuchi/DlibDotNet#101]
Here is `DlibDotNet.Extensions` [migration ](https://github.com/takuya-takeuchi/DlibDotNet/compare/master...valerysntx:standardextensions) to `netstandard2.0` + tests 

 - https://github.com/valerysntx/DlibDotNet/commit/0ddf43bd7fff622d6db0823d9b349f4f0dc5b80f
 - https://github.com/valerysntx/DlibDotNet/commit/f73c21f47b8b8251ce11d0ec6620d8331bde3c4d
 - https://github.com/valerysntx/DlibDotNet/commit/995c2d6025fa0bf898a3db5ce5dda3e6277885a8

@takuya-takeuchi: ping me, if considering such of migration, i will PR :)

_Originally posted by @valerysntx in https://github.com/takuya-takeuchi/DlibDotNet/issues/18#issuecomment-451672469_

https://github.com/takuya-takeuchi/DlibDotNet/issues/97

**Comment by takuya-takeuchi** [comment]
@valerysntx It looks to be good. I added the comment to the above 3 commits.

**Comment by valerysntx** [comment]
@takuya-takeuchi thanks for reviewing!

So, this could be updated in a fully backward compatible and cross-platform way.

* https://github.com/CoreCompat/CoreCompat.

Making iterating over migration, we need cross-platform interop with System.Drawing. 
I will make PR updates, for fully backward compatible way to migrate using https://www.nuget.org/packages/CoreCompat.System.Drawing/1.0.0-beta006

**Comment by takuya-takeuchi** [comment]
close due to 2df5ba5e85a8543b098319f930839c1b9676b920
