### ISSUE TITLE
Extracting landmark points

### ISSUE THREAD

**Issue by Lucashglund** [takuya-takeuchi/DlibDotNet#103]
Is there a good way to extract the information about the dot-location when using Dlib.GetFrontalFaceDetector().Operator("Image") combined with "ShapePredictor.Detect("Image", faces)" that make use of the 68 point landmark file "shape_predictor_68_face_landmarks.dat"

**Comment by takuya-takeuchi** [comment]
you can use https://github.com/takuya-takeuchi/FaceRecognitionDotNet/blob/master/src/FaceRecognitionDotNet/FaceRecognition.cs
