### ISSUE TITLE
Cuda 10

### ISSUE THREAD

**Issue by turowicz** [takuya-takeuchi/DlibDotNet#104]
I see that the nuget package requires CUDA 9.2 to be present on the Linux machine. Unfortunately I'm using Ubuntu 18.04 and there is no CUDA 9.x available for it.

Is there a plan to upgrade to CUDA 10? For now I'm forced keep on compiling Dlib myself and not use the nuget package.

cc @valerysntx @takuya-takeuchi

**Comment by takuya-takeuchi** [comment]
@turowicz I got it.
But other developer may need cuda 9.2.
So Maybe we should publish dlibdotnet-withcuda-10.

**Comment by takuya-takeuchi** [comment]
I'm building following new packages

* DlibDotNet.CUDA92
* DlibDotNet.CUDA100

Old package **DlibDotNet-WithCUDA** will become obsolete. TBH, it was not good name :(
So FaceRecognitionDotNet-WithCUDA will be FaceRecognitionDotNet.CUDA100 or FaceRecognitionDotNet.CUDA92

**Comment by takuya-takeuchi** [comment]
Published

* https://www.nuget.org/packages/DlibDotNet
* https://www.nuget.org/packages/DlibDotNet.CUDA92
* https://www.nuget.org/packages/DlibDotNet.CUDA100

**Comment by turowicz** [comment]
That is amazing thank you so much!

**Comment by turowicz** [comment]
@takuya-takeuchi do we need to do the same for FaceRecognitionDotNet or is it OK to use the -WithCUDA variant?

**Comment by turowicz** [comment]
I see the -WithCUDA variant of FacialRecognitionDotNet is still in `.10`

**Comment by takuya-takeuchi** [comment]
Sorry. I have already pushed the latest package but I did not publish to release branch.
Pleased check README.md
