### ISSUE TITLE
Can't compile DlibDotNet.Native

### ISSUE THREAD

**Issue by VinickGold** [takuya-takeuchi/DlibDotNet#107]
# Summary of your issue

Can't compile DlibDotNet.Native with Cmake (V 3.14). After execute the commands as described in the [Wiki - Tutorial for Windows](https://github.com/takuya-takeuchi/DlibDotNet/wiki/Tutorial-for-Windows) 

mkdir build
cd build
cmake -G "Visual Studio 15 2017 Win64" -T host=x64 ^
           -DDLIB_PATH=C:\dlib-19.17 ^
           ..

i get the following error in my command prompt:

-------------------------------------------------------
-- CMAKE_SYSTEM_INFO_FILE: Platform/Windows
-- CMAKE_SYSTEM_NAME:      Windows
-- CMAKE_SYSTEM_PROCESSOR: AMD64
-- CMAKE_SYSTEM:           Windows-10.0.17134
-- os_version_suffix:
-- Project: C:/DlibDotNet-master/src/DlibDotNet.Native
-- Binaries: C:/DlibDotNet-master/src/DlibDotNet.Native/build
-------------------------------------------------------
-- CMAKE_BUILD_TYPE: Release
**_CMake Error at CMakeLists.txt:54 (add_subdirectory):
  add_subdirectory given source
  "C:/DlibDotNet-master/src/DlibDotNet.Native/../../src/dlib/dlib" which is
  not an existing directory._**

-- Configuring incomplete, errors occurred!

I have no ideia what i can be doing wrong, the instructions seens to be pretty straigth foward on the wiki. Do you know if is there someone else having this problem? Thanks in advance.

**Comment by takuya-takeuchi** [comment]
dlib is in the src dir as submodule.
you must do git submodule update to get dlib source.

**Comment by Lam-dev** [comment]
i have the same error. Can you give more detailed instructions? Thank you

**Comment by takuya-takeuchi** [comment]
````
git clone https://github.com/takuya-takeuchi/DlibDotNet
cd DlibDotNet
git submodule update --init --recursive
````

**Comment by VinickGold** [comment]
Thanks @takuya-takeuchi, it solved the issue.

**Comment by Lam-dev** [comment]
i solved the issue. thank you so much

**Comment by VinickGold** [comment]
Hi @takuya-takeuchi, since i'm not able to create a pull request for the project wiki, i would like to suggest a little enhancement in the wiki documentation adding the steps below to preparation section in order to make the build process easy:

1 - Clone Dlib.Net repository to any directory 
   - `git clone https://github.com/takuya-takeuchi/DlibDotNet`

2 - Update the repository submodules
   - `cd DlibDotNet`
   - `git submodule update --init --recursive`

3 - Download dlib package from officail site
4 - Extract dlib file to any directory

PS: In case you think this change isn't necessary the issue can be closed, thanks in advance.

**Comment by takuya-takeuchi** [comment]
@VinickGold Thank you for good reopen!!! :)
Yes, wiki is too old. I must update wiki.

This issue should be treated as important.
I promise to update wiki in this weekend.

**Comment by takuya-takeuchi** [comment]
Updated all wiki pages

* Add Preparation section
  * Use Initialize script to call `git submodule update --init --recursive`
* Remove explanation to download and extract dlib package
* Update build command

**Comment by sonfiree** [comment]
!update wiki

**Comment by takuya-takeuchi** [comment]
@sonfiree 
what's wrong?

**Comment by sonfiree** [comment]
> Updated all wiki pages
> 
> * Add Preparation section
>   
>   * Use Initialize script to call `git submodule update --init --recursive`
> * Remove explanation to download and extract dlib package
> * Update build command

Not wiki (https://github.com/takuya-takeuchi/DlibDotNet/wiki/Tutorial-for-Linux)
`git submodule update --init --recursive`

**Comment by takuya-takeuchi** [comment]
@sonfiree 
Initialize.sh call this command.
