### ISSUE TITLE
Array2D<RgbPixel> to Bitmap

### ISSUE THREAD

**Issue by wpmanoj** [takuya-takeuchi/DlibDotNet#108]
# Summary of your issue

Array2D<RgbPixel> image draw on winform PictureBoxIpI. 

everything goes well but "Bitmap result = cimg.ToBitmap();" in here convert doesn't work. 

it gave me some error "Array2D<RgbPixel> does not Contain definition for 'ToBitmap' and best extension method overload BitmapConverter.ToBitmap(Mat)  requires a receiver of type 'Mat'". how should it change.

# Environment

C#, winForm

## Example code:

```
frame = new Mat();
capture = new VideoCapture(0);
capture.Open(0);

capture.Read(frame);
byte[] array = new byte[frame.Width * frame.Height * frame.ElemSize()];
Marshal.Copy(frame.Data, array, 0, array.Length);

Array2D<RgbPixel> cimg = Dlib.LoadImageData<RgbPixel>(array, (uint)frame.Height, (uint)frame.Width, (uint)(frame.Width * frame.ElemSize()));

DlibDotNet.Rectangle[] faces = detector.Operator(cimg);

List<FullObjectDetection> shapes = new List<FullObjectDetection>();

foreach (DlibDotNet.Rectangle r in faces)
{
   FullObjectDetection det = poseModel.Detect(cimg, r);
   shapes.Add(det);

   Dlib.DrawRectangle(cimg, r, new RgbPixel { Green = 255 });
}

Bitmap result = cimg.ToBitmap(); // The Place Error Occured.
pictureBox.Invoke(new Action(() =>
{
         pictureBox.Image?.Dispose();
         pictureBox.Image = result;
 }));
```

## Output:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1929	'Array2D<RgbPixel>' does not contain a definition for 'ToBitmap' and the best extension method overload 'BitmapConverter.ToBitmap(Mat)' requires a receiver of type 'Mat'

```

**Comment by takuya-takeuchi** [comment]
ToBitmap method is not included in nuget package.
it is in DlibDotNet.Extensions.

please build and refer it on yout project

**Comment by wpmanoj** [comment]
i'm just using system drawing. it's work fine too. some one who will face this problem can use this.

`
Bitmap result = frame.ToBitmap();
Graphics gImage = Graphics.FromImage(result);

rect = new System.Drawing.Rectangle(r.Left, r.Top, r.Right - r.Left, r.Bottom - r.Top);
gImage.DrawRectangle(GreenPen, rect);
`
