### ISSUE TITLE
Error while building DlibDotNet.Native

### ISSUE THREAD

**Issue by deepakkumar1984** [takuya-takeuchi/DlibDotNet#11]
Any idea anout these errors

Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2019	unresolved external symbol DGifOpenFileName referenced in function "void __cdecl dlib::load_image<class dlib::matrix<signed char,0,0,class dlib::memory_manager_stateless_kernel_1<char>,struct dlib::row_major_layout> >(class dlib::matrix<signed char,0,0,class dlib::memory_manager_stateless_kernel_1<char>,struct dlib::row_major_layout> &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (??$load_image@V?$matrix@C$0A@$0A@V?$memory_manager_stateless_kernel_1@D@dlib@@Urow_major_layout@2@@dlib@@@dlib@@YAXAEAV?$matrix@C$0A@$0A@V?$memory_manager_stateless_kernel_1@D@dlib@@Urow_major_layout@2@@0@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)	DlibDotNet.Native	C:\git\DlibDotNet\src\DlibDotNet.Native\build\load_image_dataset.obj	1	
Error	LNK2001	unresolved external symbol DGifOpenFileName	DlibDotNet.Native	

C:\git\DlibDotNet\src\DlibDotNet.Native\build\load_image.obj	1	
Error	LNK2019	unresolved external symbol DGifSlurp referenced in function "void __cdecl dlib::load_image<class dlib::matrix<signed char,0,0,class dlib::memory_manager_stateless_kernel_1<char>,struct dlib::row_major_layout> >(class dlib::matrix<signed char,0,0,class dlib::memory_manager_stateless_kernel_1<char>,struct dlib::row_major_layout> &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (??$load_image@V?$matrix@C$0A@$0A@V?$memory_manager_stateless_kernel_1@D@dlib@@Urow_major_layout@2@@dlib@@@dlib@@YAXAEAV?$matrix@C$0A@$0A@V?$memory_manager_stateless_kernel_1@D@dlib@@Urow_major_layout@2@@0@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)	DlibDotNet.Native	

C:\git\DlibDotNet\src\DlibDotNet.Native\build\load_image_dataset.obj	1	
Error	LNK2001	unresolved external symbol DGifSlurp	DlibDotNet.Native	C:\git\DlibDotNet\src\DlibDotNet.Native\build\load_image.obj	1	
Error	LNK2019	unresolved external symbol DGifCloseFile referenced in function "void __cdecl dlib::load_image<class dlib::matrix<signed char,0,0,class dlib::memory_manager_stateless_kernel_1<char>,struct dlib::row_major_layout> >(class dlib::matrix<signed char,0,0,class dlib::memory_manager_stateless_kernel_1<char>,struct dlib::row_major_layout> &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (??$load_image@V?$matrix@C$0A@$0A@V?$memory_manager_stateless_kernel_1@D@dlib@@Urow_major_layout@2@@dlib@@@dlib@@YAXAEAV?$matrix@C$0A@$0A@V?$memory_manager_stateless_kernel_1@D@dlib@@Urow_major_layout@2@@0@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)	DlibDotNet.Native

	C:\git\DlibDotNet\src\DlibDotNet.Native\build\load_image_dataset.obj	1	
Error	LNK2001	unresolved external symbol DGifCloseFile	DlibDotNet.Native	

C:\git\DlibDotNet\src\DlibDotNet.Native\build\load_image.obj	1	
Error	LNK1120	3 unresolved externals	DlibDotNet.Native	

C:\git\DlibDotNet\src\DlibDotNet.Native\build\Debug\DlibDotNet.Native.dll	1

**Comment by takuya-takeuchi** [comment]
I guess CMake compiler fails to recognize **DLIB_GIF_SUPPORT** define.
Because **DGifCloseFile** is defined in giflib rather than Dlib and DLibDotNet.

But DLIB_GIF_SUPPORT is already defined in https://github.com/takuya-takeuchi/DlibDotNet/blob/master/src/DlibDotNet.Native/CMakeLists.txt

So I doubt that CMake garbage cache remains.
Could you delete build directory and re-try build process?

**Comment by takuya-takeuchi** [comment]
Or you can add **DLIB_JPEG_SUPPORT**, **DLIB_PNG_SUPPORT** and **DLIB_GIF_SUPPORT** manually if CMake does not work well.
After do CMake, open **DlibDotNet.Native.vcxproj** and add the above defines to **PreprocessorDefinitions** sections.

Of Course, this approach is workaround rather than proper.

**Comment by deepakkumar1984** [comment]
Thanks for the help with the build which I am able to do it successfully. I am using the .net dll in my project but getting the following erorr: Unable to load DLL 'DlibDotNet.Native.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)

I have DlibDotNet.Native.dll, DlibDotNet.Native.lib, dlib.lib in the same folder DlibDotNet.dll resides.

Anything else I am missing

**Comment by deepakkumar1984** [comment]
All good now! I am able to load it now. thanks
