### ISSUE TITLE
Run error

### ISSUE THREAD

**Issue by Lam-dev** [takuya-takeuchi/DlibDotNet#110]
I encountered this error when running example DnnFaceRecognition
![error](https://user-images.githubusercontent.com/46856909/58385081-f59e3c00-8014-11e9-9e28-67ccb0cf0df8.jpg)
Please help me solve it

**Comment by takuya-takeuchi** [comment]
Did you deploy model file?
Please check the this section.
https://github.com/takuya-takeuchi/DlibDotNet/tree/master/examples/DnnFaceRecognition#2-download-demo-data

**Comment by takuya-takeuchi** [comment]
This issue may be same to #111.
