### ISSUE TITLE
ShapePredictor occur 'Can not pass IntPtr.Zero Arg_ParamName_Name'

### ISSUE THREAD

**Issue by hauserJr** [takuya-takeuchi/DlibDotNet#111]
# Summary of your issue
When I run ../examples/DnnFaceRecognition project have a error occur

# Environment
![image](https://user-images.githubusercontent.com/12874475/58471490-8e000200-8176-11e9-9a40-4d766233c95e.png)

# What did you do when you faced the problem?
I just assign test.jpg to args
## Example code:

```
 private static void Main(string[] args)
        {
            args = new string[] { @"test.jpg" };
            if (args.Length == 0)
            {
                ....
            }

            // The first thing we are going to do is load all our models.  First, since we need to
            // find faces in the image we will need a face detector:
            using (var detector = Dlib.GetFrontalFaceDetector())
            // We will also use a face landmarking model to align faces to a standard pose:  (see face_landmark_detection_ex.cpp for an introduction)
            using (var sp =  ShapePredictor.Deserialize(@"shape_predictor_68_face_landmarks.dat"))
            // And finally we load the DNN responsible for face recognition.
            using (var net = DlibDotNet.Dnn.LossMetric.Deserialize(@"dlib_face_recognition_resnet_model_v1.dat"))
...
```

## Output:
on Program.cs line 34 have a error occur
```
System.ArgumentException: 'Can not pass IntPtr.Zero
Arg_ParamName_Name'
```
![image](https://user-images.githubusercontent.com/12874475/58471802-504fa900-8177-11e9-91e5-f0e532c74271.png)

## What did you intend to be?
I just want to run this project using my pictures

**Comment by takuya-takeuchi** [comment]
Where did you execute example? If execute directory include nonalpha-numeric character, dlib (not dlibdotnet) may not be able to find model file.
If this case, you can change encoding indicates where model file is.

Please refer this issue.
https://github.com/takuya-takeuchi/FaceRecognitionDotNet/issues/21

**Comment by hauserJr** [comment]
I rename my dat file and move to new path on D://, same like this
> D:\\\68landmarks.dat

so project DnnFaceRecognition on Program.cs line 34 I change to
` using (var sp =  ShapePredictor.Deserialize("D:\\68landmarks.dat"))`

execute result it's can find flie
![image](https://user-images.githubusercontent.com/12874475/58523693-08bd3180-81f8-11e9-8d52-f89b624c8e6e.png)

whatever I change what encoding ,when execute to 
`
var ret = NativeMethods.deserialize_shape_predictor(str,
                                                                out var predictor,
                                                                out var errorMessage);
`
predictor value always output 0

**Comment by takuya-takeuchi** [comment]
This issue may be came from #160.
So this issue could be resolved.
