### ISSUE TITLE
Is there a way to convert Array2D<RgbPixel> to System.Drawing.Bitmap?

### ISSUE THREAD

**Issue by Omar-Belghaouti** [takuya-takeuchi/DlibDotNet#113]
# Summary
I'm making a WPF application and to display images on it. The images must be in Bitmap format, so is there a way to convert Array2D<RgbPixel> to Bitmap?

# Environment
.NET Framework 4.6.1

**Comment by takuya-takeuchi** [comment]
You can build and use DlibDotNet.Extensions.
Then you can call Array2D.ToBitmap.

**Comment by Omar-Belghaouti** [comment]
Okay, thanks

**Comment by Omar-Belghaouti** [comment]
Alright thanks

**Comment by Omar-Belghaouti** [comment]
Alright I've built DlibDotNet.Extensions but I cannot see any method ToBitmap?
I have an Array2D<RgbPixel> object named cimg and I want to convert like so cimg.ToBitmap()

**Comment by valerysntx** [comment]
> I cannot see any method ToBitmap?

 _**[ToBitmap](https://github.com/takuya-takeuchi/DlibDotNet/blame/63b9e420be27f3ab9a8320dbae79cf82b355afcf/src/DlibDotNet.Extensions/Extensions/BitmapExtensions.cs#L64)**_ 


```
...
namespace DlibDotNet.Extensions 
{

       public static Bitmap ToBitmap<T>(this Array2D<T> array)
                  where T : struct
                  {
...
```
https://stackoverflow.com/questions/403539/what-are-extension-methods

**Comment by Omar-Belghaouti** [comment]
valerysntx, I can't find this static method in DlibDotNet.Extensions namespace, considering that I downloaded DlibDotNet from NuGet package manager. All I see is this class DlibDotNet.Extensions.EnumerableExtensions that does not contain ToBitmap static method!

**Comment by Omar-Belghaouti** [comment]
I've hard built it, now it's working, I wish It came from NuGet directly.
