### ISSUE TITLE
Convert OpenCVSharp.Mat to FaceRecognitionDotNet.Image

### ISSUE THREAD

**Issue by Lam-dev** [takuya-takeuchi/DlibDotNet#114]
Hello I just have a question,
How to convert opencvsharp mat to faceRecognition.Image.

**Comment by takuya-takeuchi** [comment]
No way to provide function to convert OpenCVSharp.Mat to FaceRecognitionDotNet.Image.

You must convert Mat to byte array.
Reference: https://github.com/takuya-takeuchi/DlibDotNet/blob/master/examples/WebcamFacePose/Program.cs

After that, you can use FaceRecognitionDotNet.LoadImage method.
