### ISSUE TITLE
Can not build DlibDotNetNativeDnn

### ISSUE THREAD

**Issue by Lam-dev** [takuya-takeuchi/DlibDotNet#115]
I tried build dlibDotNetNativeDnn.dll file. however, i can't because RAM is only 4GB(error 1060: out of heap space). If you have dlibDotNetNativeDnn.dll file (visual studio 15 2017 x64 not CUDA). please give me. Thank you so much

**Comment by takuya-takeuchi** [comment]
you can use nuget package.
please check https://github.com/takuya-takeuchi/DlibDotNet
