### ISSUE TITLE
can I use parallel computing to Improve the recognition Speed?

### ISSUE THREAD

**Issue by longas1232** [takuya-takeuchi/DlibDotNet#116]
# Summary of your issue

# Environment

Write your environment.

# What did you do when you faced the problem?

//write here

## Example code:

```
paste your core code
```

## Output:

```
paste your output
```

**Comment by takuya-takeuchi** [comment]
use gpu or build dlibDotNet.native and Dnn with intelMkl

**Comment by longas1232** [comment]
thanks for your time,takuya 
I am writing a demo for Face recognition by your library,it is very good to use 
when I  initialize the face picture (almost 2000） and make them to the ".dat" file 
it cost me for a long time.so I plan to use parallel way like this 
//Parallel.ForEach(strs, path =>
                        //{
                        //    byte[] bys = File.ReadAllBytes(path);
                        //    DirectoryInfo info = new DirectoryInfo(Path.GetDirectoryName(path));
                        //    string name = info.Name;
                        //    FaceServer.FaceEntry(bys, name);
                        //    //m_logger.Debug("{0}，{1}", name, result);
                        //});
but i will get errors and i can't run it so whether can i use some way to improve this time to cost 
so i can't wait it for a long time
thanks a lot at all

**Comment by takuya-takeuchi** [comment]
I do not know what library you use.

But if you use FaceRecognitionDotNet, you can refer https://github.com/takuya-takeuchi/FaceRecognitionDotNet/issues/24.

**Comment by longas1232** [comment]
I got it,thank you
and I check my code this library is not the original by you
so can u give me a link about the example for face FaceRecognitionDotNet 
i feel grateful for the help

**Comment by longas1232** [comment]
I got it,thank you
and I check my code this library is not the original by you
so can u give me a link about the example for face FaceRecognitionDotNet 
i feel grateful for the help

**Comment by takuya-takeuchi** [comment]
> so can u give me a link about the example for face FaceRecognitionDotNet

FRDN does not support multthread for one gpu.
It may work on multiple gpu with multithread.
But there is not example.

Example are in https://github.com/takuya-takeuchi/FaceRecognitionDotNet/tree/master/examples

**Comment by longas1232** [comment]
I learn for it.
thank for your patience
