### ISSUE TITLE
BadImageFormatException trying to use nuget package

### ISSUE THREAD

**Issue by VinickGold** [takuya-takeuchi/DlibDotNet#117]
# Summary of your issue

I clonned the repo and compiled the solution on Windows following the wiki, after that i was able to run the facedetection and facelandemarkdetection examples (WinForms) in the repository solution ...

![image](https://user-images.githubusercontent.com/8043172/58677745-93567b80-8333-11e9-94cf-63fab641114f.png)

Now i want to use the facedetection in another solution, then i created a new solution with Console App project targeting .Net Framework 4.6.1, installed the [nuget package](https://www.nuget.org/packages/DlibDotNet/19.17.0.20190513).
**PS: You can find a solution copy in this [Repository](https://github.com/VinickGold/Dlibdotnet_console_sample)**

Following the examples i wrote the code below for sake of simplicity:

```
var path = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.Desktop), "photo.jpg");

using (var faceDetector = Dlib.GetFrontalFaceDetector())
using (var img = Dlib.LoadImage<RgbPixel>(path))
{
	Dlib.PyramidUp(img);

	var detectedFaces = faceDetector.Operator(img);

	Console.WriteLine($"Detected Faces: { detectedFaces.Count() }");

	Console.ReadKey();
}
```

When i try to call Dlibdotnet [Dlib.GetFrontalFaceDetector()]  i receive a: 

**System.BadImageFormatException | "An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)"**

My bin folder seems to have all the required dlls:

![Untitled](https://user-images.githubusercontent.com/8043172/58674028-5df66180-8324-11e9-9f3d-59dc1288eeb3.png)

# Environment

Windows 10, MS Visual Studio 2017 Community. 

# What did you do when you faced the problem?

1 - I tried copy the dlls from the repo bin folder where the examples are working fine and add as references on the new project instead of using the nuget package

2 - I tried install older version of the nuget package

But even though the result is the same.

Now i'm 2 days trying to figure out why i can't run Dlib in another project and if i'm missing something, maybe a dependency i didn't noticed. Thanks in advance :)

**Comment by takuya-takeuchi** [comment]
I guess your project setting prefer 32bit.
Please check https://stackoverflow.com/questions/12066638/what-is-the-purpose-of-the-prefer-32-bit-setting-in-visual-studio-and-how-does

Or your application is created as x86 application.
DlibDotNet does not support 32bit application.

**Comment by VinickGold** [comment]
Thank you very much @takuya-takeuchi, Dlibdotnet worked like a charm now :)
