### ISSUE TITLE
Add example or wiki for convert OpenCVSharp.Mat and EmguCV.Mat to dlib image classes

### ISSUE THREAD

**Issue by takuya-takeuchi** [takuya-takeuchi/DlibDotNet#118]
There is a lot of this issues.

**Comment by takuya-takeuchi** [comment]
EmguCV does not support .NET core.
https://github.com/emgucv/emgucv/issues/1

**Comment by valerysntx** [comment]
> EmguCV does not support .NET core.
> [emgucv/emgucv#1](https://github.com/emgucv/emgucv/issues/1)

@takuya-takeuchi, please reopen, since https://github.com/emgucv/emgucv/pull/47, 
such could be really helpful, when someone needed.

**Comment by takuya-takeuchi** [comment]
@valerysntx 
this is not emgucv issue but ZedGraph issue.
ZedGraph does not support .NET core and it is depended by emgucv.
So I cannot refer Emgu.CV package on .NET core console app.

But I already provided .NET framework console app as example.
https://github.com/takuya-takeuchi/DlibDotNet/tree/master/examples/3rdparty/EmguCV

**Comment by virzak** [comment]
Submitted a PRs to make this happen: https://github.com/emgucv/emgucv/issues/1#issuecomment-549384064
