### ISSUE TITLE
Does DlibDotNet support to get face posture?

### ISSUE THREAD

**Issue by Lam-dev** [takuya-takeuchi/DlibDotNet#121]
how can i get face posture. please help me!

**Comment by takuya-takeuchi** [comment]
Could you write the proper issue title?
Issue title is important more than you think.

the following links implement the face pose estimation uses dlib.

* https://www.learnopencv.com/head-pose-estimation-using-opencv-and-dlib/
* https://github.com/chili-epfl/attention-tracker
* https://github.com/lincolnhard/head-pose-estimation

**Comment by Lam-dev** [comment]
oh sorry, I will write the appropriate title next time. Thanks for your answer!!
