### ISSUE TITLE
System.IO.FileNotFoundException: 'shape_predictor_68_face_landmarks.dat is not found'

### ISSUE THREAD

**Issue by yusufpraditya** [takuya-takeuchi/DlibDotNet#125]
Where should I place the shape_predictor_68_face_landmarks.dat file? I'm trying to make facial landmark detection in WinForms.

**Comment by takuya-takeuchi** [comment]
Normally, you can use `ShapePredictor.Deserialize` method and pass the path of it..
So you can deploy shape_predictor_68_face_landmarks.dat at where you would like to.

**Comment by yusufpraditya** [comment]
Here is my code:
`_ShapePredictor = ShapePredictor.Deserialize(@"E:\shape_predictor_68_face_landmarks.dat");`

Got an error message:
System.BadImageFormatException: 'An attempt was made to load a program with an incorrect format.

**Comment by takuya-takeuchi** [comment]
`BadImageFormatException` means that application works on different architecture with dll.
DlibDotNet is only provided as 64bit.
So I think your application is built as 32bit.

**Comment by programmist87** [comment]
Добрый день. Вы можете подсказать, что это за файл, shape_predictor_68_face_landmarks.dat? Появился на смартфоне. Его создаёт какое-то определённое приложение? Или его создают разные приложения?
