### ISSUE TITLE
Build Errors

### ISSUE THREAD

**Issue by vinicius121** [takuya-takeuchi/DlibDotNet#13]
Hi,

After following your instructions on how to build the DlibDotNet.Native, I have encountered the following error:

`"C:\Users\User_Lab\Desktop\HFACE\DlibDotNet-master\src\DlibDotNet.Native\build\ALL_BUILD.vcxproj" (default target) (1)
->
"C:\Users\User_Lab\Desktop\HFACE\DlibDotNet-master\src\DlibDotNet.Native\build\DlibDotNet.Native.vcxproj" (default targ
et) (3) ->
(Link target) ->
  LINK : fatal error LNK1104: cannot open file 'C:\Users\User_Lab\Desktop\HFACE\dlib-19.7\examples\build\dlib_build\Rel
ease\dlib.lib' [C:\Users\User_Lab\Desktop\HFACE\DlibDotNet-master\src\DlibDotNet.Native\build\DlibDotNet.Native.vcxproj
]`
I'm using Visual Studio 2017, DLIB 19.7, giflib-5.1.4, cmake 3.11 on windows 10.

Any help?
Thanks

**Comment by takuya-takeuchi** [comment]
Sorry for late replay.
> I build it but it gave me 33 warnings. normal?
Maybe, these warnings are produced by dlib. Certainly, DlibDotNet may produce these.
But I guess these warning could not have a negative influence.

> Can you give a project example or how to start one from scratch?
For now, I do not provide WPF samples. But you can refer this project.
https://github.com/takuya-takeuchi/DlibDotNet/tree/master/examples/Image

**Comment by Sergey-Aleksandrovich** [comment]
Здравствуйте,
Помогите решить проблему с компиляцией DlibdotNet.Nativ.dll. Делаю все по инструкции, но компилятор выдает следующие ошибки:
"C:\DlibDotNet\src\DlibDotNet.Native\build\ALL_BUILD.vcxproj" (целевой объект по умолчанию) (1) ->
"C:\DlibDotNet\src\DlibDotNet.Native\build\DlibDotNet.Native.vcxproj" (целевой объект по умолчанию) (3) ->
(ClCompile конечный объект) ->
  c:\dlibdotnet\src\dlibdotnet.native\dlib\image_transforms\random_cropper.h(85): error C2039: get_min_object_size: не является членом "dlib::random_cropper" [C:\DlibD
otNet\src\DlibDotNet.Native\build\DlibDotNet.Native.vcxproj]
  c:\dlibdotnet\src\dlibdotnet.native\dlib\image_transforms\random_cropper.h(119): error C2660: dlib::random_cropper::set_min_object_size: функция не принимает 1 аргум
ентов [C:\DlibDotNet\src\DlibDotNet.Native\build\DlibDotNet.Native.vcxproj]

    Предупреждений: 0
    Ошибок: 2

**Comment by Sergey-Aleksandrovich** [comment]
Спасибо, огромное.
