### ISSUE TITLE
Use USE_AVX_INSTRUCTIONS

### ISSUE THREAD

**Issue by takuya-takeuchi** [takuya-takeuchi/DlibDotNet#130]

**Comment by takuya-takeuchi** [comment]
Related issue #129

**Comment by valerysntx** [comment]
In case if adding avx, we are dropping backwards compatibility. There should be non-avx branch keeper fresh. And it will be forked, I suppose 
I have Xeon 5450 arch now...

**Comment by takuya-takeuchi** [comment]
@valerysntx 
Ok. TBH, I don't know how faster enabling AVX will be turned on.
So I stop to turn on ABX if there is meaningless to enable it.

**Comment by takuya-takeuchi** [comment]
performance of object_detector is improved if **USE_AVX_INSTRUCTIONS** and **USE_SSE4_INSTRUCTIONS** are enabled.

### disable

````
Timings at 240p:
 - Face locations: 0.0574s (17.42 fps)
 - Face landmarks: 0.0014s (714.29 fps)
 - Encode face (inc. landmarks): 0.0040s (250.00 fps)
 - End-to-end: 0.0622s (16.08 fps)
````

### enable

````
Timings at 240p:
 - Face locations: 0.0476s (21.01 fps)
 - Face landmarks: 0.0014s (714.29 fps)
 - Encode face (inc. landmarks): 0.0044s (227.27 fps)
 - End-to-end: 0.0526s (19.01 fps)
````

**Comment by takuya-takeuchi** [comment]
@valerysntx

Can you confirm binary enabled AVX and SSE4 on your xeon machine?
I have no machine which does not support AVX and SSE4.

You can execute Build.ps1 in src/DlibDotNet.Native by Powershell Core.

#### cpu

````
pwsh Build.ps1 Release cpu 64 desktop
````

#### CUDA 10.0

````
pwsh Build.ps1 Release cuda 64 desktop 100
````

You can disable AVX and SSE4 by modifing https://github.com/takuya-takeuchi/DlibDotNet/blob/d7c82bbf0d58eb0e4391d20d5fea945b249ba931/nuget/BuildUtils.ps1#L420

I want to know perfomance issue if running AVX/SSE4 enabled binary on legacy cpu.

**Comment by valerysntx** [comment]
@takuya-takeuchi thanks, it's not a case anymore!
