### ISSUE TITLE
[QUESTION] Moving to use managed image library

### ISSUE THREAD

**Issue by eByte23** [takuya-takeuchi/DlibDotNet#132]
Hi.

Just wondering if there was any reason why you would consider moving to a managed image library e.g. ImageSharp.
To allow for easier manipulation of images? 

I have considered there may be a perf hit with marshaling data...however with the likes of Span<T> Memory<T> etc... there could be  a posiblity of making this nicer.

I know that ImageSharp also alot of similar data structs already that might be easily usable in this project.

Would this be considered for a potential pull requets, if i did the work for it?

Thanks!
Also love the work!

**Comment by takuya-takeuchi** [comment]
I'm very sorry. I do not understand what you hope. I'm not familiar with english. so I may misunderstand what you say.

DlibDotNet is wrapper library of dlib.
Do you mean that I should re-write dlib code by C#, right?

**Comment by eByte23** [comment]
Sorry about that I’ll try and simplify my question.

I am asking a reason you chose to do a full wrapper of dlib, instead of writing some of the image code in c#、i have use the ImageSharp library a fair bit before and it has alot of the same image interop classes you use.
E.g. Pixel<T>, RGB32<T> etc.

日本語でいいですか？

今はこのプロジェクトがdlibのc#のwrapperでしよね、それで別に全然いいんです、私が使っています。

ただ、もっとc#で写真のコードを使ってたらどうですか？問題になりそうですか？

私がけっこう使ったのプロジェクトがImageSharp。そのプロジェクトが写真のゴードもういっぱいあります。

分かれるんですか？すみません日本語がmainじないです。
どう思っていますか？

**Comment by takuya-takeuchi** [comment]
> I am asking a reason you chose to do a full wrapper of dlib, instead of writing some of the image code in c#

* dlib supports deep neural network components
* I'm not interesting in manipulating image.
* This project is playground for me. I can do what I want to.
** use C++, docker, cross compile, powershell and more

**Comment by eByte23** [comment]
Understood. Thanks
