### ISSUE TITLE
Tracker for object detection requires Array2DBase but I only have a Mat image type

### ISSUE THREAD

**Issue by annelau99** [takuya-takeuchi/DlibDotNet#133]
# Summary of your issue
tracker.StartTrack(Array2DBase, DlibRect), does not take Mat image. I only have a Mat image and am trying to start the tracker. How do I convert a Mat image to the Array2dbase? 

Thanks. 
# Environment
The Mat is taken from the OpenCVSharp VideoCapture.

# What did you do when you faced the problem?
1. Tried converting to byte[]
2. Tried to Construct a new Array2DBase (could not find the constructor)

## Example code:
capture.Read(img);
Mat rgb = new Mat();
Cv2.CvtColor(img, rgb, ColorConversionCodes.BGR2RGB);
Rectangle rect = new Rectangle(x1, y1, x2, y2);
tracker.StartTrack(rgb, rect);

## Output:
	Cannot convert type 'OpenCvSharp.Mat' to 'DlibDotNet.Array2DBase'	ObjectTracker

**Comment by takuya-takeuchi** [comment]
ok. there is no way to convert it to Array2D.
You can use Array2d.indexer. but it could be very slow.

I will provide new interface if dlib supports.

Thank you for your contribution.

**Comment by takuya-takeuchi** [comment]
You can use it.
https://github.com/takuya-takeuchi/DlibDotNet/tree/master/examples/3rdparty/OpenCVSharp

Thank you for your contribution.

**Comment by annelau99** [comment]
Thank you! Got it to work!
