### ISSUE TITLE
unable to find entry point named ""  in DLL DlibDotnet.native.Dll ...

### ISSUE THREAD

**Issue by Azizgaamouz** [takuya-takeuchi/DlibDotNet#14]
I try to run the Facedetction C# example but i all the time receive an exception. all Dlls (Dlibdotnet.dll, dlibdotnet.native.dll) are in the same folder than Facedetection.dll.
I'm using dotnet core 2 with visual studio 2017 and windows 8.1
https://user-images.githubusercontent.com/36734999/36975925-ad4b3b76-2073-11e8-91b7-f02f43ad86fc.png
any idea ?
Thanks

**Comment by takuya-takeuchi** [comment]
Sorry for late reply.
I guess DlibDotNet.Native.dll was not build correctly. Because your dll is too small.
DlibDotNet.Native.dll contains many of dlib contents. 

You could see what is happen after used dependency walker.

**Comment by takuya-takeuchi** [comment]
There is no additional report.
