### ISSUE TITLE
Not getting expected ObjectDetector results 

### ISSUE THREAD

**Issue by steinborge** [takuya-takeuchi/DlibDotNet#140]
Attempting to use a trained SVM file to replicate results achieved in Python using DLIB simple_object_detector. 

# Environment

Windows 10, VS2019

# What did you do when you faced the problem?

Attempting to mimic DLIB's Python simple_object_detector results. I have a SVM file trained using Python. I am able to open it and execute detection using DlibDotNet but I am getting different results for the exact same files in Python. 

Part of issue is there doesn't appear to be any equivalent of simple_object_detector in C#/C++ libraries - and I can't seem to find any obvious configuration values that simple_object_detector set when created in Python .

I have used the sample  Dlib object detection settings (see below) - the svm is opened successfully and detection occurrs, but there are very few matches.

The image files are loaded using OpenCV. 

I have included initialisation and object  logic - I have also included Python source which is working. 

Happy to post svm file and sample images if that would help. 

## Example code:
```
            //           
            //initialise detector 
            DlibDotNet.ObjectDetector<DlibDotNet.ScanFHogPyramid<DlibDotNet.PyramidDown, DlibDotNet.DefaultFHogFeatureExtractor>> detector;

            //
            var tmp2 = new DlibDotNet.ScanFHogPyramid<DlibDotNet.PyramidDown, DlibDotNet.DefaultFHogFeatureExtractor>(6);
            detector = new DlibDotNet.ObjectDetector<DlibDotNet.ScanFHogPyramid<DlibDotNet.PyramidDown, DlibDotNet.DefaultFHogFeatureExtractor>>(tmp2);
            detector.Deserialize("plates2.svm");
            var img = CvInvoke.Imread("somefile.jpg");

            //create RGB 
            Mat rgb = new Mat();
            CvInvoke.CvtColor(img, rgb, Emgu.CV.CvEnum.ColorConversion.Bgr2Rgb);

            //convert to dlib format
            var dlimg = ConvertMATtoDLIB(rgb);


            //attempt to detect.. return bounding rectangles if successful 
            var dets = detector.Operator(dlimg).ToList();

        /// <summary>
        /// Convert CV MAT to DLIB
        /// </summary>
        ///https://github.com/takuya-takeuchi/DlibDotNet/wiki/How-to-convert-EmguCV.Mat-to%3F
        /// <param name="mat"></param>
        /// <returns></returns>
        DlibDotNet.Matrix<DlibDotNet.RgbPixel> ConvertMATtoDLIB(Mat mat)
        {
            var array = new byte[mat.Width * mat.Height * mat.ElementSize];
            mat.CopyTo(array);

            var image = new DlibDotNet.Matrix<DlibDotNet.RgbPixel>(array, mat.Height, mat.Width, mat.ElementSize);

            return image;
        }



from imutils import paths
from imutils import resize
import argparse
import dlib
import cv2

# construct the argument parse and parse the arguments
ap = argparse.ArgumentParser()
ap.add_argument("-d", "--detector", required=True, help="SVM Object detector file")
ap.add_argument("-t", "--testing", required=True, help="Path to images to test")
args = vars(ap.parse_args())

# load the detector
detector = dlib.simple_object_detector(args["detector"])

# loop over the testing images
for testingPath in paths.list_images(args["testing"]):
  # load the image and make predictions
  image = cv2.imread(testingPath)


  boxes = detector(cv2.cvtColor(image, cv2.COLOR_BGR2RGB))

  # loop over the bounding boxes and draw them
  for b in boxes:
    (x, y, w, h) = (b.left(), b.top(), b.right(), b.bottom())
    cv2.rectangle(image, (x, y), (w, h), (0, 255, 0), 2)

  # show the image

  cv2.imshow(testingPath, image)
  cv2.waitKey(0)

```

**Comment by takuya-takeuchi** [comment]
dlib Python API does not equal to dlib C++ API. (ex: python dlib.get_frontal_face_detector)

### simple_object_detector of C++ for python
typedef object_detector<scan_fhog_pyramid<pyramid_down<6> > > simple_object_detector;

### implementation of object_detector

#### python

dlib::object_detector<dlib::scan_fhog_pyramid<dlib::pyramid_down<6u>, dlib::default_fhog_feature_extractor>>.operator calls 
https://github.com/davisking/dlib/blob/ba361d73abb06eda6a2a1bba397a680879610f0a/tools/python/src/object_detection.cpp#L369

#### C++
https://github.com/davisking/dlib/blob/efd4e27488d9291b2efd4a7076d572d7765fb4dd/dlib/image_processing/object_detector.h#L500

So simple_object_detector.operator implementations are not same.

**Comment by steinborge** [comment]
Thanks for your quick reply.

I understand they're not the same - I see that the Python simple_object_detector is a wrapper.
https://github.com/davisking/dlib/blob/master/tools/python/src/simple_object_detector.h 

From what I understand I should be able to use the svm by initialising the DlibDotNet object detector with the same configuration as simple_object_detector - so is 
typedef object_detector<scan_fhog_pyramid<pyramid_down<6> > > simple_object_detector;

equivalent of the following?

//initialise detector 
DlibDotNet.ObjectDetector<DlibDotNet.ScanFHogPyramid<DlibDotNet.PyramidDown, DlibDotNet.DefaultFHogFeatureExtractor>> detector;

//
var tmp2 = new DlibDotNet.ScanFHogPyramid<DlibDotNet.PyramidDown, DlibDotNet.DefaultFHogFeatureExtractor>(6);
            detector = new DlibDotNet.ObjectDetector<DlibDotNet.ScanFHogPyramid<DlibDotNet.PyramidDown, DlibDotNet.DefaultFHogFeatureExtractor>>(tmp2);
            detector.Deserialize("plates2.svm");

That's what I'm using and it deserialises and performs detection, the results are not the same. 

Thanks again for your time.

**Comment by takuya-takeuchi** [comment]
Paarameter could be correct.
You have to implement python wrapper as C#.
You may use https://github.com/takuya-takeuchi/FaceRecognitionDotNet/blob/master/src/FaceRecognitionDotNet/Dlib/Python/SimpleObjectDetector.cs

**Comment by takuya-takeuchi** [comment]
No Response
