### ISSUE TITLE
Dlib.GetFrontalFaceDetector throws System.Exception 

### ISSUE THREAD

**Issue by bruce987** [takuya-takeuchi/DlibDotNet#142]
When executing Dlib.GetFrontalFaceDetector, I get a System.Exception: 'Failed to find dll "DlibDotNetNative", for processor architiecture AMD64.'

Running on Windows 10, VS2019 Enterprise 16.3.2, application is a Core 3.0 C# application.

I tried different libraries, all produce the same error.

Am I missing an additional library? I do not see any DlibDotNetNative dll in nuget.

Thanks,
Bruce

**Comment by takuya-takeuchi** [comment]
Which nuget package did you use?
If CUDA or MKL, install or deploy dependencies.

You can use dependecy Walker to find missing library.

Or, .net core 3.0 may occur error. I did not test 3.0 yet.

How do you run program?

**Comment by bruce987** [comment]
I tried several with the same results.
Currrently I have DlibDotNet - v19.18.0.20190928. I tried DlibDotNet.CUDA101, DlibDotNetUWP. For CUDA I have v10.0 and v10.1 installed, plus cuDNN-7.6.3-cuda10.0 and cuda10.1. I copied the libraries over to the bin\debug folder.

When I load DlibDotNet into Dependencies I shows DlibDotNetNative and DlibDotNetNatviceDnn as missing. I'm not sure where those are or how they get loaded?

**Comment by bruce987** [comment]
I have a little bit more information. The project shows the DlibDotNetNative dll's, but the link was to win-AnyCPU, which does not exist. I changed my project to use x64 and added the package back in. Now it finds the dll's and copies them to the bin folder, but I still get the AMD64 architecture error when I run.

**Comment by takuya-takeuchi** [comment]
Could you check the dotnet sdk info?

````
where dotnet
````

I guess you installed x86 .net sdk.

**Comment by bruce987** [comment]
I ran “where dotnet” from a cmd window and got this back … “C:\Program Files\dotnet\dotnet.exe” which tells me that it’s x64.

 

Any other thoughts?

 

-Bruce

**Comment by takuya-takeuchi** [comment]
Sorry, late reply.

I created new Hyper-V machine and try sample program.

Machine environmental is

* Windows 10 1903 English
* Visual Studio 2019 Community Edition 16.3.2

I selected the only following workloads.

* .NET desktop development
* Desktop development with C++
* .NET Core cross-platform development

I did not select and deselect any component on Individual components tab.

And program is

````csharp
using System;
using DlibDotNet;

namespace Issue142
{
    class Program
    {
        static void Main(string[] args)
        {
            using (var faceDetector = Dlib.GetFrontalFaceDetector())
            using (var image = Dlib.LoadImage<RgbPixel>("Lenna.png"))
            {
                var dets = faceDetector.Operator(image);
                Console.WriteLine($"{dets[0].Area}");
            }
        }
    }
}
````

Import **DlibDotNet 19.18.0.20190928 (not CUDA and MKL, pure CPU)**
It works fine.

![image](https://user-images.githubusercontent.com/6241854/66257634-b6f46b80-e7d6-11e9-8552-40993079395e.png)

![image](https://user-images.githubusercontent.com/6241854/66257636-c2479700-e7d6-11e9-9c00-abd3d41d29ea.png)

**Comment by bruce987** [comment]
Hi Takuya,

 

I created a new project following your example and had no issues, ran as expected. 

 

Since I’m just now learning ML, I have a solution folder with several projects. This is where the problem came up. I took the Issue142 project and added it to my solution. Same problem occurred. I then deleted the solution file and recreated the solution with your example. Now the problem doesn’t occur. 

 

The problem had something to do with the solution file. I took a look at it, but didn’t see anything our of the ordinary… now the solution file is gone – deleted.

 

Quick question, can your library detect objects other than faces? I have a trained model that used several 6000 images. It’s an object found on the space station. We are trying to train a DNN to find this object.

 

Thanks for the help,

Bruce

**Comment by takuya-takeuchi** [comment]
> Quick question, can your library detect objects other than faces? I have a trained model that used several 6000 images. It’s an object found on the space station. We are trying to train a DNN to find this object.

I have never trained the own dataset to detect face image.
But default model file that be contained dlib library can detect human face well.

BTW, I think 6000 images is a bit small size.

**Comment by bruce987** [comment]
Thanks for the help.

 

Yes I have around 500,000 images of the device using different angles and lighting.

 

-Bruce

**Comment by bruce987** [comment]
Closing issue. I was able to use OpenCvSharp4 and Emgu.CV to train an image and find it in a live camera fed. Now to resolve the issues with OpenPoseDotNet.

**Comment by Robotuner** [comment]
I still can get it to work.  I am loading the nuget package DlibDotNet 19.20.9.20200725 which allows the program to find GetFrontalFaceDetector, however the build fails with the message that it cannot copy the DlibDotNet.19.20.0.20200725\runtimes\win-ANYCPU\native\DlibDotNetNativeDnn.dll because it isn't found.  When I look in the packages folder under runtimes, there isn't a win-AnyCPU folder.   It seems that even if I change the build configuration to x64, I get the same message, trying to copy the DlibDotNetNativeDnn.dll from the win-AnyCPU folder.
