### ISSUE TITLE
MMOD Detection with ZED camera SDK

### ISSUE THREAD

**Issue by rmtttt** [takuya-takeuchi/DlibDotNet#143]
# MMOD Detection with ZED camera SDK

# Environment

Windows 10
Cuda 10
Intel Xeon CPU
Nvidia P5000

# What did you do when you faced the problem?

I'm trying to use mmod detector with ZED camera as an input.
I fetching an image from ZED SDK (cuda accelerated) to OpenCV, then covering CVMat to Dlib matrix to run detector. Everything is working until I trying to input an image from ZED SDK to detector -  since both are runing on cuda I've got cuda errors.

## Example code:

```
 
```

## Output:

```
DllName DlibDotNetNativeDnn;
DriverVersion 10020;
ErrorCode 7;
ErrorName cudaErrorLaunchOutOfResources;
ErrorMessage too many resources requested for launch;
RuntimeVersion 10000;

DllName DlibDotNetNativeDnn;
DriverVersion 10020;
ErrorCode 8;
ErrorName cudaErrorInvalidDeviceFunction;
ErrorMessage invalid device function;
RuntimeVersion 10000;
```

## What did you intend to be?
What would be a solution to have both - ZED SDK and MMOD Detector - ruining in one application?

**Comment by takuya-takeuchi** [comment]
@rmtttt 
Thank you for your using issue template!!

I guess you used DlibDotNet.CUDA100. But your machine installed CUDA 10.1 update1 or 2?
Could you tell me exact CUDA version?

I concern 'cudaErrorLaunchOutOfResources'. But we should check cuda version at first.

**Comment by rmtttt** [comment]
Hi @takuya-takeuchi 
Thank you for your great job!

That's right, I'm using DlibDotNet.CUDA100 and CUDA version is correct - it is 10.0 - the same is needed for latest ZED SDK. 

Both parts works correctly in separate applications: when I use webcam (instead of ZED SDK) with MMOD detector - it runs just great! I also can run ZED SDK, fetch and display image separately, even at the same time when detector running on other camera (so it's not about memory).

The problem appears when I combine two applications - I would explain it as some kind of conflict on CUDA: first ZED creates a CUDA thread, then detector in the same application tries to create other CUDA thread and CUDA throws an exception.. Or something like this.

**Comment by takuya-takeuchi** [comment]
It may be wrong. CUDA could not support multithreading.
https://answers.opencv.org/question/68412/multithreading-opencv-gpu-crash/

Sorry, I was not able to find document to understand easily.

**Comment by rmtttt** [comment]
It's wrong, CUDA supports multithreading.

The problem was that I didn't implement any threading in my application - since I put hole detector part to AsyncTask it works correctly.
Thank you, somehow you helped to solve the problem :)

Let my ask one more question.
Is there a method to convert DlibDotNet.Matrix<BGRA> to DlibDotNet.Matrix<RGB>? On GPU?

**Comment by rmtttt** [comment]
ah, sorry

it was DlibDotNet.Matrix< BGRA > to DlibDotNet.Matrix< RGB >

thnx

**Comment by takuya-takeuchi** [comment]
It seems the reporter resolve issue.
