### ISSUE TITLE
execution time of detect a face

### ISSUE THREAD

**Issue by davidchou6397** [takuya-takeuchi/DlibDotNet#144]
I have use your package to detect a face,but it cost 2s to do that ,what I wrong with my code

 Bitmap bitmap=(Bitmap)pictureBox1.Image.Clone();
                var watch = System.Diagnostics.Stopwatch.StartNew();
                // the code that you want to measure comes here
                
                var data = bitmap.LockBits(new System.Drawing.Rectangle(0, 0, bitmap.Width, bitmap.Height),
       System.Drawing.Imaging.ImageLockMode.ReadOnly, bitmap.PixelFormat);
                try
                {
                    var array = new byte[data.Stride * data.Height];
                    Marshal.Copy(data.Scan0, array, 0, array.Length);
                    using (var img = Dlib.LoadImageData<RgbPixel>(array, (uint)bitmap.Height, (uint)bitmap.Width, (uint)data.Stride))
                    {
                        using (var fd = Dlib.GetFrontalFaceDetector())
                        using (var sp = ShapePredictor.Deserialize("shape_predictor_68_face_landmarks.dat"))
                        {
                            // find all faces in the image
                            var faces1 = fd.Operator(img);
                            foreach (var face in faces1)
                            {// find the landmark points for this face
                                var shape = sp.Detect(img, face);
                                // find the landmark points for this face
                                count = (int)shape.Parts;
                                // draw the landmark points on the image
                                for (var i = 0; i < shape.Parts; i++)
                                {
                                    /*    var point = shape.GetPart((uint)i);
                                        var rect = new DlibDotNet.Rectangle(point);
                                        Dlib.DrawRectangle(img, rect, color: new RgbPixel(255, 255, 0), thickness: 4);*/
                                }
                            }
                        }

                    }
                    watch.Stop();
                    count = (int)watch.ElapsedMilliseconds;
                    

                }
                finally
                {
                    bitmap.UnlockBits(data);
                }

**Comment by takuya-takeuchi** [comment]
Detection time depends on image size and nuget package.
I guess you used DlibDotNet.
CUDA or MKL could improve performance.

**Comment by takuya-takeuchi** [comment]
1 more point.
You should incude tine of Deserialize method.

**Comment by takuya-takeuchi** [comment]
No Response
