### ISSUE TITLE
Examples/DnnSemanticSegmentationTrain Error: RgbPixel does not support

### ISSUE THREAD

**Issue by WJ-GitHub** [takuya-takeuchi/DlibDotNet#146]
Great Project !
Examples/DnnSemanticSegmentation is running fine with example datasets on CPU and GPU.

Examples/DnnSemanticSegmentationTrain is aborting with error:

System.NotSupportedException: RgbPixel does not support at DlibDotNet.Dnn.LossMulticlassLogPerPixel.Train[T](DnnTrainer`1 trainer, IEnumerable`1 data, IEnumerable`1 label) at DnnSemanticSegmentationTrain.Program.Main(String[] args) in DlibDotNet-master\examples\DnnSemanticSegmentationTrain\Program.cs:line 160

thrown by LossMulticlassLogPerPixel.cs at line 333:

switch (ret)
                {
                    case NativeMethods.ErrorType.MatrixElementTypeNotSupport:
                        throw new NotSupportedException($"{dataElementTypes} does not support");
                }

How to fix this error ?
Best regards

**Comment by takuya-takeuchi** [comment]
@WJ-GitHub 
Thank you for reporting issue.
Yes, there is any problem on this example.
I tuckle this issue.

Please give me time.

**Comment by takuya-takeuchi** [comment]
OK, fix complete

**Comment by WJ-GitHub** [comment]
Thank you so much for really fast fixing !
I have compiled the given branch and run on CPU. No errors, until now ! CPU-Training is running for test purpose.
I will compile for GPU usage and give you feedback !
Best regards

**Comment by takuya-takeuchi** [comment]
@WJ-GitHub 
It's my pleasure.
You can reopen it or create new issue if you want anytime.
