### ISSUE TITLE
Unable to load DLL 'DlibDotNetNative'

### ISSUE THREAD

**Issue by zlyxm** [takuya-takeuchi/DlibDotNet#148]
# win7 64 Exception: Unable to load DLL 'DlibDotNetNative'

# Environment

win7 x64 
DlibDotNet 19.18.0.20190928

# Run the following code,I found in the same environment:
1, win10 64 DlibDotNet 19.18.0.20190928  success
2, win10 64 DlibDotNet 19.17.0.20190623  success
1, win7  64 DlibDotNet 19.18.0.20190928  failure
2, win7  64 DlibDotNet 19.17.0.20190623  success

## Example code:

```
            FaceRecognition fr;
            fr = FaceRecognition.Create(@"D:\Environmental\face_recognition_models");
            var dlibToComBuf = FaceRecognition.LoadImageFile("sfz.bmp");
            var enToCompare = fr.FaceEncodings(dlibToComBuf).First();
            Console.WriteLine(enToCompare);

```

## Output:
![image](https://user-images.githubusercontent.com/27178240/67546583-58fcd900-f72f-11e9-9ed9-f6f942fd1903.png)

## What did you intend to be?
Sorry, can you help me find the reason?

**Comment by takuya-takeuchi** [comment]
I created Windows7 English VM and sample program.
But issues did not occur.
I did the following steps to reproduce your issue.

1. Create .NET Framework console app by .NET 4.6.1 on Vsiual Studio 2017
2. Install FaceRecognitionDotNet 1.2.3.13
3. Update DlibDotNet to 19.18.20190928

![image](https://user-images.githubusercontent.com/6241854/67612862-dd0f9900-f7e1-11e9-924a-b40f60ed14b2.png)

**Comment by zlyxm** [comment]
I am sorry for the late reply.This may be the wrong version of DlibDotNet for FaceRecognitionDotNet.Next time, I must test it rigorously and ask questions again.

**Comment by takuya-takeuchi** [comment]
@zlyxm 
It doesn’t matter.
i'm looking forward to your next report!!

**Comment by LuckyMallari** [comment]
This is because of https://github.com/takuya-takeuchi/DlibDotNet/blob/b78c05f077d8fff13d2824c077ed7ace87fc361f/src/DlibDotNet/PInvoke/WindowsLibraryLoader.cs#L193

If you build ur app as x64, the dll must be in 
`dll\x64` folder also because of:

https://github.com/takuya-takeuchi/DlibDotNet/blob/b78c05f077d8fff13d2824c077ed7ace87fc361f/src/DlibDotNet/PInvoke/WindowsLibraryLoader.cs#L23

**Comment by k3cloudqxy** [comment]
@takuya-takeuchi    can you give me your  console app demo ,my app also have the exception  Unable to load DLL 'DlibDotNetNative',   I use DlibDotNet.CUDA101 19.18.0.20190928,
![image](https://user-images.githubusercontent.com/11499014/68769424-3b040380-065f-11ea-9b43-edc58d89f781.png)

**Comment by takuya-takeuchi** [comment]
@k3cloudqxy 
Here you are.
[#148.zip](https://github.com/takuya-takeuchi/DlibDotNet/files/3841507/148.zip)

**Comment by k3cloudqxy** [comment]
thank you very much

**Comment by zlyxm** [comment]
I know!
I tried the VM normally! And the win7 in English and Chinese is OK. It also runs normally on an i5 win7.
But I am 100% on a CPU N3160 computer, I am sure that the hardware is not compatible, but the strange is that the previous version is normal.
![image](https://user-images.githubusercontent.com/27178240/68824169-daadaa00-06d0-11ea-9e70-40bc70ca524d.png)

**Comment by takuya-takeuchi** [comment]
@zlyxm 
Yes, latest version enabled AVX instruction.
So legacy cpu does not work.
 Please check #153
