### ISSUE TITLE
Help for using with Unity 3D

### ISSUE THREAD

**Issue by minhkhue** [takuya-takeuchi/DlibDotNet#15]
I'm actually developing with Unity3D on Win 64. I wanna use DlibDotNet with Unity. So the idea is that I call WebcamTexture class inside of Unity for capturing image from webcam. Then, this class can return to me a Color32 Array ( a Color32 type contains 4 bytes of rgba, just like RGBAlphaPixel ). Next, i convert this color32 array into byte array by;

byte[] bytes = new byte[colors.Length * 4];
            for (int i = 0; i < bytes.Length/4; i += 4)
            {
                bytes[i]= colors[i].r;
                bytes[i+1] = colors[i].g;
                bytes[i+2] = colors[i].b;
                bytes[i+3] = colors[i].a;
               
            }

Finally, i apply this into LoadImageData function in order to recognize the number of face. (like Face Detection example) But the result is always 0.

Can you give me an idea ?

Thanks

**Comment by takuya-takeuchi** [comment]
You tried to use FrontalFaceDetector.Detect method for RGBA image?
If so, this method does not support RGBA image due to ristricts of dlib.

However, I may misunderstand what you faces to.
Would you show your code to recognize faces?

**Comment by minhkhue** [comment]
No, (i've tried this idead but, yes, the error message is "RGBAlphaPixel can not converted to Uint8")
What i desire to do is to detect the faces on resources online from the webcam and not from the images stocked on the machine. So instead of using LoadImage function (like used in the exemple); i use LoadImageData from a byte array to get Array2D<byte>. This byte array, I convert from the Color32 array provided by Unity.

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.IO;
using UnityEngine;
using DlibDotNet;
using System.Runtime.InteropServices;

namespace TestDlibDotNet
{
    public class Class1
    {
         public int UnityTest(Color32[] color_array)
        {
            int lengt = 0;
            using (var detector = FrontalFaceDetector.GetFrontalFaceDetector())
            using (var img = Dlib.LoadImageData<Byte>(Color32ArrayToByteArray(color_array), (uint)640, (uint)480, (uint)4))
            {
                Dlib.PyramidUp(img);
                var dets = detector.Detect(img);

                try
                {
                    lengt = dets.Length;
                }
                catch (InvalidCastException e)
                {
                }

            }
            return lengt;

        }
        public byte[] Color32ArrayToByteArray(Color32[] colors)
        {
            byte[] bytes = new byte[colors.Length * 4];
            for (int i = 0; i < bytes.Length/4; i += 4)
            {
                bytes[i]= colors[i].r;
                bytes[i+1] = colors[i].g;
                bytes[i+2] = colors[i].b;
                bytes[i+3] = colors[i].a;
               
            }
            return bytes;
        }


    }
}

**Comment by takuya-takeuchi** [comment]
ok.
LoadImageData does not suit for this case.
LoadImageData<T> treats argments as T type image. It means that this function does not convert color format.

If you expect this function convert image to grayscale, it's wrong.
In addition, 4th argment of LoadImageData is not channels but srtide.
In this case, It could be 640 x 4.

Therefore, you should convert image to grayscale or RGB manually.

**Comment by minhkhue** [comment]
Thanks, so finally, i need to manually convert my image resources from webcam to grayscale and then convert the last one to byte array ? What it means The 4th parameter (uint step) in LoadImageData ? :D

**Comment by takuya-takeuchi** [comment]
Step is Stride. This parameter equals to last parameter of System.Windows.Media.Imaging.BitmapSource.Create.
Generally, stride is byte size per line and it equals to image width * channels. However, some image format; eg bmp does not equals to.
Please get further information from https://en.wikipedia.org/wiki/BMP_file_format.
