### ISSUE TITLE
is the convert dictionary right ? "BitmapExtensions"

### ISSUE THREAD

**Issue by RainkLH** [takuya-takeuchi/DlibDotNet#150]
static BitmapExtensions()
        {
            OptimumChannels = new Dictionary<PixelFormat, int>();
            OptimumChannels[PixelFormat.Format24bppRgb] = 3;
            OptimumChannels[PixelFormat.Format8bppIndexed] = 1;
            OptimumChannels[PixelFormat.Format32bppRgb] =
            OptimumChannels[PixelFormat.Format32bppArgb] = 4;

            OptimumConvertImageInfos = new Dictionary<PixelFormat, ConvertInfo<ImageTypes>[]>();
            OptimumConvertImageInfos[PixelFormat.Format8bppIndexed] = new[]
            {
                new ConvertInfo<ImageTypes> { Type = ImageTypes.UInt8 }
            };
            **OptimumConvertImageInfos[PixelFormat.Format24bppRgb] = new[]
            {//!!!!!!!!!   Format24bppRgb->  RgbPixel  ??????????    ---------------------------
                new ConvertInfo<ImageTypes>{ Type = ImageTypes.RgbPixel, RgbReverse = true }
            };
            OptimumConvertImageInfos[PixelFormat.Format24bppRgb] = new[]
            {//!!!!!!!!    Format24bppRgb->  BgrPixel   ??????????  ----------------------------------
                new ConvertInfo<ImageTypes>{ Type = ImageTypes.BgrPixel, RgbReverse = false }
            };**
            OptimumConvertImageInfos[PixelFormat.Format32bppArgb] = new[]
            {
                new ConvertInfo<ImageTypes> { Type = ImageTypes.RgbAlphaPixel, RgbReverse = true }
            };
            OptimumConvertMatrixInfos = new Dictionary<PixelFormat, ConvertInfo<MatrixElementTypes>>();
            OptimumConvertMatrixInfos[PixelFormat.Format8bppIndexed] = new ConvertInfo<MatrixElementTypes> { Type = MatrixElementTypes.RgbPixel };
            OptimumConvertMatrixInfos[PixelFormat.Format24bppRgb] = new ConvertInfo<MatrixElementTypes> { Type = MatrixElementTypes.RgbPixel, RgbReverse = true };
            OptimumConvertMatrixInfos[PixelFormat.Format32bppArgb] = new ConvertInfo<MatrixElementTypes> { Type = MatrixElementTypes.RgbAlphaPixel, RgbReverse = true };

            for (var i = 0; i < _8bppColorPalette.Length; i++)
                _8bppColorPalette[i] = Color.FromArgb(i, i, i);
        }

**Comment by takuya-takeuchi** [comment]
@RainkLH 
TBH, BitmapExtensions is for hobby use.
So this method does not cover all use cases.

**Comment by takuya-takeuchi** [comment]
close
