### ISSUE TITLE
MatrixToMat

### ISSUE THREAD

**Issue by k3cloudqxy** [takuya-takeuchi/DlibDotNet#151]
# Summary of your issue
there is a example  MatToMatrix in examples/3rdparty/OpenCVSharp， how can i convert Matrix to 
 Mat ?
# Environment

Write your environment.
win10
# What did you do when you faced the problem?
 how can i convert Matrix to 
 Mat ?
//write here

## Example code:

```
paste your core code
```

## Output:

```
paste your output
```

**Comment by takuya-takeuchi** [comment]
@k3cloudqxy 
You can refer it.
https://github.com/shimat/opencvsharp/issues/173

**Comment by k3cloudqxy** [comment]
thanks for your reply, I tried this code, it works， resultImage  is Matrix<RgbPixel>

                int rows = resultImage.Rows;
                int cols = resultImage.Columns;

                var cvMat = new OpenCvSharp.Mat(rows, cols, OpenCvSharp.MatType.CV_8UC3);
                var indexer = cvMat.GetGenericIndexer<Vec3b>();
                for (int y = 0; y < rows; y++)
                {
                    for (int x = 0; x < cols; x++)
                    {
                        byte blue = resultImage[y, x].Blue;
                        byte green = resultImage[y, x].Green;
                        byte red = resultImage[y, x].Red;
                        Vec3b newValue = new Vec3b(blue, green, red);
                        indexer[y, x] = newValue;
                    }
                }
