### ISSUE TITLE
Not x64: dlibdotnet.cuda101\19.18.0.20190928

### ISSUE THREAD

**Issue by LuckyMallari** [takuya-takeuchi/DlibDotNet#152]
# Summary of your issue
Nuget package for dlibdotnet.cuda101\19.18.0.20190928 was built on AnyCPU, and not x64.

![image](https://user-images.githubusercontent.com/6183345/68460899-cb54cb00-01bd-11ea-93e3-6f7690c4805a.png)

```
System.Exception
  HResult=0x80131500
  Message=Failed to find dll "DlibDotNetNative", for processor architecture AMD64.
  Source=DlibDotNet
  StackTrace:
   at DlibDotNet.WindowsLibraryLoader.LoadLibrary(String dllName) in E:\Users\Lucky\Documents\Source\external\DlibDotNet\src\DlibDotNet\PInvoke\WindowsLibraryLoader.cs:line 153
```

# Environment
Win10

# What did you do when you faced the problem?

Target x64 on DlibDotNet

## What did you intend to be?
built for x64 arch

**Comment by takuya-takeuchi** [comment]
I cannot understand what the reporter intent to.
And additional menthion.
