### ISSUE TITLE
DlibDotNetNative not compatible with older CPU's

### ISSUE THREAD

**Issue by h2moller** [takuya-takeuchi/DlibDotNet#153]
# Summary of your issue
When running components using DlibDotNet on server with older CPU's I keep getting the following error: System.DllNotFoundException: Unable to load DLL 'DlibDotNetNative': A dynamic link library (DLL) initialization routine failed. (Exception from HRESULT: 0x8007045A)

I am using the 19.18.0.20190928 version of the DlibDotNet Nuget package. 

The exact same code base works correctly on newer infrastructure. I don't have a large set of servers to test on but Intel Xeon E5520 does not work. Also tried on some older work stations running Intel i5-760 and also not working.

I was not able to test the anything between the 4th gen i5 and the 760. I can confirm that 4th gen intel CPU's and later works as expected. I have not tested any AMD CPU's

# Environment

Windows Server 2012 R2 Intel Xeon E5520
.Net Framework 4.7.2

Windows 10 Intel i5-760
Visual Studio 2019.
.Net Framework 4.7.2

# What did you do when you faced the problem?

Made sure DlibDotNet, DlibDotNetNative, DlibDotNetNativeDnn dlls is built for CPU only and included in directory. 
Installed C++ 2017 runtime on all machines. 
Using Dependencies tool to check if any dependencies are missing.

Tested app on multiple machines to narrow down it's a CPU compatibility issue and not any file that is missing.

**Comment by takuya-takeuchi** [comment]
@h2moller 
On Aug 2019, I enabled AVX instruction for dlibdotnet.
AVX is supported form Core Gen2 series.

So you may use old dlibdotnet.
https://www.nuget.org/packages/DlibDotNet/19.17.0.20190813

**Comment by vantam123** [comment]
System.DllNotFoundException: Unable to load DLL 'DlibDotNetNative': A dynamic link library (DLL) initialization routine failed. (Exception from HRESULT: 0x8007045A)

i am uisng CPU LattePanda 2GB/32GB (Intel(R) Atom x5-Z8350)

**Comment by takuya-takeuchi** [comment]
@vantam123 
Same reason. Atom x5-Z8350 looks like to not support AVX.
https://en.wikipedia.org/wiki/Intel_Atom

**Comment by popy2k14** [comment]
> @h2moller
> On Aug 2019, I enabled AVX instruction for dlibdotnet.
> AVX is supported form Core Gen2 series.
> 
> So you may use old dlibdotnet.
> https://www.nuget.org/packages/DlibDotNet/19.17.0.20190813

thx a lot.
This solved the compatibility problem on several celeron J1900 machines.
