### ISSUE TITLE
Can't compile DlibDotNet.Native.Dnn - out of memory on 32GB machine

### ISSUE THREAD

**Issue by kaamil1984** [takuya-takeuchi/DlibDotNet#154]
# Environment

Windows 10
Visual Studio 2017 installed
Visual Studio 2019 installed
Cmake 3.15.5 (from kitware.com/cmake)
32GB RAM (0MB pagefile/swap)

# What I did:

I took 19.17.0.20190813 release tag.

`cmake -G "Visual Studio 15 2017 Win64" -T host=x64 ..`
`cmake --build . --config Release`

## Result:

>   ...
>   cuda.cpp
>   config.cpp
>   input.cpp
>   layers.cpp
>   loss.cpp
>   loss_metric.cpp
>   loss_mmod.cpp
>   loss_multiclass_log.cpp
>   loss_multiclass_log_per_pixel.cpp
>   **... fatal error C1060 ...** 

(out of memory)

Compiler took all my memory (about 25GB of 32GB).

I tried Debug and Release builds with similar results.

**Comment by kaamil1984** [comment]
I finally compiled it after turning on pagefile on my precious NVMe SSD.

Compiler total memory usage was hitting about 33GB.

**Is this normal?**

Btw, I found that make -j parameter can help with make consuming too much ram: https://stackoverflow.com/questions/11639524/make-j-ram-limits

**Comment by takuya-takeuchi** [comment]
Yes, this build requires huge ram.
But latest code could reduce usage ram.

And we use cmake.
So we cannot use -j parameter.
However, there may be alternative option.

**Comment by kaamil1984** [comment]
Thank you for quick response.

It is weird that Dlib is not distributed as compiled binaries...

> And we use cmake.
> So we cannot use -j parameter.

Right. In cmake there is --parallel option. 

For now - I'm satisfied.
