### ISSUE TITLE
Is there some reasony why AVX is not enabled by default?

### ISSUE THREAD

**Issue by kaamil1984** [takuya-takeuchi/DlibDotNet#155]
Hi,

Is there some reason why only SSE2 instructions are enabled by default when you build DlibDotNet.Native and DlibDotNet.Native.Dnn?

AVX is supported by CPUs from 2012, and now we have 2019.

Thank you for creating maintaining this project!

Regards
Kamil

**Comment by kaamil1984** [comment]
I found that one reason
https://github.com/takuya-takeuchi/DlibDotNet/issues/153

and also I found that now it is enabled in current version. You wrote

> On Aug 2019, I enabled AVX instruction for dlibdotnet.
> AVX is supported form Core Gen2 series.

**Will AVX work** in DlibDotNet if I enable it in DlibDotnet.Native and DlibDotnet.Native.Dnn compilation?

**Comment by takuya-takeuchi** [comment]
> Will AVX work in DlibDotNet 19.17.0.0 if I enable it in DlibDotnet.Native and DlibDotnet.Native.Dnn compilation?
Last version of 19.17 supports AVX, to be exact.

And I forgot to push 19.18.0.20190928 tag.
I had pushed just now.

**Comment by takuya-takeuchi** [comment]
May be able to close
