### ISSUE TITLE
Missing basic image procesing functions

### ISSUE THREAD

**Issue by ejoebstl** [takuya-takeuchi/DlibDotNet#159]
Hello, 

I'm unable to find basic image processing functions from dlib, for example:
* binary_erosion
* binary_dilation
* binary_close
* binary_open

Are those implemented?

**Comment by takuya-takeuchi** [comment]
@ejoebstl 
TBH, these functions are not fit for C# wrapper.
Because, they use non-type template parameter for structure element.
http://dlib.net/dlib/image_transforms/morphological_operations.h.html

So it is hard for C# side to specify dynamic structure size.

**Comment by takuya-takeuchi** [comment]
It is difficult to implement it.
