### ISSUE TITLE
Trying to build on MacOS

### ISSUE THREAD

**Issue by thomasd3** [takuya-takeuchi/DlibDotNet#16]
When trying to build DlibDotNetNative on MacOS, I get the following:

[thomas:~/Downloads/DlibDotNet-master/src/DlibDotNet.Native/build] $ cmake --build . --config Release
[  1%] Building CXX object CMakeFiles/DlibDotNet.Native.dir/dlib/array/array.cpp.o
In file included from /Users/thomas/Downloads/DlibDotNet-master/src/DlibDotNet.Native/dlib/array/array.cpp:1:
In file included from /Users/thomas/Downloads/DlibDotNet-master/src/DlibDotNet.Native/dlib/array/array.h:5:
In file included from /usr/local/include/dlib/array.h:6:
In file included from /usr/local/include/dlib/array/array_kernel.h:7:
/usr/local/include/dlib/array/../interfaces/enumerable.h:107:17: error: unknown type name 'size_t'
        virtual size_t size (
                ^
In file included from /Users/thomas/Downloads/DlibDotNet-master/src/DlibDotNet.Native/dlib/array/array.cpp:1:
/Users/thomas/Downloads/DlibDotNet-master/src/DlibDotNet.Native/dlib/array/array.h:190:5: warning: cannot delete expression with
      pointer-to-'void' type 'void *' [-Wdelete-incomplete]
    delete obj;
    ^      ~~~
1 warning and 1 error generated.
make[2]: *** [CMakeFiles/DlibDotNet.Native.dir/dlib/array/array.cpp.o] Error 1
make[1]: *** [CMakeFiles/DlibDotNet.Native.dir/all] Error 2
make: *** [all] Error 2

**Comment by takuya-takeuchi** [comment]
I confirmed this issue for building with dlib 19.10.
19.10 looks like to contain breaking api.
For now, please use 19.9 if you can.

**Comment by takuya-takeuchi** [comment]
However size_t is not special type.
Why does it recognize in not windows env?

**Comment by takuya-takeuchi** [comment]
I fixed and checked whether build is no problem for 19.13 on Windows, Linux and MacOS. Please get latest develop branch revision.
And cmake process have been simplify, so please check [Wiki](https://github.com/takuya-takeuchi/DlibDotNet/wiki).
