### ISSUE TITLE
Dlib.LoadImage Or Dlib.SaveJpeg  params  Path can not be chinese?

### ISSUE THREAD

**Issue by k3cloudqxy** [takuya-takeuchi/DlibDotNet#165]
# Summary of your issue
Dlib.LoadImage Or Dlib.SaveJpeg  params  Path can not be chinese?
# Environment
win10   .net 4.6.1

# What did you do when you faced the problem?
Dlib.LoadImage  path containes chinese, these is an exception, I tested if  the path doese not contains chinese, it works ok
## Example code:

           string path = "E:\\HPan\\TestPic\\111 - 副本\\IMG_0003.JPG";
            Array2D<RgbPixel> imgSrc = Dlib.LoadImage<RgbPixel>(path);
paste your core code
```
## Output:
External component exception occurs.
![TIM截图20191212161146](https://user-images.githubusercontent.com/11499014/70694364-64fe2380-1cfa-11ea-82fd-e3ef5f99b12f.png)

## What did you intend to be?

**Comment by takuya-takeuchi** [comment]
Please set encoding you want to use to Dlib.Enciding property.

**Comment by k3cloudqxy** [comment]
it works               thank you very much
