### ISSUE TITLE
How to extract all the head and shoulders instad of only the face from image?

### ISSUE THREAD

**Issue by Jenami67** [takuya-takeuchi/DlibDotNet#166]
# Summary of your issue
I'm trying to extract a 3*4 image from the scan of passport but when i use ```Dlib.ExtractImage4Points``` it just extract the face. What should I do to extract all the picture?
![Inkedinput (12) - Copy_LI](https://user-images.githubusercontent.com/48004796/71519838-615bc680-28ce-11ea-8a2b-d6137c981134.jpg)

# Environment
VS 2019, Windows 10 64bit

# What did you do when you faced the problem?

I tried to make the rectangle in ```Dlib.ExtractImage4Points``` method (array of dPoint) vaster but the image sizes are not equal and make the output unaccurate. The code I tried is below:

## Example code:

```
using (var fd = Dlib.GetFrontalFaceDetector())
            {
                for (int i = 1; i <= 56; i++)
                {

                    var img = Dlib.LoadImage<RgbPixel>(string.Format("TestImages/input ({0}).jpeg", i));

                    // find all faces in the image
                    var faces = fd.Operator(img);

                    foreach (var face in faces)
                    {
                        // draw a rectangle for each face
                        Dlib.DrawRectangle(img, face, color: new RgbPixel(0, 255, 255), thickness: 4);

                        DRectangle dRectangle = new DRectangle(face.Left, face.Top, face.Right, face.Bottom);
                        dRectangle.Top = dRectangle.Top - 50;
                        dRectangle.Bottom = dRectangle.Bottom + 80;
                        dRectangle.Left = dRectangle.Left - 20;
                        dRectangle.Right = dRectangle.Right + 40;

                        DPoint[] dPoint = new DPoint[] {
                        new DPoint(face.TopLeft.X, face.TopLeft.Y),
                        new DPoint(face.TopRight.X, face.TopRight.Y),
                        new DPoint(face.BottomLeft.X, face.BottomLeft.Y),
                        new DPoint(face.BottomRight.X, face.BottomRight.Y),
                    };
                        int width = (int)dRectangle.Width;
                        int height = (int)dRectangle.Height;

                        img = Dlib.ExtractImage4Points(img, dPoint, width, height);
                    }
                    Dlib.SaveJpeg(img, string.Format("TestImages/output ({0}).jpeg", i));
                }
            }
```

## Output:
![output (12)](https://user-images.githubusercontent.com/48004796/71520020-5a818380-28cf-11ea-9fed-a39da615ef3f.jpeg)

## What did you intend to be?
![input (12) - Copy](https://user-images.githubusercontent.com/48004796/71519996-2b6b1200-28cf-11ea-92d5-d4412cffad1f.jpeg)

**Comment by takuya-takeuchi** [comment]
@Jenami67 
Thank you for detail issue report!!

Do you mean how to crop image?
If you so, you should change code from

````csharp
                        DPoint[] dPoint = new DPoint[] {
                        new DPoint(face.TopLeft.X, face.TopLeft.Y),
                        new DPoint(face.TopRight.X, face.TopRight.Y),
                        new DPoint(face.BottomLeft.X, face.BottomLeft.Y),
                        new DPoint(face.BottomRight.X, face.BottomRight.Y),
````

to

````csharp
                    DPoint[] dPoint = new DPoint[]
                    {
                        new DPoint(dRectangle.Left, dRectangle.Top),
                        new DPoint(dRectangle.Right, dRectangle.Top),
                        new DPoint(dRectangle.Left, dRectangle.Bottom),
                        new DPoint(dRectangle.Right, dRectangle.Bottom),
                    };
````

ExtractImage4Points crops the image according to point vector.
You specified the face only area rather than face photo area.

**Comment by Jenami67** [comment]
Thank you for answer but I mean Extracting all the image from passport not just the face. the passport are not scanned very clean and thier sizes are deferent. is there a way to extract all the 3*4 image instead of just the face?

**Comment by takuya-takeuchi** [comment]
Umm.. 

* learning human include face and shoulder
  * dlib face detection model file focus on only face
    * But I think it is difficult. Because learned model should not recognize white space of above head.
* If you can scan passport by optical scanner, you can crop fixed point and size calculated by image resoltion (dpi)
  * Is should be easy. Because, in law enforcement, fingerprint card is fixed format and AFIS system can detect fingerprint area by using template. You can use same approach.
* learning passport photo area by shape_predictor
  * Your passport has distinctive background image. It looks like to has edge between photo and background. This edge may be able to be learned by deep learning. So you can let model learn adge points.
    * https://github.com/takuya-takeuchi/DlibDotNet/blob/master/examples/TrainShapePredictor/Program.cs
  * Or learning whole of passport
    * It has many feature. So learning location of photo area, country stamp and some demographics.
*  learning passport photo by object detection
   * It could be not bad. But general object detection returns bounding box which is not considered about rotation. So you must check rotation angle and correct box.

**Comment by Jenami67** [comment]
Thanks a lot my bro! I will work on it and tell you the result.
Thanks again.
