### ISSUE TITLE
.Net Core 2.2 error DlibDotNetNative.dll not found

### ISSUE THREAD

**Issue by rossnoe** [takuya-takeuchi/DlibDotNet#168]
# Summary of your issue
I am not able to build my .Net Core 2.2 console application because I get an error that says "Could not copy the file "...\.nuget\packages\dlibdotnet\19.18.0.20191202\runtimes\win-AnyCPU\native\DlibDotNetNative.dll" because it was not found."

# Environment
I am using Windows 10, Visual Studio 2017

# What did you do when you faced the problem?
I am trying the code found on this link https://medium.com/machinelearningadvantage/detect-faces-with-c-and-dlib-in-only-40-lines-of-code-f0bb1b929133

## Example code:

Here is my code for my console application:

        // file paths
        private const string inputFilePath = "./input.jpg";

        static void Main(string[] args)
        {
            Console.WriteLine("Face detection / testing");
            // set up Dlib facedetector
            using (var fd = Dlib.GetFrontalFaceDetector())
            {
                // load input image
                var img = Dlib.LoadImage<RgbPixel>(inputFilePath);

                // find all faces in the image
                var faces = fd.Operator(img);
                foreach (var face in faces)
                {
                    // draw a rectangle for each face
                    Dlib.DrawRectangle(img, face, color: new RgbPixel(0, 255, 255), thickness: 4);
                }

                // export the modified image
                Dlib.SaveJpeg(img, "output.jpg");
            }

        }

## What did you intend to be?
Please help!!!

**Comment by takuya-takeuchi** [comment]
@rossnoe 
DlibDotNet does not support AnyCPU.
So please specify x64 for build configuration.

**Comment by rossnoe** [comment]
I did that and still have the same issue. I have the platform target set to x64 and still get the error.

**Comment by takuya-takeuchi** [comment]
Could you upload minimum sample program include sln file to reproduce issue?

**Comment by rossnoe** [comment]
Thank you for your fast response. Basically, I am following this tutorial https://medium.com/machinelearningadvantage/detect-faces-with-c-and-dlib-in-only-40-lines-of-code-f0bb1b929133 and the code that I produced is as below:

    // file paths
    private const string inputFilePath = "./input.jpg";

    static void Main(string[] args)
    {
        Console.WriteLine("Face detection / testing");
        // set up Dlib facedetector
        using (var fd = Dlib.GetFrontalFaceDetector())
        {
            // load input image
            var img = Dlib.LoadImage<RgbPixel>(inputFilePath);

            // find all faces in the image
            var faces = fd.Operator(img);
            foreach (var face in faces)
            {
                // draw a rectangle for each face
                Dlib.DrawRectangle(img, face, color: new RgbPixel(0, 255, 255), thickness: 4);
            }

            // export the modified image
            Dlib.SaveJpeg(img, "output.jpg");
        }

    }

Does that help?

**Comment by rossnoe** [comment]
Also, here is my build setting:

![error](https://user-images.githubusercontent.com/573343/71538046-e3f67d00-28f2-11ea-86d4-dd03f8c5ba8c.jpg)

**Comment by takuya-takeuchi** [comment]
No. You must specify x64 configuration to solution rather than project.

![image](https://user-images.githubusercontent.com/6241854/71538198-666e5380-296a-11ea-9064-4bf921044e90.png)

**Comment by rossnoe** [comment]
Success!!! You were right, that was the issue. I have it working now with my console application. Thanks very much for your help.

**Comment by multinerd** [comment]
Workaround for anyone that does NOT want to change their configs to `x64`:

1. Navigate to `C:\Users\{YOUR_USERNAME}\.nuget\packages\dlibdotnet\19.21.x.xxxxxxxxxxx\runtimes`
2. Make a copy of `win-x64` or `win-x32` (depending on your requirements)
3. Rename that copied folder to `win-AnyCPU`
