### ISSUE TITLE
Memory Leak using ExtractImageChips<T>(Array2DBase, IEnumerable<ChipDetails>)

### ISSUE THREAD

**Issue by akade** [takuya-takeuchi/DlibDotNet#17]
ExtractImageChips<T>(Array2DBase, IEnumerable<ChipDetails>) leaks unmanaged memory. I use it in a realtime application every frame and end up with huge amounts of used memory that I verified to be unmanaged.

Looking at the code, I can see that Array<> does not clean up the elements (it just calls delete on the pointer). As Array<Array2D<T>> has objects as content, I suspect this is where the memory gets leaked.

Any suggestions on how I can fix this?

**Comment by takuya-takeuchi** [comment]
That's right.
For now, array class will not be released.

````C++
DLLEXPORT void array_delete(void* obj)
{
    // dlib::array is template type.
    // Ex. dlib::array<dlib::matrix<float, 31, 1>> does NOT equal to dlib::array<dlib::matrix<float>>
    // Template argument is decided in compile time rather than runtime.
    // So we can not specify template argument as variable.
    // In other words, we have to call delete for void* because we do not known exact type.
    // Unfortunately, dlib::array implement destructor.
    // What should we do?
    delete obj;
}
````
However, I probably should check type and delete it for except for template types looks like dlib::array<dlib::matrix<float, 31, 1>>.

**Comment by akade** [comment]
I fixed it for me by modifying the wrapper:

`  protected override void DisposeUnmanaged()
        {
            base.DisposeUnmanaged();


            switch (_ItemType)
            {
                case ItemTypes.PixelType:
                    {
                        Dlib.Native.array_delete(this.NativePtr);
                    }
                    break;
                case ItemTypes.Array2D:
                    {
                        var type = this._ArrayElementType.ToNativeArray2DType();
                        Dlib.Native.array_array2d_delete(type, this.NativePtr);
                    }
                    break;
                case ItemTypes.Matrix:
                    {
                        throw new NotSupportedException("Memory leak");
                    }
                    break;
                default:
                    throw new ArgumentOutOfRangeException();
            }
        }`

and adding the following native method:

`DLLEXPORT void array_array2d_delete(array2d_type type, void* obj)
{
	switch (type)
	{
	case array2d_type::UInt8:
		delete ((dlib::array<array2d<uint8_t>>*)obj);
		break;
	case array2d_type::UInt16:
		delete ((dlib::array<array2d<uint16_t>>*)obj);
		break;
	case array2d_type::Int16:
		delete ((dlib::array<array2d<int16_t>>*)obj);
		break;
	case array2d_type::Int32:
		delete ((dlib::array<array2d<int32_t>>*)obj);
		break;
	case array2d_type::Float:
		delete ((dlib::array<array2d<float>>*)obj);
		break;
	case array2d_type::Double:
		delete ((dlib::array<array2d<double>>*)obj);
		break;
	case array2d_type::RgbPixel:
		delete ((dlib::array<array2d<rgb_pixel>>*)obj);
		break;
	case array2d_type::HsiPixel:
		delete ((dlib::array<array2d<hsi_pixel>>*)obj);
		break;
	case array2d_type::RgbAlphaPixel:
		delete ((dlib::array<array2d<rgb_alpha_pixel>>*)obj);
		break;
	}
}`
I also did that for the matrix class, where you already had this code but as comment because of some special fixed size matrix templates. I had no issueswith it and I think at least the above array code is save.
And it fixed my memory leak. In case you want to integrate that.

**Comment by takuya-takeuchi** [comment]
Thank you so much!!
Please give me moment to check your codes.
Unfortunately,  I am busy here recently, so I can not do any coding :(

**Comment by takuya-takeuchi** [comment]
OK, It should be ok.
Could you send PR if you can?
After merge, I add code to release array<Matrix>.
