### ISSUE TITLE
Unable to load 'DlibDotNetNative' when use FaceRecognitionDotNet.CUDA101

### ISSUE THREAD

**Issue by sminnims** [takuya-takeuchi/DlibDotNet#170]
# Summary of your issue
- Install FaceRecognitionDotNet.CUDA101 / DlibDotNet.CUDA101
- Error occured when called FaceRecognition.Create(_modelPath)
# Environment
- Windows 10
- Visual Studio 2017
- NVIDIA Cuda 10.1
- FaceRecognitionDotNet.CUDA101 "1.2.3.13"
- DlibDotNet.CUDA101"19.17.0.20190623"

# What did you do when you faced the problem?
- Forced remove DlibDotNet.CUDA101 and reinstall

## Example code:
        private void Init()
        {
            FRCtrl = FaceRecognition.Create(Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "models"));
        }

## Output:

![image](https://user-images.githubusercontent.com/20694804/72121760-4e9dc300-339f-11ea-83b7-02902b0552ad.png)

## What did you intend to be?
face detect with cuda

Hi. 

I tried to do face detection using Cuda with - FaceRecognitionDotNet.CUDA101.
However, an error occurred when executing.

System.DllNotFoundException
  HResult=0x80131524
  Message=DLL 'DlibDotNetNative' cannot be loaded. 지정된 모듈을 찾을 수 없습니다. (예외가 발생한 HRESULT: 0x8007007E)
  Source=DlibDotNet
  StackTrace:
   at DlibDotNet.NativeMethods.get_frontal_face_detector()
   at FaceRecognitionDotNet.FaceRecognition..ctor(String directory)
   at FaceRecognitionDotNet.FaceRecognition.Create(String directory)
   at ImageSource.MainWindow.Init() in C:\Git\FRDotNetTest\ImageSource\ImageSource\MainWindow.xaml.cs:line 49

There isn't exsist DlibDotNetNative.dll file in output folder.

Do i miss some step for using Cuda Library?

I'm install cuda 10.1 and set path.
>set CUDA
CUDA_PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1
CUDA_PATH_V10_1=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1

Output Folder Files
![image](https://user-images.githubusercontent.com/20694804/72122500-7130db80-33a1-11ea-8b27-f23f371bc654.png)

**Comment by takuya-takeuchi** [comment]
Could you check whether there are cunning libs?

**Comment by sminnims** [comment]
> Could you check whether there are cudnn libs?
cudnn libs in cuda folder. 
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\lib\x64
![image](https://user-images.githubusercontent.com/20694804/72228341-1ee1fb80-35e9-11ea-8776-9aa6742598e6.png)

do i need to copy cudnn libs to output folder?

**Comment by takuya-takeuchi** [comment]
cudnn files (lib, bin ,include) should be in C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\vXXX.
so Basically, you need not to copy them to app dir.

You may find out by using dependency walker.

> Output Folder Files
DlidDotNet.Native.Dnn is missing. Missing could be what apps crash.

**Comment by sminnims** [comment]
I solved my problem.
I copied dlibdotnetnativednn.dll and dlibdotnetnative.dll from dlibdotnet folder to my working folder and It Work! 
Thank you for your advise! 
and This issue was related to FaceRecognitionDotNet and I reported wrong repository.
Sorry.

**Comment by takuya-takeuchi** [comment]
Good.
Don’t hesitate to report any issue.
Thank you for your contribution!!
