### ISSUE TITLE
Using DLibDotNet looks for DlibDotNetNative - can't run

### ISSUE THREAD

**Issue by elhaix** [takuya-takeuchi/DlibDotNet#171]
# Summary of your issue
Windows 10

In a basic Windows Forms solution, I added DLibDotNet and DLibDotNet.Extensions.  Things were working fine last week until I renamed some folders.  Going at it from the beginning again, I created a new solution, added the projects and ran the code.

In DLibDotNet.Dlib.cs, when   var ret = NativeMethods.get_frontal_face_detector(); is attempted, the following exception occurs:

{"The type initializer for 'DlibDotNet.NativeMethods' threw an exception."}
InnerException = {"Unable to load DLL 'DlibDotNetNativeDnn': The specified module could not be found. (Exception from HRESULT: 0x8007007E)"}

It seems to be wanting the native C++ code to be built.

Stuck on this one, as it was all working in the past.

I also tried simply adding the DlibDotNet Nuget Package, then end up getting a similar error, "...native\DlibDotNetNative.Dll"  .. because it was not found.

**Comment by takuya-takeuchi** [comment]
It looks like failing to copy library.
Could you check new soluution configuration?
https://github.com/takuya-takeuchi/DlibDotNet/issues/168#issuecomment-569379523

**Comment by elhaix** [comment]
Hi Takuya,

Unfortunately that did not work.  Here is my config and the list of initial errors.

![image](https://user-images.githubusercontent.com/296048/72460368-a4f17400-379a-11ea-9813-4d468004672c.png)

**Comment by takuya-takeuchi** [comment]
ToArray2d method is in dlibdotnet.extension rather than Dlibdotnet.
You must build and copy to directory manually.

**Comment by takuya-takeuchi** [comment]
No Response
