### ISSUE TITLE
DlibDotNet.NativeMethods threw exception

### ISSUE THREAD

**Issue by kernello** [takuya-takeuchi/DlibDotNet#172]
# Summary of your issue
Getting exception from DlibDotNet.NativeMethods when trying to initialize Shape_predictor.
# Environment
Windows 2012 server IIS, x64 bit
# What did you do when you faced the problem?
My dev environment working fine but getting exception in the prod environment.

## Example code:

```
paste your core code
```

## Output:

```
The type initializer for 'DlibDotNet.NativeMethods' threw an exception., error trace:    at DlibDotNet.NativeMethods.deserialize_shape_predictor(Byte[] filName, Int32 fileNameLength, IntPtr& predictor, IntPtr& errorMessage)
   at DlibDotNet.ShapePredictor.Deserialize(String path)
   at OCRImageManager.RPOCRImage..ctor()
   at Services.AppointmentRepository.GetAppointment(List`1 request, String fileSaveLocation)
   at Controllers.AppointmentController.<Appointment>d__2.MoveNext()
```

## What did you intend to be?
I have checked in both machine and both machine has visual redistributeble x64 2008, 2013, 2015

Please help me.

**Comment by takuya-takeuchi** [comment]
@kernello 
I can not suggest any advice without detail error message.
Could you show the InnerException of The type initializer for "'DlibDotNet.NativeMethods' threw an exception"?

But I guess

* DlibDotNetNative or DlibDotNetNativeDnn are missing in application directory.
* Visual Studio 2017 C++ is not installed
  * but it could not be matter because VC++ 2015/2017/2019 runtime is shared runtime.

**Comment by kernello** [comment]
Hello @takuya-takeuchi 

Thanks for your reply. Yeah, DlibDotNetNative and DlibDotNetNativeDnn both file has existed in the project directory. Same release files working fine in my other machine. I have compared the working machine which doesn't work machine. Botha machine has the same redistributable but getting the exception.

**Comment by kernello** [comment]
Should I try to install VS  Redistributable 2017 x64?.

**Comment by takuya-takeuchi** [comment]
Yes. Could you have a try if modify system setting is no matter to install it?

**Comment by kernello** [comment]
@takuya-takeuchi ,

I just use Dlib v19.17.0.20190813 and working fine with Xenon CPU and Intel CPU as well.

**Comment by takuya-takeuchi** [comment]
@kernello 
FYI
Latest dlibdotnet does not support legacy cpu.
https://github.com/takuya-takeuchi/DlibDotNet/issues/153

v19.17.0.20190813  is last version which supports non avx cpu.

**Comment by takuya-takeuchi** [comment]
No Response

**Comment by kernello** [comment]
@takuya-takeuchi,

Thanks for your help. v19.17.0.20190813 works for us.
