### ISSUE TITLE
Use Dlibdotnet to recognize face in bitmap images

### ISSUE THREAD

**Issue by lindomar-marques55** [takuya-takeuchi/DlibDotNet#173]
Use Dlibdotnet to recognize face in bitmap images.
I am trying to use dlibdotnet to recognize face in bitmap image after the accord does motion recognition. I can make dlibdotnet recognize face in an image obtained from the directory (loadimage) but I cannot make it use a bitmap image generated by the accord after motion recognition. and also I can't pass the result after working with dlibdotnet for bitmap to display on the screen or to perform other activities with the same image. if anyone has any tips please thank you. I am using .netframework 4.8 Wpf C #.

**Comment by takuya-takeuchi** [comment]
Accord is accord.Net? I have no idea about this bitmap format.
Do you want to know how to convert Accord.Net format to DlibDotNet

**Comment by lindomar-marques55** [comment]
I'm sorry, but in the example you gave `CvInvoke.Imread` asks for a string, but the bitmap I want to use is in memory and was not recorded, it is passed directly from another procedure.
and for me there was an error in the
`ImreadModes.AnyColor`
 part of this error
`Error Argument 2: Cannot convert from "OpenCvSharp.ImreadModes" to "Emgu.CV.CvEnum.LoadImageType`.

I tried using the bitmap like this 
`private void Detectorderosto_Rostomudoua(object sender, EventArgs e)
        {
            Bitmap bmp = (Bitmap)sender;
 Bitmap frame = new Bitmap(bmp);
                     using (var fd = Dlib.GetFrontalFaceDetector())
            {
                using (var sp =  ShapePredictor.Deserialize("shape_predictor_68_face_landmarks.dat"))
                {
                    Array2D<RgbPixel> img = frame.ToArray2D<RgbPixel>();
                    var faces = fd.Operator(img);
                    MessageBox.Show("fafadsf");
                }
            }
      }
        `

 but it resulted in the following error when running (`System.NotSupportedException: 'Not support converting from Format32bppArgb to RgbPixel`)

**Comment by lindomar-marques55** [comment]
I tried it this way

```
 Bitmap bmp = (Bitmap)sender;

            Bitmap frame = new Bitmap(bmp);
            Image<Bgr, Byte> imageCV = new Image<Bgr, byte>(frame); //Image Class from Emgu.CV
            Emgu.CV.Mat mat = imageCV.Mat;
            var array = new byte[mat.Width * mat.Height * mat.ElementSize];
            mat.CopyTo(array);
      
            using (Array2D<BgrPixel> image = Dlib.LoadImageData<BgrPixel>(array, (uint)mat.Height, (uint)mat.Width, (uint)(mat.Width * mat.ElementSize)))
            {
                MessageBox.Show("fafadsf");
            }
```

but when running the following error in `System.NotSupportedException: 'Specified method is not supported.'`

**Comment by takuya-takeuchi** [comment]
@lindomar-marques55 

````
using System;
using System.Drawing;
using System.Windows.Forms;
using DlibDotNet;
using Emgu.CV;
using Emgu.CV.CvEnum;
using Emgu.CV.Structure;

namespace MatToArray2D
{

    internal class Program
    {

        private static void Main()
        {
            using (var sender = Bitmap.FromFile("Lenna.png"))
            {
                Bitmap bmp = (Bitmap)sender;
                Bitmap frame = new Bitmap(bmp);
                Image<Bgr, Byte> imageCV = new Image<Bgr, byte>(frame); //Image Class from Emgu.CV
                Emgu.CV.Mat mat = imageCV.Mat;
                var array = new byte[mat.Width * mat.Height * mat.ElementSize];
                mat.CopyTo(array);

                using (Array2D<BgrPixel> image = Dlib.LoadImageData<BgrPixel>(array, (uint)mat.Height, (uint)mat.Width, (uint)(mat.Width * mat.ElementSize)))
                {
                    MessageBox.Show("fafadsf");
                }
            }
        }

    }

}
````

It works fine.
I think DlibDotNet you use looks like to be a bit old.
Could you check version and use latest version?

**Comment by lindomar-marques55** [comment]
I downloaded the latest version of the dnlib dotnet from github and compiled it. however when running these new dlls it generates this error. 
`System.TypeInitializationException: 'The type initializer for 'DlibDotNet.NativeMethods' threw an exception.'`

```
Excessao interna
DllNotFoundException: Unable to load DLL 'DlibDotNetNativeDnn': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
```

please what am i missing? i use windows 7 .net 4.8 and c # with WPF.

**Comment by takuya-takeuchi** [comment]
Please check the following points

### using DlibDotNet CUDA

* Install proper CUDA
* Install cuDNN to CUDA directory

### using DlibDotNet MKL

* Copy mkl library to app directory

### Common

* Install C++ 2017 runtime
* There is DlibDotNet.dll, DlibDotNetNative.dll and DlibDotNetNativeDnn.dll in app directory

**Comment by lindomar-marques55** [comment]
I'm more lost than blind in shooting. I installed dlibdotnet, dlibdotnet.cuda101 and dlibdotnet.mkl. but still giving error.
`System.DllNotFoundException: 'Unable to load DLL 'DlibDotNetNative': Exception from HRESULT: 0xC000001D'`
 I'm almost giving up.

**Comment by takuya-takeuchi** [comment]
You may face same past error.
https://github.com/takuya-takeuchi/DlibDotNet/issues/169

**Comment by lindomar-marques55** [comment]
my brother, I managed to do face recognition in bitmap image as I wanted it worked with version v19.17 of dlibdotnet the version v19.18 continued giving the error mentioned above. thanks
