### ISSUE TITLE
DlibDotNet.Rectangle to bitmap 

### ISSUE THREAD

**Issue by lindomar-marques55** [takuya-takeuchi/DlibDotNet#175]
Hello, I was able to recognize the face using Dlib.GetFrontalFaceDetector () 
but I would like to be able to generate a new bitmap with only the face recognized, that is,
 I need to convert DlibDotNet.Rectangle into a bitmap. any idea where I should go?
 thanks for listening.

**Comment by takuya-takeuchi** [comment]
You mean you want to crop recognizes area?
If so, you can check this issue.
https://github.com/takuya-takeuchi/DlibDotNet/issues/166

**Comment by takuya-takeuchi** [comment]
No Response
