### ISSUE TITLE
Wrong directory in wiki

### ISSUE THREAD

**Issue by SamuelvVelzen** [takuya-takeuchi/DlibDotNet#178]
Hi Takuya,

Following the wiki on how to setup the mac version I came across is what I think a mistake in the instruction manual. 
In the manual it says "How to build DlibDotNet.Native.Dnn" however the steps go to the "DlibDotNet.Native" folder. 
Like this: 
**Open DlibDotNet/src/DlibDotNet.Native in console.**
I think it has to be this:
**Open DlibDotNet/src/DlibDotNet.Native.Dnn in console.**

https://github.com/takuya-takeuchi/DlibDotNet/wiki/Tutorial-for-MacOS

Please correct me if I am wrong but it looks weird 2 sections doing the same thing

**Comment by takuya-takeuchi** [comment]
@SamuelvVelzen 
Thank you for your contribution.
I fixed it. Thank you!!
