### ISSUE TITLE
can i load image from URL not path ? 

### ISSUE THREAD

**Issue by mohamedmmagdi** [takuya-takeuchi/DlibDotNet#179]
original method: 
   var img = Dlib.LoadImage<RgbPixel>(filePath))

what i need to do is:
     using (var img = Dlib.LoadImage<RgbPixel>(fileURL))

**Comment by takuya-takeuchi** [comment]
can not.
dlib does not support to load from web.

**Comment by takuya-takeuchi** [comment]
No Response
