### ISSUE TITLE
Using DlibDotNet.Extensions with .NET Standard 2.0

### ISSUE THREAD

**Issue by nor0x** [takuya-takeuchi/DlibDotNet#18]
I try using DlibDotNet.Extensions under .NET Standard 2.0 for BitmapExtensions, however the project doesn't build because WriteableBitmap is not available when running .NET Standard 2.0. Does anyone  know any workarounds for this issue?
Thanks for DlibDotNet, it's a great piece of software  👍

**Comment by takuya-takeuchi** [comment]
Oh, I did not consider DlibDotNet.Extensions for using .NET Starndard 2.0.
I thought it is used for WPF and WinForms to improvement compatible.

.NET Standard support System.Drawing.Bitmap? If so, I may be able to isolate WriteableBitmapConverter to another assembly.
For example, DlibDotNet.WinForms.Extensions and DlibDotNet.WPF.Extensions. Ops, terrible name!!

FYI: https://stackoverflow.com/questions/50392705/writeablebitmap-in-net-standard-2-0

**Comment by valerysntx** [comment]
@nor0x, not exactly that case, but I've used [WindowsBase](https://www.nuget.org/packages/WindowsBase/ ) to fix many of missed namespaces on netstandart2.0

**Comment by valerysntx** [comment]
@nor0x i was able to build using the following packages:
`Microsoft.Xaml v4.0.0.1, System.Drawing.Common v4.5.0, WindowsBase v4.6.1055`
``` <ItemGroup>
    <Reference Include="PresentationCore">
      <HintPath>..\packages\Microsoft.Xaml.4.0.0.1\lib\PresentationCore.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="PresentationFramework">
      <HintPath>..\packages\Microsoft.Xaml.4.0.0.1\lib\PresentationFramework.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="System" />
    <Reference Include="System.Core" />
    <Reference Include="System.Design">
      <HintPath>..\packages\Microsoft.Xaml.4.0.0.1\lib\System.Design.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="System.Drawing" />
    <Reference Include="System.Drawing.Common, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51, processorArchitecture=MSIL">
      <HintPath>..\packages\System.Drawing.Common.4.5.0\lib\net461\System.Drawing.Common.dll</HintPath>
    </Reference>
    <Reference Include="System.Xaml">
      <HintPath>..\packages\Microsoft.Xaml.4.0.0.1\lib\System.Xaml.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="UIAutomationProvider">
      <HintPath>..\packages\Microsoft.Xaml.4.0.0.1\lib\UIAutomationProvider.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="WindowsBase">
      <HintPath>..\packages\Microsoft.Xaml.4.0.0.1\lib\WindowsBase.dll</HintPath>
      <Private>True</Private>
    </Reference>

**Comment by zhuxb711** [comment]
https://1drv.ms/u/s!Agii_xhBMge2nJQGU17IaRH1qK1xww

DlibExtention_Net_Core Version

**Comment by valerysntx** [comment]
Here is `DlibDotNet.Extensions` migration to `netstandard2.0`
 - https://github.com/valerysntx/DlibDotNet/commit/0ddf43bd7fff622d6db0823d9b349f4f0dc5b80f
 - https://github.com/valerysntx/DlibDotNet/commit/f73c21f47b8b8251ce11d0ec6620d8331bde3c4d
 - https://github.com/valerysntx/DlibDotNet/commit/995c2d6025fa0bf898a3db5ce5dda3e6277885a8
@takuya-takeuchi: ping me, if considering such of migration, i will PR :)

**Comment by takuya-takeuchi** [comment]
close due to 2df5ba5e85a8543b098319f930839c1b9676b920
