### ISSUE TITLE
RotateImage looks like not working correctly

### ISSUE THREAD

**Issue by takuya-takeuchi** [takuya-takeuchi/DlibDotNet#180]
Hi @takuya-takeuchi  I used "1.57" as suggested to rotate an image that was 800 Width by 600 Height and the image didn't rotate 90 degrees. So then I created a for loop and found that the value of 11 worked. 

 DlibDotNet.Dlib.RotateImage(array2D, array2D_Output1,1.57);
 var win2 = new ImageWindow(array2D_Output1);

_Originally posted by @atabora1 in https://github.com/takuya-takeuchi/FaceRecognitionDotNet/issues/36#issuecomment-593773713_

**Comment by takuya-takeuchi** [comment]
@atabora1
I tried sample code but it works fine.

````
using System;
using DlibDotNet;

namespace _180
{
    class Program
    {
        static void Main(string[] args)
        {
            foreach(var radian in new[] { 1.57d / 3, 1.57d * 2 / 3, 1.57d, 3.14 })
                using(var src = Dlib.LoadImage<RgbPixel>("Lenna.bmp"))
                using(var dst = new Array2D<RgbPixel>())
                {
                    Dlib.RotateImage(src, dst, radian);
                    Dlib.SavePng(dst, $"{radian}.png");
                }
        }
    }
}
````

![0 5233333333333333](https://user-images.githubusercontent.com/6241854/75883405-48d7d180-5e66-11ea-8ad1-cca27c7d592a.png)

![1 0466666666666666](https://user-images.githubusercontent.com/6241854/75883411-4aa19500-5e66-11ea-81ac-d8adbee099f1.png)

![1 57](https://user-images.githubusercontent.com/6241854/75883409-4a08fe80-5e66-11ea-9a25-164b139f8dd6.png)

![3 14](https://user-images.githubusercontent.com/6241854/75883415-4aa19500-5e66-11ea-92c0-811abed098ae.png)

**Comment by atabora1** [comment]
Thanks, the images help to identify what I was doing wrong. The issue was that 1.57 was rotating the image 90 degrees counter-clockwise. I was trying to rotate it 90 degrees clockwise so I would need this value instead. 4.71204188. thanks,
