### ISSUE TITLE
The type initializer for 'DlibDotNet.NativeMethods' threw an exception

### ISSUE THREAD

**Issue by betty-crokker** [takuya-takeuchi/DlibDotNet#183]
# Summary of your issue
Just trying to get some preliminary face recognition going

# Environment
Visual Studio 2019 Community
Windows 10
Installed DlibDotNet.CUDA101 via NuGet
Installed NVIDIA CUDA 10.2
(I'm assuming CUDA 10.2 is a superset of 10.1 so using CUDA 10.2 with DlibDotNet.CUDA101 is OK)

Project was working using DlibDotNet (no CUDA) but slow so I wanted to switch to the CUDA version for speed.

# What did you do when you faced the problem?
Caught exception to see details, ran DependencyWalker

Dependency Walker actually hangs when I tell it to look at DlibDotNetNativeDnn.dll.  I tried both Version 2.2.6000 for Win32 (x86) and Version 2.2.6000 for Win64 (x64).  In both cases the spinner goes forever, using 100% of one CPU core

## Example code:
            try
            {
                FaceDetector = Dlib.GetFrontalFaceDetector();
            }
            catch(Exception e)
            {
                Debug.WriteLine("Exception thrown during GetFrontalFaceDetector(): " + e.Message);
                Debug.WriteLine(e.StackTrace);
                if (e.InnerException != null)
                {
                    Debug.WriteLine("Inner Exception : " + e.InnerException.Message);
                    Debug.WriteLine(e.InnerException.StackTrace);
                }
                throw;
            }

## Output:
Exception thrown: 'System.TypeInitializationException' in DlibDotNet.dll
Exception thrown during GetFrontalFaceDetector(): The type initializer for 'DlibDotNet.NativeMethods' threw an exception.
'ImageTagger.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.3\System.Diagnostics.StackTrace.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'ImageTagger.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.3\System.Reflection.Metadata.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'ImageTagger.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.3\System.Collections.Immutable.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
   at DlibDotNet.NativeMethods.get_frontal_face_detector()
   at DlibDotNet.Dlib.GetFrontalFaceDetector()
   at ImageTagger.Analyzer..ctor() in D:\projects\ImageTagger\ImageTagger\Analyzer.cs:line 18
Inner Exception : Unable to load DLL 'DlibDotNetNativeDnn' or one of its dependencies: The specified module could not be found. (0x8007007E)
   at DlibDotNet.NativeMethods.LossMetric_anet_type_create()
   at DlibDotNet.NativeMethods..cctor()
Exception thrown: 'System.TypeInitializationException' in ImageTagger.dll
An exception of type 'System.TypeInitializationException' occurred in ImageTagger.dll but was not handled in user code
The type initializer for 'DlibDotNet.NativeMethods' threw an exception.

**Comment by Megadino** [comment]
@betty-crokker if Dependancy Walkers hangs, you may want to try track requests to a file system from your application with Process Monitor - https://docs.microsoft.com/en-us/sysinternals/downloads/procmon and see which file requests for which DLL fail. Process Monitor helped me a few times when DW could not.  

Also, you haven't mentioned what platform your project targets to - x86 or x64, there might be a discrepancy too. Please be aware that DlibDotNet does not support AnyCPU build configuration.

**Comment by betty-crokker** [comment]
I am targeting x64.  Process Monitor has 5,181 events for my application (running inside the Visual Studio debugger), is there a particular Operation I can filter on to see which file request failed?

**Comment by betty-crokker** [comment]
The problem was that I had not installed cuDNN.  Now that I've got that running, it turns out my hardware only supports CUDA 9.1 and the earliest version of DlibDotNet is for CUDA 9.2 so I guess it's time to upgrade hardware.
