### ISSUE TITLE
netcore have "System.Drawing.Bitmap" now ,can you consider add BitmapExtensions to nuget package?

### ISSUE THREAD

**Issue by codeoflin** [takuya-takeuchi/DlibDotNet#184]
Netcore have "System.Drawing.Bitmap" now ,can you consider add BitmapExtensions to nuget package?
I really need it  :)

**Comment by takuya-takeuchi** [comment]
@codeoflin 
Ok. I will add the following methods

* Matrix<T>.ToBitmap()
* Array2D<T>.ToBitmap()

Is it OK?
Extesion is old and it include WPF component and no cross-platform.

**Comment by takuya-takeuchi** [comment]
# Note

* Consider about .NET framework
  * .NET Framework needs not to depends on System.Drawing.Common package
     * Does it mean nuget package separate binary to for .NET framework and .NET standard?

**Comment by takuya-takeuchi** [comment]
Should I drop supporting WPF component from Extensions?
If so, DlibDotNet can get to be cross-platform.
I think we should increase dependencies of DlibDotNet.

**Comment by takuya-takeuchi** [comment]
.NET 5.0 support System.Windows.Media.Imaging?

**Comment by takuya-takeuchi** [comment]
Start developing on https://github.com/takuya-takeuchi/DlibDotNet/tree/feature/extensions2core

* Dropped WPF support
* Finished to convert to .NET Standard
* Finished to prepare nuget package

**Comment by codeoflin** [comment]
thank you very much. @takuya-takeuchi

**Comment by takuya-takeuchi** [comment]
@codeoflin 
I just uploaed DlibDotNet.Extensions nuget package.
https://www.nuget.org/packages/DlibDotNet.Extensions
(now, nuget indexing package and it may be invisible...)

It could support .NET Framework and .NET core.
It dropped supprot of WPF component but it could help your development.
Have a try.
