### ISSUE TITLE
"Unable to load DLL 'DlibDotnetNative' " exception from a working application

### ISSUE THREAD

**Issue by Nimachakin** [takuya-takeuchi/DlibDotNet#189]
# Summary of your issue
Greetings from Russia!
Dear @takuya-takeuchi , I can not run my app from the job's computer because of exception (from the title).

# Environment

Windows 7 pro SP1 (x64)
.net core SDK 3.1
Visual Studio Code (x64 portable)

DlibDotNet 19.18.0.20200429

# What did you do when you faced the problem?
This dll is placed in bin/x64/Debug folder of the app. So I guessed a dlibdotnet nuget was broken.
First I tried to change the version of DlibDotNet nuget and the version of .net from 3.1 to 2.0. It didn't help me. Then I decided to run the application from my PC at home (with Windows 10 installed) from the same VS Code. And it worked fine! So i think there is a lack of some component on my working PC (with windows 7 pro SP1) I was  searching the internet all the last week and any suggestions don't help me to solve this problem.  I've checked and installed all the Visual C++ Redistributive runtimes. Result is the same: app works on win 10 and doesn't on win 7. 
Some people recommend me to check this DlibDotNetNative DLL via 'DependencyWalker' but i have no clue how does it works.

## Example code:

```
using System;
using DlibDotNet;

namespace TestConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            var detector = Dlib.GetFrontalFaceDetector();
            Console.WriteLine("Hello World!");
        }
    }
}
```

## Output:

```
...>dotnet run
Unhandled exception. System.DllNotFoundException: Unable to load DLL 'DlibDotnetNative' or one if its dependencies: 0xC000001D
    at DlibDotNet.NativeMethods.get_frontal_face_detector()
    at DlibDotNet.Dlib.GetFrontalFaceDetector()
    at DlibConsoleTestApp.Program.Main(String[] args) in ...
```

**Comment by Megadino** [comment]
@Nimachakin  you can try to use Process Monitor tool to see what files your program tries to load and what fails when it initializes DlibDotNet. 

DlibDotNet does not support AnyCPU configuration, make sure you use either x86 or x64 config to build your project.
Latest DlibDotNet requires CPU with AVX instructions set, make sure your work  PC has CPU with AVX(for example Intel Xeon and many AMD CPUs don't have it)

Try to put DlibDotNet files into the root folder of your app where .exe is and into subfolder 'dll', this may help.

**Comment by takuya-takeuchi** [comment]
@Nimachakin 
This issue could be helpful for you.
https://github.com/takuya-takeuchi/DlibDotNet/issues/169
https://github.com/takuya-takeuchi/DlibDotNet/issues/173

**Comment by Nimachakin** [comment]
Hello. 
Well, I tried the things you guys recommend me but still can not solve this problem. This week I noticed that if I delete "visual c++ 2015" from my home PC (windows 10), the application with dlib won't work (Exception like "can not load DlibDotNetNative"). And after I installed it again the app works fine. 
There was not visual c++ 2015 on my working PC (windows 7 pro SP1) because it already have 2015-2019 version which automatically consume or delete the previous version (2015 or 2017) on installing. I deleted this version and installed visual c++ 2015. But again, it didn't work as I hoped. 
Process Monitor tool showed me that my app can't load some dlls like "api-ms-win-crt-runtime-|1-1-0.dll", "api-ms-win-core-file-|1-2-0.dll" etc. 
Google says these dlls are visual c++ components. But even with it my app still crushed with "can not load DlibDotNetNative.dll"
None of my colleagues can't help me. I'm sure there is some little fix which will make it works but still don't get what it really is

**Comment by takuya-takeuchi** [comment]
@Nimachakin 
TBH, I don't want to take care of Windows 7 which is not supported by Microsoft.

But I ask Google about this.
Superuser looks like to be helpful.
https://superuser.com/questions/986496/missing-api-ms-win-crt-runtime-1-1-0-dll

You may work fine after update Universal C Runtime in Windows.

Thanks.

**Comment by Nimachakin** [comment]
@takuya-takeuchi oh thank you! I'll try that.

**Comment by Nimachakin** [comment]
Good morning! 
Nothing helped me to make DlibDotNet 19.18.0.20200429 works fine, but i tried previous version (19.17.0.20190813) and it worked! So i will contrinue to develop my web-api with it. Anyway, thanks to all of you!
