### ISSUE TITLE
Cuda102

### ISSUE THREAD

**Issue by hkhawand** [takuya-takeuchi/DlibDotNet#191]
# Summary of your issue
Hello,
I have Cuda 10.2 installed and wanted to create a solution that depends on FaceRecognitionDotnet as a csproject and not as a dll.

So I compiled successfully DlibdotNet.Native (although the compiled dll file was 200Mb large on debug) and DlibDotNet.NativeDnn using Cmake that enabled the use of Cuda with a test project.

But when referencing the source code (csproject) of DlibDotNet and FaceRecognitionDotnet, my project was not able to use Cuda and processing of image facial encodings was slow.
I did move the above compiled dlls (with Cuda enabled) to my debug folder with no success.

#What I did
I removed the csprojects and used Nuget packages of Cuda101 and it worked :)

#Question
The question is: I need the source code of FaceRecognitionDotnet inside my solution and not as a Nuget Package. What should I do?

# Environment
VS.Net 2019    Win10   Cuda10.2 CuDnn installed

**Comment by takuya-takeuchi** [comment]
@hkhawand 
> So I compiled successfully DlibdotNet.Native (although the compiled dll file was 200Mb large on debug) and DlibDotNet.NativeDnn using Cmake that enabled the use of Cuda with a test project.

How did you confirm whether your build uses cuda binary?
I guess your build does not depends on cuda libs.
Could you check dependencies information of DlibDotNet you build?

**Comment by hkhawand** [comment]
Exactly, thank you for pointing out the dependencies,
I did set the dependencies of DlibdotNet.Native and DlibDotNet.NativeDnn before building them as per Nvidia Cuda installation guide:
[https://docs.nvidia.com/cuda/cuda-installation-guide-microsoft-windows/index.html#build-customizations-for-existing-projects](url)

It did not work when DlibdotNet.Native.dll is built as Debug. But it did work on Release (It took a long time to build)

As for DlibDotNet  and FaceRecognitionDotnet csprojects I changed nothing concerning dependencies.

Thank you for your fast support, I appreciate that.

Do you want to ask me something before closing the issue?

**Comment by takuya-takeuchi** [comment]
@hkhawand 
thank you for your kindly reporting.
Yeah, I have nothing to ask you.
You can close it!!

P.S.
I will release FRDN.CUDA10.2 in the near future.
I guess you need not to build

**Comment by takuya-takeuchi** [comment]
Release done

https://www.nuget.org/packages/DlibDotNet.CUDA102
https://www.nuget.org/packages/FaceRecognitionDotNet.CUDA102/
https://github.com/takuya-takeuchi/FaceRecognitionDotNet/releases/tag/1.3.0.1

**Comment by hkhawand** [comment]
Thanks a lot,
I am glad a new version was released and as Cuda102 nuget package too.
