### ISSUE TITLE
DlibDotNet.MKL - Bundle MKL DLL request

### ISSUE THREAD

**Issue by razier** [takuya-takeuchi/DlibDotNet#192]
Possible to bundle the Intel MKL dll (libiomp5md.dll, mkl_core.dll, mkl_def.dll, mkl_intel_thread.dll) into the nuget package?

Installing the entire Intel MKL (2gb), to copy a few dll does not seem to make sense.

If you are worried on the license, Based on the faq page, we are allow to bundle and redistribute based on the ISSL : 
https://software.intel.com/content/www/us/en/develop/articles/intel-math-kernel-library-license-faq.html

p.s. Sorry for not following the format of issue reporting

**Comment by takuya-takeuchi** [comment]
@razier 
thank you for your good advise!!!
ok, I plan to bundle these dlls package.
But current code base depends on docker to test before package release.
And then, I have to pickup proper libs from docker container.
So it may take times.

Thanks.

**Comment by takuya-takeuchi** [comment]
@razier 
Next DDN.MKL bundle Intel MKL for only Windows.
44ae718d22d3a5324aaef4ddc5d94bb706edb83b

**Comment by takuya-takeuchi** [comment]
[10.20.0.20200725](https://www.nuget.org/packages/DlibDotNet.MKL/19.20.0.20200725) bundle mkl libs for only windows
