### ISSUE TITLE
Support for cuda 11

### ISSUE THREAD

**Issue by MarkWalter94** [takuya-takeuchi/DlibDotNet#198]
It would be great having compile support for newer cuda versions.

**Comment by takuya-takeuchi** [comment]
@MarkWalter94 
I'm very sorry to delay response.
I already work on this issue.
cuddn is RC and dlib faces to some build error.

But in these days, latest dlib looks like to support cudnn8.
https://github.com/davisking/dlib/issues/2100

I'm just checking it.

Thanks a lot.

**Comment by takuya-takeuchi** [comment]
# Current issue

* centos cudnn8 container is missing
  * it is nvidia's matter
* build for cuda 9.2 and 10.0 fails
  * https://github.com/davisking/dlib/issues/2099
````
/opt/data/DlibDotNet/src/dlib/dlib/cuda/cuda_dlib.cu(1762): error: calling a constexpr __host__ function("log1p") from a __device__ function("cuda_log1pexp") is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.
````

**Comment by takuya-takeuchi** [comment]
> * build for cuda 9.2 and 10.0 fails
>   * [davisking/dlib#2099](https://github.com/davisking/dlib/issues/2099)
> 
> ```
> /opt/data/DlibDotNet/src/dlib/dlib/cuda/cuda_dlib.cu(1762): error: calling a constexpr __host__ function("log1p") from a __device__ function("cuda_log1pexp") is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.
> ```

https://github.com/ageitgey/face_recognition/issues/1039#issuecomment-590880149
https://github.com/davisking/dlib/commit/23b9abd07a56f9fef560aa9e263b37f82543a0cc

**Comment by takuya-takeuchi** [comment]
https://github.com/davisking/dlib/issues/2099#issuecomment-663199368

Fixed but dlib should fix this issue rather than modify submodule.

**Comment by takuya-takeuchi** [comment]
PR done
https://github.com/takuya-takeuchi/DlibDotNet/pull/205

But CentOS does not support due to not publishing docker image from nvidia.
