### ISSUE TITLE
Cannot set the contents of an "Array2D" directly

### ISSUE THREAD

**Issue by zalo** [takuya-takeuchi/DlibDotNet#2]
# Summary of your issue
There does not appear to be a method to set the contents of an `Array2D` directly (either on a per-element basis or on a bulk-basis via a byte array).

## Example code:
Examples use `Dlib.LoadImage<byte>()` to populate `Array2D` objects (which loads an image from a file). There does not appear to be a safe way to set them to arbitrary `byte[]` arrays...

## What did you intend to be?
Ideally, there would be a `Dlib.LoadImageData<byte>()` function which takes a `byte[]` as input and fills the Array2D with data.

**Comment by takuya-takeuchi** [comment]
Thank you for your interest in this projects.

Yes, for now there is no the following interface.

    var rawData = File.IO.ReadAllBytes(file);
    var array = Dlib.LoadImageData(rawData);

I guess dlib::assign_pixel function is what you want.
I found [sample source](https://github.com/roymacdonald/ofxDLib-DEPRECATED-/blob/master/src/ofxDLib.h) which use this function.
But I hope there is more better function in dlib.
However, dlib api is too complex.

**Comment by takuya-takeuchi** [comment]
Hi there.

I added new method to Dlib.ImageLodaData<T>(Type[] data, uint rows, uint columns, uint steps).
For now, dest type must equal to src type.
