### ISSUE TITLE
How to use the IOS version

### ISSUE THREAD

**Issue by axelborgegmail** [takuya-takeuchi/DlibDotNet#202]
# Summary of your issue
I see you added IOS support in the build scripts, but I cant find how to install it proparly.
# Environment
Visual Studio for Mac Community 8.6.7, MacOS Catalina, Xamarin Forms, IOS 13.6
# What did you do when you faced the problem?

Installed the Nuget Package DlibDotNet 19.20.0.20200725

## Example code:

```
                    using (var detector = Dlib.GetFrontalFaceDetector())
                            using (var img = Dlib.LoadImage<byte>("photo.jpg"))
                            {
                                Dlib.PyramidUp(img);

                                var dets = detector.Operator(img);
                                Console.WriteLine($"Number of faces detected: {dets.Length}");
                            }
```

## Output:

```
{System.TypeInitializationException: The type initializer for 'DlibDotNet.NativeMethods' threw an exception. ---> System.DllNotFoundException: DlibDotNetNativeDnn assembly:<unknown assembly> type:<unknown type> member:(null)
  at (wrapper managed-to-native) DlibDotNet.NativeMethods.LossMetric_anet_type_create()
  at DlibDotNet.NativeMethods..cctor () [0x0002a] in <1cebcf54e31b48c2871aefc17cb62992>:0 
   --- End of inner exception stack trace ---
  at DlibDotNet.Dlib.GetFrontalFaceDetector () [0x00000] in <1cebcf54e31b48c2871aefc17cb62992>:0 
  at Ideally.IdeallySignUpPage..ctor () [0x00119] in xxx.cs }
```

**Comment by takuya-takeuchi** [comment]
@axelborgegmail 

This script is experimental and I was not checking whether this script works.
And DlibDotNet 19.20.0.20200725 does not contain ios binary.

**Comment by takuya-takeuchi** [comment]
![ABE8672D-BE84-4321-8A66-3DCAD21E1CE1](https://user-images.githubusercontent.com/6241854/89886882-4f822600-dc08-11ea-8986-6270d40d4bef.png)

**Comment by takuya-takeuchi** [comment]
But all api enables then build fails.
There is many many works to use.

**Comment by baartho** [comment]
I have a rookie question. 

It means it isn't available yet for xamarin? 

If it isn't, do you have any plans to release it?

**Comment by takuya-takeuchi** [comment]
@baartho 
yes, I have to do a lot works to use on ios.

**Comment by takuya-takeuchi** [comment]
I restart to develop ios libs.
I have already built ios and android binary.
But there is some issue

* Binary is too large so it occurs to fail deploy for android
* iOS binary have to remove unused functions or add missing function to resolve undefined symbols

**Comment by takuya-takeuchi** [comment]
close by #258
