### ISSUE TITLE
Error deserializing dlib_face_recognition_resnet_model_v1.dat

### ISSUE THREAD

**Issue by SimonKravis** [takuya-takeuchi/DlibDotNet#206]
# When I execute the code `var FaceDescriptors = DlibDotNet.Dnn.LossMetric.Deserialize(lossMetricFilePath).Operator(faceMatrices); where lossMetricFilePath is `C:\Users\Simon\source\repos\dlib_face_recognition_resnet_model_v1.dat` I get the exception "External component has thrown an exception." faceMatrices list has 2 elements, 200x200. Debug view of 1 element below:
![faceMatricesElement](https://user-images.githubusercontent.com/8662136/90949840-6be75380-e48f-11ea-8cda-d7b77d2fe6cf.png)

# Environment

Visual Studio 2019, Windows Forms App, Windows 10 64 bit, C#. DlibDotNet, FaceRecognitionDotNet from Nuget as shown below:.
![Installed Components from Nugetpng](https://user-images.githubusercontent.com/8662136/90949883-2aa37380-e490-11ea-822e-0e72dce831f3.png)
 ShapePredictor works OK.

# What did you do when you faced the problem?

Stopped development

## Example code:

```
paste your core code
```

## Output:

```
paste your output
```

**Comment by SimonKravis** [comment]
Any hints? I have downloaded the source code for DlibDotNet and am able to build it after much experimentation and modification for Windows  but if I add the project .. DlibDotNet-master\src\DlibDotNet/DlibDotNet.csproj  to my solution I can't step into the source code to try and find out exactly what is going wrong, perhaps because the NuGet reference to FaceRecognitionDotNet includes DlibDotNet.dll. Can you suggest how I might be able to step into the source code to try and diagnose the problem further?

**Comment by SimonKravis** [comment]
I didn't mean to close the issue ...

**Comment by takuya-takeuchi** [comment]
@SimonKravis 
I'm very sorry to delay response,.
I'm very busy and have no time to go through issue.
I am palanning to check it on this weekend.

Thanks.

**Comment by SimonKravis** [comment]
That's OK - support is appreciated but not expected. I have tried rebuilding the project using .NetCore 3.1 rather than .NetFramework 4.6.1 and get the same error. If I try and use built source code rather than Nuget package I get an error deserialising ShapePredictor. I've tried to step into the Nuget package DlibDotNet with the debugger to get more detail on the error, but none of the suggested methods allow me to do this.

**Comment by takuya-takeuchi** [comment]
@SimonKravis 
OK, I forgot to how to use LossMetric.
You can check https://github.com/takuya-takeuchi/DlibDotNet/blob/develop/examples/DnnFaceRecognition/Program.cs

In conclusion, input image must be 150x150 for dlib_face_recognition_resnet_model_v1.dat.
This demo output '2'.

````
using System;
using System.Diagnostics;
using System.Drawing;
using System.Drawing.Imaging;
using System.Linq;
using System.Runtime.InteropServices;
using DlibDotNet;

namespace _206
{
    class Program
    {
        static void Main(string[] args)
        {
            var modelFile = "dlib_face_recognition_resnet_model_v1.dat";
            var bmpFile = "Lenna_150x150.bmp";

            var faceMatrices = Enumerable.Range(0,2).Select(i => Dlib.LoadImageAsMatrix<RgbPixel>(bmpFile)).ToArray();
            using(var model = DlibDotNet.Dnn.LossMetric.Deserialize(modelFile))
            using(var result = model.Operator(faceMatrices, 2))
            {
                Console.WriteLine(result.Count);
            }

            foreach(var bmp in faceMatrices)
                bmp.Dispose();
        }
    }
}
````

**Comment by SimonKravis** [comment]
Works fine now. Would be good to make default size for `Dlib.GetFaceChipDetails` 150 rather than 200
