### ISSUE TITLE
How can I get extracted faces in L-R order in image?

### ISSUE THREAD

**Issue by SimonKravis** [takuya-takeuchi/DlibDotNet#207]
I would like to sequence the extracted faces in L-R order. chiplocations[].Rect.left gives the left co-ord of the enclosing rectangle which will work as the ordering parameter.

# Environment

VS 2019 Community, Win 10, Windows Forms Project

# What did you do when you faced the problem?

Stopped.

# Code:
```
var chipLocations = Dlib.GetFaceChipDetails(shapes, 150, 0.5); // make chips 150 x 150

                    using (var faceChips = Dlib.ExtractImageChips<RgbPixel>(img, chipLocations,))
                    {
                        Image image = null;
                        //Iterate face chips and add image to  images 
                        foreach (var face in faceChips)
                        {
                            image = face.ToBitmap();
                            images.Add(image);
                            Matrix<RgbPixel> faceMatrix = new Matrix<RgbPixel>(face);
                            faceMatrices.Add(faceMatrix);
                        }
                    }
```

## Output:

```
paste your output
```

I would like to have faces in L-R order in the above  loop

**Comment by takuya-takeuchi** [comment]
@SimonKravis 

Sorry. What does it mean?
You mean

1. FaceA ([x,y]=[30, 20])
1. FaceB ([x,y]=[40, 20])
1. FaceC ([x,y]=[20, 20])

to

1. FaceC ([x,y]=[20, 20])
1. FaceA ([x,y]=[30, 20])
1. FaceB ([x,y]=[40, 20])

right?

If so, You can use ChipDetails.Rect to sort by LINQ.

**Comment by SimonKravis** [comment]
Yes, that is the scenario. Can you tell me how to modify the code 
` ChipDetails[] chipLocations = Dlib.GetFaceChipDetails(shapes, 150, 0.5); // make chips 150 x 150` 
 `  using (var faceChips = Dlib.ExtractImageChips<RgbPixel>(img, chipLocations))`
 ` { ` 
 `      foreach (var face in faceChips)`
 `      {`
`           Matrix<RgbPixel> faceMatrix = new Matrix<RgbPixel>(face);`
`           faceMatrices.Add(faceMatrix);`
 `      }`
`}`
to achieve this result?

**Comment by takuya-takeuchi** [comment]
![image](https://user-images.githubusercontent.com/6241854/91662552-2fb29380-eb1e-11ea-9bab-1d46ad0deeea.png)

How is it?

**Comment by takuya-takeuchi** [comment]
@SimonKravis

**Comment by SimonKravis** [comment]
Works OK - thanks. Also needed to sort face rectangle display for application to label multiple faces in a photo
