### ISSUE TITLE
Face Recognition with DlibDotNet

### ISSUE THREAD

**Issue by postacik** [takuya-takeuchi/DlibDotNet#21]
Hi,
I could not find face recognition related functions in the library. Can you explain how these can be included in DlibDotNet.Native.dll?

Thanks :)

**Comment by takuya-takeuchi** [comment]
Face detection samples are

https://github.com/takuya-takeuchi/DlibDotNet/tree/master/examples/FaceDetection
https://github.com/takuya-takeuchi/DlibDotNet/tree/master/examples/FaceLandmarkDetection

I'm sorry if I misunderstand what you want to know.

thank you for your interest in the project.

**Comment by postacik** [comment]
Thank "you" for sharing your project.

Actually face recognition is another subject with the dlib library.

Sample C++ code is below:

http://dlib.net/dnn_mmod_face_detection_ex.cpp.html

Does your DlibDotNet.Native.dll contain the functions in this sample?

**Comment by takuya-takeuchi** [comment]
Unfortunately, C# can not treat with C++ non-type template parameter.
So it is very very hard to use dnn module.
This problems occurs in python module. So also python interface does not provide dnn module.
https://github.com/davisking/dlib/issues/254

However, you do not hesitate to use C++, you can add the following code to DlibDotNet.Native.

Example
````cpp
// Developer can customize these as you want to do!!!
template <long num_filters, typename SUBNET> using con5d = con<num_filters,5,5,2,2,SUBNET>;
template <long num_filters, typename SUBNET> using con5  = con<num_filters,5,5,1,1,SUBNET>;

template <typename SUBNET> using downsampler  = relu<affine<con5d<32, relu<affine<con5d<32, relu<affine<con5d<16,SUBNET>>>>>>>>>;
template <typename SUBNET> using rcon5  = relu<affine<con5<45,SUBNET>>>;

using net_type = loss_mmod<con<1,9,9,1,1,rcon5<rcon5<rcon5<downsampler<input_rgb_image_pyramid<pyramid_down<6>>>>>>>>;

DLLEXPORT void* net_new(matrix_element_type type)
{
    return new net_type();
}

DLLEXPORT void* net_operator(net_type* net, matrix<rgb_pixel>* matrix)
{
    return net(matrix);
}
````
````csharp
[DllImport(NativeMethods.NativeLibrary, CallingConvention = NativeMethods.CallingConvention)]
public static extern IntPtr net_new();

[DllImport(NativeMethods.NativeLibrary, CallingConvention = NativeMethods.CallingConvention)]
public static extern IntPtr net_operator(IntPtr net, IntPtr matrix);

public void Operator(Matrix<Rgb> matrix)
{
    var net = net_new();
    var dets = net_operator(net.NativePtr, matrix.NativePtr)
}
````

Oh, If I provide above code as template in DlibDotNet.Native, it is easy to extend for developer.

**Comment by takuya-takeuchi** [comment]
I understand what you say. You showed the sample of 'detection' and then I misunderstood.

I checked the above repository and read code.
And then I found dlib python uses dnn function as C++.
https://github.com/davisking/dlib/blob/master/tools/python/src/face_recognition.cpp

I guess what you really wanted to show is this sample, right?
http://dlib.net/dnn_face_recognition_ex.cpp.html

In any case, we must to implement dnn function.

**Comment by postacik** [comment]
Sorry for the wrong link. The sample you mention is the correct one.

Thanks.

**Comment by postacik** [comment]
Thank you very much. I'll check it and come back. :))))

**Comment by postacik** [comment]
It works like a charm. Thank you very much. 👍 👍 👍

**Comment by postacik** [comment]
The "new face recognition example" in the "develop" branch works fine but in the WinForms "FaceDetection" example , the loaded image appears completely black with the DlibDotNet.Native.dll from the "develop" branch. 

If I copy DlibDotNet.Native.dll from the master branch it works fine.
