### ISSUE TITLE
Unity Android support

### ISSUE THREAD

**Issue by Zumbalamambo** [takuya-takeuchi/DlibDotNet#216]
Please add unity Android support

**Comment by takuya-takeuchi** [comment]
Now, I have no time to work on hard task.

**Comment by Zumbalamambo** [comment]
Could you please suggest any steps on how I can do that? :)

**Comment by takuya-takeuchi** [comment]
@Zumbalamambo 

I guess we have to do the following steps

1. Build DlibDotNet.Native and DlibDotNet.Native.Native for android
2. Modify DlibDotNet p/invoke definition to access from android
3. Create nuget package

And you can refer this page.
https://docs.microsoft.com/en-us/xamarin/cross-platform/cpp/

**Comment by Zumbalamambo** [comment]
Thanks. It works now
