### ISSUE TITLE
Dlib object detection and tracking

### ISSUE THREAD

**Issue by vinicius121** [takuya-takeuchi/DlibDotNet#22]
Hi,

I trained a object detector in python using Dlib. It detects and tracks the object successfully. 
Now I would like to do the same in C#. I know that I can call the correlation tracker in C#. However, it seems that I can't call the `dlib.simple_object_detector()` function which accepts the trained model. Is there any alternative to this?
Also is there any implementation of the dlib fast multiclass object detection method?[http://blog.dlib.net/2017/09/fast-multiclass-object-detection-in.html](url)
More information here: [http://dlib.net/train_object_detector.py.html](url)

Thanks,

Vinícius

**Comment by takuya-takeuchi** [comment]
simple_object_detetor is missing in C++ api.
It is typedef and defined in the below.
https://github.com/davisking/dlib/blob/master/tools/python/src/simple_object_detector.h

However, maybe there is not some C# api corresponds to above.

**Comment by vinicius121** [comment]
Hi, 

Thanks for answering. Is there a way to import this to the DlibDotNet?

Thanks,

Vinícius

**Comment by takuya-takeuchi** [comment]
You have to implement these C++ APIs in DlibDotNet.Native project and wrap them in DlibDotNet.
In any case, it may not be easy.

In the near future, I might as well implement. However, I am writing the dnn face recognition wrapper. So I have no time and I can not work on now. I'm verry sorry.

**Comment by postacik** [comment]
Great to hear that you are working on the face recognition wrapper. I think it will be used by many projects.

**Comment by takuya-takeuchi** [comment]
Hi, I'm sorry for delay report.
I ported examples\fhog_object_detector_ex.cpp to C#.
https://github.com/takuya-takeuchi/DlibDotNet/tree/develop/examples/FHogObjectDetector

This sample is similar with simple_object_detector.h.

Have a try!

**Comment by vinicius121** [comment]
Hi,

No worries. Thanks for implementing it. 
I already have a detector trained in python to detect an object.
Now, I'm trying to run the detector to detect the object in real time using a webcam.
From what I understood when analyzing the code you use this `detector.Deserialize("detector.svm");` to recall the detector, right?
Then you use `detector.Operator();` to detect the object in an image? 
Finally, I'm using OpenCVSharp 3 to capture the frames by using VideoCapture. Then, I convert it to Mat. My problem now is how do I convert Mat to Matrix<byte>?

Thanks,

Vinícius Silva

**Comment by takuya-takeuchi** [comment]
> detector.Deserialize("detector.svm"); to recall the detector, right?

it’s not meaningful.  in original sample code, this statement only demonstrate how to reuse trained model.

> detector.Operator(); to detect the object in an image?

Correct.
Operator returns bounding boxes.

>My problem now is how do I convert Mat to Matrix<byte>?

I often use OpenCvSharp3.
First, You copy Mat<T>.data to managed array.
Then you can use LoadImageData and Matrix constructor.

I guess some developer use dlib and opencv.
Therefore, I will create sample to demonstrate how to convert data dlib to opencv, vice versa.

**Comment by takuya-takeuchi** [comment]
Hi vinicius121
I ported examples\webcam_face_pose_ex.cpp to C#.
https://github.com/takuya-takeuchi/DlibDotNet/tree/develop/examples/WebcamFacePose

The above sample use OpenCVSharp3 to use WebCam and covert Mat to Array2D.

Have a try!

**Comment by Omar-Belghaouti** [comment]
Hi takuya-takeuchi
I saw your WebcamFacePose example but I got an error
When I use Marshal.Copy method it gives me this error : "Argumen 1 : cannot convert from 'System.array' to 'int[]'"

**Comment by takuya-takeuchi** [comment]
> When I use Marshal.Copy method it gives me this error : "Argumen 1 : cannot convert from 'System.array' to 'int[]'"

Go to #112

**Comment by Omar-Belghaouti** [comment]
Okay
