### ISSUE TITLE
DlibDotNet Working in Local server Not in Online

### ISSUE THREAD

**Issue by KowsalyaR97** [takuya-takeuchi/DlibDotNet#224]
Hi, I referred the below link 
https://medium.com/machinelearningadvantage/detect-faces-with-c-and-dlib-in-only-40-lines-of-code-f0bb1b929133
to detect faces from an image.

I can able to run it in my Local server... But in online server it's not working...

Version
Asp.netcore 3.1
Windows10

This is the packages i have used in my project.

                   <Project Sdk="Microsoft.NET.Sdk.Web">

                   <PropertyGroup>
                       <TargetFramework>netcoreapp3.1</TargetFramework>
                       <UserSecretsId>c7872e35-1f97-4ea1-ac18-8a39dbc9dfed</UserSecretsId>
                   </PropertyGroup>

                   <ItemGroup>
                         <Content Remove="C:\Users\windowsp125\.nuget\packages\dlibdotnet\19.21.0.20201122\build\..\runtimes\win- 
                           AnyCPU\native\DlibDotNetNative.dll" />
                         <Content Remove="C:\Users\windowsp125\.nuget\packages\dlibdotnet\19.21.0.20201122\build\..\runtimes\win- 
                          AnyCPU\native\DlibDotNetNativeDnn.dll" />
                  </ItemGroup>

                  <ItemGroup>
                      <PackageReference Include="DlibDotNet" Version="19.21.0.20201122" />
                          <PackageReference Include="MailKit" Version="2.9.0" />
                          <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="3.1.8" />
                          <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="3.1.8" />
                          <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="3.1.8" />
                          <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="3.1.9" />
                          <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="3.1.9" />
                          <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="3.1.9">
                          <PrivateAssets>all</PrivateAssets>
                          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
                       </PackageReference>
                       <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="3.1.4" />
                   <PackageReference Include="MimeKit" Version="2.9.2" />
                     <PackageReference Include="SendGrid" Version="9.21.0" />
                  </ItemGroup>

              <ItemGroup>
                     <Folder Include="wwwroot\assets\js\NewFolder\" />
               </ItemGroup>

            </Project>

**Comment by KowsalyaR97** [comment]
https://user-images.githubusercontent.com/58511867/100496060-fdddb700-3176-11eb-9608-00c7c88b6b0b.jpg

I make the fresh installation... and then try to publish my project... Even though its not working

**Comment by takuya-takeuchi** [comment]
@KowsalyaR97 
You are talinkg about ASP.NET core?
I have never tried DlibDotNet for ASP.NET core.
But publish command is a part of dotnet.
So it could work fine.

Let me check.

**Comment by takuya-takeuchi** [comment]
Visual Studio Configuration Manager could configure build configuration for Debug-x64.
But I'm not sure why I can not add x64 to platform.
So we can not publish proper contents even though we select x64 on Visual Studio.

![image](https://user-images.githubusercontent.com/6241854/100497556-92f4a600-319f-11eb-983e-aa493ce379b6.png)

**Comment by takuya-takeuchi** [comment]
Sorry. I can add x64 to plaform for new solution file.
Existing solution file DlibDotNet.sln looks like to be unstable.

And then, I can publish correct contents by publish command from visual studio.

![image](https://user-images.githubusercontent.com/6241854/100497655-49f12180-31a0-11eb-8b0c-5c33e53efffe.png)

**Comment by takuya-takeuchi** [comment]
@KowsalyaR97 
FYI, I add examples of ASP.NET.
https://github.com/takuya-takeuchi/DlibDotNet/tree/develop/examples/ASP.NET

**Comment by KowsalyaR97** [comment]
@takuya-takeuchi 
Thanks...

**Comment by KowsalyaR97** [comment]
https://user-images.githubusercontent.com/58511867/100519520-6f8d2380-31be-11eb-9f51-82e6000e2f4a.jpg
Hi @takuya-takeuchi

After publish my project, I got the following dll files.... When I put these files in my online server it's not working.

**Comment by takuya-takeuchi** [comment]
@KowsalyaR97 

> it's not working.

I can say nothing to resolve issue without error message, hint and useful information.

**Comment by KowsalyaR97** [comment]
Hi @takuya-takeuchi, thanks for your kind support.
https://user-images.githubusercontent.com/58511867/100762379-e83bec00-3419-11eb-994e-c39ba64c2ef4.jpg
Finally I fixed my issue by changing the configuration before publish my project... Before I changed the configuration as you said in this link https://github.com/takuya-takeuchi/DlibDotNet/wiki/DlibDotNet-is-not-copied-to-output-directory.
