### ISSUE TITLE
Is DLibdotnet supports multilingual

### ISSUE THREAD

**Issue by KowsalyaR97** [takuya-takeuchi/DlibDotNet#226]
Hi, While using Dlibdotnet to detect faces it load images from the directory named with some other language it shows a LoadImageExeption.

Code I have used to load images,
`Dlib.LoadImage<RgbPixel>(FilePath)`

My image path contains a string **Guarín** but dlibdotnet get this string as **GuarÃn** and produces an error as below link.
https://user-images.githubusercontent.com/58511867/101599252-7c601180-3a1f-11eb-9ca2-a843259bbd07.jpg

I tried this encoding,
`Encoding.UTF8.GetString(Encoding.UTF8.GetBytes(inputFilePath));`
But no luck.

**Comment by takuya-takeuchi** [comment]
@KowsalyaR97 
dlib (not DlibDotNet) does not support utf8 because it uses std::string.
So we have to take care of encoding of file path.
But you can pass encoding you want to use to DlibDotNet.

````csharp
DlibDotNet.Encodings = System.Text.Encoding.GetEncoding("gb2312"); // please specify proper encoding.
````

**Comment by whiteDigitalAI** [comment]
Thanks @takuya-takeuchi  

Where to implement this code of line? I am tying Spanish which is 850 so I have to declare the encoding as 

DlibDotNet.Encodings = System.Text.Encoding.GetEncoding(850); // please specify proper encoding.

 and it will be great if you specify on which file/line to implement this code..  Thanks in advance

**Comment by whiteDigitalAI** [comment]
BTW I am using Nuget Package to install on my ASP.Net core 3.1 project.. Thanks

**Comment by takuya-takeuchi** [comment]
@whiteDigitalAI 

> Where to implement this code of line

You can do anytime before call api with path string.
Generally, we should call it on startup application.

**Comment by takuya-takeuchi** [comment]
@whiteDigitalAI 
Yeah, I'm focusing ASP.NET core to get server side technology.
So I  start to provide/create ASP.NET apps.

* https://github.com/takuya-takeuchi/DlibDotNet/tree/develop/examples/ASP.NET
* https://github.com/takuya-takeuchi/FaceRecognitionDotNet.Server/tree/develop

Thanks

**Comment by whiteDigitalAI** [comment]
@takuya-takeuchi 

Thank You very much.. That worked like a breeze..  BTW the code page was "1250"  

Cheers
