### ISSUE TITLE
Suggestion: Public interface to quickly convert a byte array to Array2D

### ISSUE THREAD

**Issue by Necromantic** [takuya-takeuchi/DlibDotNet#23]
I saw that you are using a method in BitmapExtensions to convert from Bitmaps to Array2D. This is a bit limiting and the methods you are set to be private or internal.
So I opened up the interface by adding a public method to DlibDotNet that just does this.
`public static void rawToArray2D(IntPtr src, ImageTypes dstType, IntPtr dst, bool rgbReverse, uint height, uint width, uint stride, uint channels) {
    Dlib.Native.extensions_convert_managed_image_to_array(src, dstType.ToNativeArray2DType(), dst, rgbReverse, height, width, stride, channels);
}`

I think it would be nice to have this in by default as it opens a lot of possibilities to use data from many kinds of sensor and cameras easily. I'm using this with Unity3D and a Realsense D400 and it's much quicker to convert a textures and sensor data that way than with doing it manually with the external interfaces.

**Comment by takuya-takeuchi** [comment]
Thank you for your suggenstion.

I guess DlibDotNet already provide Array2D<T> Dlib.ImageLodaData(Type[] data, uint rows, uint columns, uint steps).
Does it satisfy you?
If you want to pass IntPtr, I may be able to do so.

**Comment by Necromantic** [comment]
As far as I can tell DLib.LoadImageData  loads the byte array into an Array2D where every byte is considered a pixel. That's not very useful when you have a RGB image though since it is multiple bytes per pixel. So generally we are missing channel/format data there.
And yes, sometimes passing an IntPtr to some native image data can also make things easier and faster.

**Comment by Necromantic** [comment]
No need to hurry, what I added to DlibDotNet works just fine for me for now. I just thought it might be useful for other use-cases of other people as well. Mine is just a quick hack to make it work for what I need.

**Comment by takuya-takeuchi** [comment]
I got it. Again, I would like to express my gratitude for your suggestion!!
