### ISSUE TITLE
Confidence Scores from ObjectDetector.Operator()

### ISSUE THREAD

**Issue by jakecollins1** [takuya-takeuchi/DlibDotNet#232]
Hello @takuya-takeuch

I am loading a custom model for object detections, and I would like to return a IEnumerable of RectDetection instead of an IEnumerable<DlibDotNet.Rectangle>.  The detection is working, but I am interested in getting the DetectionConfidence for each detection.

```
var tmp2 = new DlibDotNet.ScanFHogPyramid<DlibDotNet.PyramidDown, DlibDotNet.DefaultFHogFeatureExtractor>(6);
objectDetector = new ObjectDetector<ScanFHogPyramid<PyramidDown, DefaultFHogFeatureExtractor>>(tmp2);
objectDetector.Deserialize(@"C:\Path\to\model\model.svn");


//After we have already loaded our frame, code below is executed
Matrix<RgbPixel> dlibMatrix = new Matrix<RgbPixel>(array, rgbMat.Height, rgbMat.Width, rgbMat.ElemSize());

IEnumerable<DlibDotNet.Rectangle> detections = objectDetector.Operator(dlibMatrix);

```

Thank you!

**Comment by takuya-takeuchi** [comment]
@jakecollins1 
I am just checking dlib interface.
Maybe non cnn base does not have properties to obtain confidence.

http://dlib.net/cnn_face_detector.py.html
https://github.com/ageitgey/face_recognition/issues/727

**Comment by jakecollins1** [comment]
Thank you for the quick response.

My colleage has prototyped it in python, I am just trying to replicate what he is doing in c#.  Am I using the wrong objects? Here is his code:
```
# Custom trained model
print('Load dlib face detector model: ', path_to_model)
faceDetector_dlib = dlib.fhog_object_detector(path_to_model)
img = dlib.load_rgb_image(str(path_to_image))
# Run dlib custom model
rects_faces, scores, idxs = faceDetector_dlib.run(img)
print(rects_faces)
print(scores)
```

**Comment by takuya-takeuchi** [comment]
@jakecollins1 

The above code could correspond to 

*https://github.com/davisking/dlib/blob/f4f8bff95ec84d441953fb854c5261655c22c824/tools/python/src/object_detection.cpp#L382
  * fhog_object_detector.run => run_rect_detector
    * https://github.com/davisking/dlib/blob/286ca71e1a521ef5f24b3956227f1398140188a8/tools/python/src/simple_object_detector_py.h#L224
      * run_detector_with_upscale1

run_detector_with_upscale1 corresponds to  https://github.com/takuya-takeuchi/FaceRecognitionDotNet/blob/master/src/FaceRecognitionDotNet/Dlib/Python/SimpleObjectDetector.cs

You can modify to obtain confidence from the above source.

**Comment by takuya-takeuchi** [comment]
However, we may be able to return confidence for only cnn detection.
In https://github.com/takuya-takeuchi/FaceRecognitionDotNet/blob/e91da42cabb351bc841b2ceead5270fe11225a8a/src/FaceRecognitionDotNet/FaceRecognition.cs#L928

**Comment by jakecollins1** [comment]
@takuya-takeuchi 

It looks like RunDetectorWithUpscale1 takes a FrontalFaceDetector as the argument.  Is there a way to upload a custom model to that? The only way I can see to instantiate one is using  GetFrontalFaceDetector().

**Comment by takuya-takeuchi** [comment]
I did't try yet but I guess simple_object_detector equals to frontal_face_detector.

* define of frontal_face_detector
  *  ttps://github.com/davisking/dlib/blob/f4f8bff95ec84d441953fb854c5261655c22c824/dlib/image_processing/frontal_face_detector_abstract.h#L12
* define of fhog_object_detector
 * https://github.com/davisking/dlib/blob/f4f8bff95ec84d441953fb854c5261655c22c824/tools/python/src/object_detection.cpp#L362
 * https://github.com/davisking/dlib/blob/286ca71e1a521ef5f24b3956227f1398140188a8/tools/python/src/simple_object_detector_py.h#L16

So you can replace the above type with ObjectDetector.
However, we have to modify if you want to integrate custom non-cnn face detector to FRDN.

Like this

````
        private IEnumerable<MModRect> RawFaceLocations(Image faceImage, int numberOfTimesToUpsample = 1, Model model = Model.Hog)
        {
            switch (model)
            {
                case Model.Custom:
                    return this._CustomFaceDetector.Detect(); // like _CustomGenderEstimator ;
                case Model.Cnn:
                    return CnnFaceDetectionModelV1.Detect(this._CnnFaceDetector, faceImage, numberOfTimesToUpsample);
                default:
                    var locations = SimpleObjectDetector.RunDetectorWithUpscale2(this._FaceDetector, faceImage, (uint)numberOfTimesToUpsample);
                    return locations.Select(rectangle => new MModRect { Rect = rectangle });
            }
        }
````

**Comment by takuya-takeuchi** [comment]
Start development of implementaion for confidence
https://github.com/takuya-takeuchi/DlibDotNet/tree/confidence

**Comment by jakecollins1** [comment]
@takuya-takeuchi thank you for your attention on this!

**Comment by takuya-takeuchi** [comment]
@jakecollins1
I published new nuget package.
please check release note.

**Comment by jakecollins1** [comment]
@takuya-takeuchi 

Thank you so much, it is tested and working.
