### ISSUE TITLE
Missplaced libraries? (Can't find DlibDotNetNative.dll and DlibDotNetNativeDnn.dll)

### ISSUE THREAD

**Issue by ADD-eNavarro** [takuya-takeuchi/DlibDotNet#238]
First things first, thank you very much for your hard work, Takeuchi-san.

# Summary of your issue

In VisualStudio 2019 - New project -Console (.NET Core 3.1), I:
1. Add NuGet package DlibDotNet
2. Change Configuration Manager to Debug x64 (since DlibDotNet won't work with Any-CPU)
3. Replace the "hello world" line with: "using (var ffd = Dlib.GetFrontalFaceDetector()){}" (of course I add the "using DlibDotNet" too)
4. Hit run and get this message:
"Exception thrown: 'System.Exception' in DlibDotNetCore.dll ("Failed to find dll "DlibDotNetNative", for processor architecture AMD64.")

# Environment

Windows Server 2019 Standard, with Intel Xeon processor (ES-2690 v3)

# What did you do when you faced the problem?

After some research, I found that the path to DlibDotNetNative and DlibDotNetNativeDnn seem to be hard-coded inside DlibDotNet. I go to [project]/bin/x64/Debug/netcoreapp3.1/  , copy both .dll, manually create there /dll/x64 and paste both libraries there, and the code starts working flawlessly. 

## What did you intend to be?

I guess DlibDotNet should work straight out of the box.

**Comment by takuya-takeuchi** [comment]
@ADD-eNavarro 
I can not reproduce your issue.

1. Create solution file by `dotnet new sln`
2. Create new console project by `dotnet new console`
3. Open sln
4. Add csproj
5. Change target framework from 5.0 to 3.1
6. Change configuration like the following. It does not matter solution configuration and we must take care of platform

![image](https://user-images.githubusercontent.com/6241854/106915893-eb20c900-6749-11eb-88a3-794ef7f87bc5.png)

7. Build
8. All DlibDotNet binaries are copied automatically

![image](https://user-images.githubusercontent.com/6241854/106916016-0ee40f00-674a-11eb-9da8-3fbc057a5159.png)

9. Works fine

![image](https://user-images.githubusercontent.com/6241854/106916181-3aff9000-674a-11eb-9ae2-cf2a2f1c185d.png)

**Comment by ADD-eNavarro** [comment]
Awesome! It totally works! 

So, if I have understood correctly, the "solution" field in Configuration Manager is irrelevant, we only have to be sure to set "platform" to x64 both in Debug and Release, right? 
Then, does the check on "build" column actually do something? Sorry, I'm not all that familiar with VS.

**Comment by takuya-takeuchi** [comment]
@ADD-eNavarro 
Yes, solution field is what it make easy to understand build configuration.
So You cam remove Any CPU solution from solution configuration because Any CPU does not work.
