### ISSUE TITLE
Creating DPoint from float array

### ISSUE THREAD

**Issue by ADD-eNavarro** [takuya-takeuchi/DlibDotNet#253]
It seems that DlibDotNet doesn't allow the creation of a DPoint from an array, where Dlib does ( [dlib.dpoint](http://dlib.net/python/#dlib.dpoint) ).
I am willing to use your awesome wrapper to compare vectors (voice related), but since DlibDotNet.Dlib.Length takes Point or DPoint as entries, I would need to create those from array (>2 dimensions).
Would this be possible?

**Comment by takuya-takeuchi** [comment]
@ADD-eNavarro 

You can do that
````csharp
using var mat = new Matrix<float>(new float[10], 1 ,10);
var length = DlibDotNet.Dlib.Length(mat);
````

**Comment by ADD-eNavarro** [comment]
As usual, awesome fast and accurate answer. Thanks again!
