### ISSUE TITLE
Is there a way convert Array2D<RgbPixel> to  Matrix<RgbPixel>?

### ISSUE THREAD

**Issue by goodmorningsky** [takuya-takeuchi/DlibDotNet#260]
# Summary of your issue
Cannot load image to Matrix<RgbPixel> in uwp app.

# Environment

Write your environment.

# What did you do when you faced the problem?

//write here

## Example code:

```
paste your core code
```

## Output:

```
paste your output
```

## What did you intend to be?

UWP doesn't allow app to read file. File system access in uwp is totally different. So, any method using path are NOT usable in uwp.
I saw public Array2D<RgbPixel> LoadFromSoftwareBitmap(SoftwareBitmap Bitmap) method from a post.
I have no issue detecting. I try to mimic DnnFaceRecognition example in uwp. 

Dlib.LoadImageData for Array2D, but Dlib doesn't have load data for LoadImageAsMatrix. 
If I can convert Array2D<RgbPixel> to Matrix<RgbPixel> it is nice!.

if not, is there a way LoadFromSoftwareBitmap method to return Matrix<RgbPixel>?

**Comment by takuya-takeuchi** [comment]
@goodmorningsky 

You can use `Matrix<T>(Array2D<T> array)`.
https://github.com/takuya-takeuchi/DlibDotNet/blob/8c1cbab8048e07fb74c6509401b68271a5f69bdf/src/DlibDotNet/Matrix/Matrix.cs#L44

**Comment by goodmorningsky** [comment]
Thank you Takuya!
