### ISSUE TITLE
how to convert RGB Array to Image?

### ISSUE THREAD

**Issue by HyungJoo-Kwon** [takuya-takeuchi/DlibDotNet#265]
# Summary of your issue
I have 256 x 256 x 3 RGB Array(NumSharp.NDArray). And I want Save this Array to Dlib Image Not Bitmap.
Please give me an idea or help.

# Environment

Write your environment.

# What did you do when you faced the problem?

1.
var output_byte = array.ToByteArray();
var output_img = Dlib.LoadImageData(output_byte, 256, 256, 256*3);

→ The result is coming out, but the result is wrong. It's part of the image and gray image

2.
var rgb_array = new Array2D<RgbPixel>(256, 256);
        for (var a = 0; a < 256; a++)
            for (var b = 0; b < 256; b++)
                rgb_array[a][b] = new RgbPixel(array[a][b][0], array[a][b][1], array[a][b][2])
var output_img = Dlib.LoadImageData(rgb_array, 256, 256, 256 * 3);

→ cannot convert from 'DlibDotNet.Array2D<DlibDotNet.RgbPixel>' to 'byte[]'

var rgb_array = new Array2D<RgbPixel>(256, 256);
        for (var a = 0; a < 256; a++)
            for (var b = 0; b < 256; b++)
                rgb_array[a][b] = new RgbPixel(array[a][b][0], array[a][b][1], array[a][b][2])
var output_img = Dlib.LoadImageData(rgb_array, 256, 256, 256 * 3);

3.
var rgb_array = new Array2D<RgbPixel>(256, 256);
      for (var a = 0; a < 256; a++)
          for (var b = 0; b < 256; b++)
              rgb_array[a][b] = new RgbPixel(output[a][b][0], output[a][b][1], output[a][b][2]);
var output_byte = rgb_array.ToBytes();
var output_img = Dlib.LoadImageData(output_byte, 256, 256, 256 * 3);

→ The result is coming out, but the result is wrong. It's part of the image and gray image

**Comment by takuya-takeuchi** [comment]
You mean that you want to create raw image, right?
What is `output`?

The following code works fine.

````csharp
using System;
using System.IO;
using DlibDotNet;

namespace Issue265
{
    class Program
    {
        static void Main(string[] args)
        {
            const int width = 256;
            const int height = 256;
            const int channels = 3;
            var raw = new byte[width * height * channels];
            for (var h = 0; h < height; h++)
            for (var w = 0; w < width; w++)
            {
                var value = (byte)Math.Max(w, h);
                raw[width * channels * h + w * channels + 0] = value;
                raw[width * channels * h + w * channels + 1] = value;
                raw[width * channels * h + w * channels + 2] = 0;
            }
            var rgb = new Array2D<RgbPixel>(height, width);
            for (var h = 0; h < height; h++)
            for (var w = 0; w < width; w++)
            {
                var value = (byte)Math.Max(w, h);
                rgb[h][w] = new RgbPixel(value, value, 0);
            }

            var array2D = Dlib.LoadImageData<RgbPixel>(raw, width, height, width * channels);
            File.WriteAllBytes("raw.raw", raw);
            Dlib.SaveBmp(array2D, "raw.bmp");

            var rawRgb = rgb.ToBytes();
            File.WriteAllBytes("rgb.raw", rawRgb);
            var array2DRgb = Dlib.LoadImageData<RgbPixel>(rawRgb, width, height, width * channels);
            Dlib.SaveBmp(array2DRgb, "rgb.bmp");
        }
    }
}
````

**Comment by HyungJoo-Kwon** [comment]
Thanks for your response
I solved the problem that I thought about for a long time. !
