### ISSUE TITLE
 error: symbol lookup error: undefined symbol: LossMetric_anet_type_create (fatal)

### ISSUE THREAD

**Issue by martienpoels-bank2loyalty** [takuya-takeuchi/DlibDotNet#270]
I'm trying to run object tracking on Ubuntu 20,0 Core. The linux-arm64 library seems to miss a symbol.
I started my program with LD_DEBUG=files so to get some information on the loaded libraries.

I'm running Ubuntu core (64bit!) on a raspberryPi4b, running dotnet 5  (version 401)
Output from uname -a

```
Linux ubuntu 5.4.0-1053-raspi #60-Ubuntu SMP PREEMPT Fri Feb 11 07:18:29 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux
```

```
Start
     33165:
     33165:     file=/home/bank2loyalty/object-tracking/runtimes/linux-arm64/native/DlibDotNetNativeDnn.so [0];  dynamically loaded by /home/bank2loyalty/.dotnet/shared/Microsoft.NETCore.App/5.0.14/libcoreclr.so [0]
     33165:
     33165:     file=/home/bank2loyalty/.dotnet/shared/Microsoft.NETCore.App/5.0.14/DlibDotNetNativeDnn.so [0];  dynamically loaded by /home/bank2loyalty/.dotnet/shared/Microsoft.NETCore.App/5.0.14/libcoreclr.so [0]
     33165:
     33165:     file=/home/bank2loyalty/object-tracking/DlibDotNetNativeDnn.so [0];  dynamically loaded by /home/bank2loyalty/.dotnet/shared/Microsoft.NETCore.App/5.0.14/libcoreclr.so [0]
     33165:
     33165:     file=DlibDotNetNativeDnn.so [0];  dynamically loaded by /home/bank2loyalty/.dotnet/shared/Microsoft.NETCore.App/5.0.14/libcoreclr.so [0]
     33165:
     33165:     file=/home/bank2loyalty/object-tracking/runtimes/linux-arm64/native/libDlibDotNetNativeDnn.so [0];  dynamically loaded by /home/bank2loyalty/.dotnet/shared/Microsoft.NETCore.App/5.0.14/libcoreclr.so [0]
     33165:     file=/home/bank2loyalty/object-tracking/runtimes/linux-arm64/native/libDlibDotNetNativeDnn.so [0];  generating link map
     33165:       dynamic: 0x0000ffff857bf2f8  base: 0x0000ffff84129000   size: 0x00000000016a3800
     33165:         entry: 0x0000ffff84e3d8a0  phdr: 0x0000ffff84129040  phnum:                  7
     33165:
     33165:     activating NODELETE for /home/bank2loyalty/object-tracking/runtimes/linux-arm64/native/libDlibDotNetNativeDnn.so [0]
     33165:
     33165:     calling init: /home/bank2loyalty/object-tracking/runtimes/linux-arm64/native/libDlibDotNetNativeDnn.so
     33165:
     33165:     opening file=/home/bank2loyalty/object-tracking/runtimes/linux-arm64/native/libDlibDotNetNativeDnn.so [0]; direct_opencount=1
     33165:
     33165:     /home/bank2loyalty/object-tracking/runtimes/linux-arm64/native/libDlibDotNetNativeDnn.so: error: symbol lookup error: undefined symbol: LossMetric_anet_type_create (fatal)
Unhandled exception.      33165:
     33165:     file=diasymreader.dll [0];  dynamically loaded by /home/bank2loyalty/.dotnet/shared/Microsoft.NETCore.App/5.0.14/libcoreclr.so [0]
     33165:
     33165:     file=/home/bank2loyalty/.dotnet/shared/Microsoft.NETCore.App/5.0.14/diasymreader.dll [0];  dynamically loaded by /home/bank2loyalty/.dotnet/shared/Microsoft.NETCore.App/5.0.14/libcoreclr.so [0]
     33165:
     33165:     file=diasymreader.dll [0];  dynamically loaded by /home/bank2loyalty/.dotnet/shared/Microsoft.NETCore.App/5.0.14/libcoreclr.so [0]
     33165:
     33165:     file=/home/bank2loyalty/.dotnet/shared/Microsoft.NETCore.App/5.0.14/diasymreader.dll [0];  dynamically loaded by /home/bank2loyalty/.dotnet/shared/Microsoft.NETCore.App/5.0.14/libcoreclr.so [0]
System.TypeInitializationException: The type initializer for 'DlibDotNet.NativeMethods' threw an exception.
 ---> System.EntryPointNotFoundException: Unable to find an entry point named 'LossMetric_anet_type_create' in shared library 'DlibDotNetNativeDnn'.
   at DlibDotNet.NativeMethods.LossMetric_anet_type_create()
   at DlibDotNet.NativeMethods..cctor()
   --- End of inner exception stack trace ---
   at DlibDotNet.NativeMethods.correlation_tracker_new(UInt32 filterSize, UInt32 numScaleLevels, UInt32 scaleWindowSize, Double regularizerSpace, Double nuSpace, Double regularizerScale, Double nuScale, Double scalePyramidAlpha)
   at DlibDotNet.CorrelationTracker..ctor(UInt32 filterSize, UInt32 numScaleLevels, UInt32 scaleWindowSize, Double regularizerSpace, Double nuSpace, Double regularizerScale, Double nuScale, Double scalePyramidAlpha)
   at ObjectTrackTest.ObjectTracker..ctor() in D:\GitHub_HomeAutomation\ai\ObjectTrackTest\ObjectTrackTest\ObjectTracker.cs:line 16
   at ObjectTrackTest.Program.Main(String[] args) in D:\GitHub_HomeAutomation\ai\ObjectTrackTest\ObjectTrackTest\Program.cs:line 10
Aborted

```
The error by itself is pretty self explaining I guess but how to fix this? Is the aarch64 a different architecture and not supported?

I can not run build processes or the like as Ubuntu Core is a very basic setup with no tools beside what is absolutely necessary.
I already had a hell of a job to get hold of the gdiplus library stuff I needed in my code. If that is needed I will have to create an image containing ubuntu server 21 or the like.

**Comment by takuya-takeuchi** [comment]
@martienpoels-bank2loyalty 
Thank you for your issue report.
Let me check and give me minute,

**Comment by martienpoels-bank2loyalty** [comment]
Hi Takuya,

First of all I’m impressed with the amount of work you put into this project.
I have setup a fresh version of ubuntu server 21.04 on the raspberry-pi and tried to follow the linux tutorial
I kindly would advise for some improvements in the tutorial.

In general, do not supply the link how to build dlib. As I actually did build the dlib stuff, which was a waste of time…
Or state more clearly dlib is included in your package and that it will be build as part of building the native library. It was a bit confusing.

BUILDING DlibDotNet.Native
To be able to build the DlibDotNet.Native  I had to edit the CMakelists.txt file, I had to remove the setting of the -m64 option. As for ARM architecture this is not a valid option.

To be compatible with other architectures 64 bit arm should be able to specify in the build command somehow so that the -m64 can be correctly removed if 64bit but on arm. I’m not very familiar with CMakelists.txt functionality but I think this can be solved for example by specifying buildtype <desktop, uwp, linux-arm> or something similar. And in that situation remove the -m64 compile option. I’m sure you can find a way to do this.

// Build DlibDotNet.Native
cd DlibDotNet/src/DlibDotNet.Native
nano CMakelists.txt
// comment out
# set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -m64")
# set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -m64")

I also had to load the additional packages  “cmake” and “build-essential” on UBUNTU.

(At the time I have sent this email the native lib was still being build, it was about 77% after 2 hours building…, time to go home.)

BUILDING DlibDotnet
Your page stating how to build DlibDotnet the first 2 lines should be removed and the command is wrong, it should say

dotnet build DlibDotNet.csproj -c Release

Build was successful right away.


So tomorrow I will be try to build de DLibDotNet.Native.DNN lib an hopefully will be able to test and alter stuff to get things going. I’ll keep you posted. Whilst having all the sources in place I should be able to solve the problem. Of course if you have the golden tip or already fixed it I’m happy to hear (and try) that too.


Met vriendelijke groet/with kind regards,

Martien Poels
Founder / CTO


[Bank 2 Loyalty]
Contactless technologies bv
Keizersveld 50
5803 AN Venray
The Netherlands
***@***.******@***.***>
www.bank2loyalty.com<http://www.bank2loyalty.com/>
+31 (0) 478 206900<tel:+314787206900>

**Comment by martienpoels-bank2loyalty** [comment]
I have not been able to compile DlibDotNet.Native  the compiler keeps using more and more memory until it get's killed while consuming 3.7Gbyte.  (System memory is 2G plus I added 2Gbyte as swap space) 

Trying to build DlibDotNet.Native.Dnn now. Which has the problem... Fingers crossed if that will run. Currently 87%..

**Comment by takuya-takeuchi** [comment]
@martienpoels-bank2loyalty 
Sorry for late reply.
I have a lot of work and I have no time to contribute project.

At first. I reply first question

> Linux ubuntu 5.4.0-1053-raspi #60-Ubuntu SMP PREEMPT Fri Feb 11 07:18:29 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux

For now, DlibDotNet doesn ot support Arm binary.
And I have raspberry pi 3 but it takes much time to build binary.
So I had avoided to do.

> Stuck at 90% Building CXX object CMa

It could not work If you try debug build.
Debug build will generate huge objects. Especially, dlibdotnet uses numerous C++ template.
But main reason of stuck is what build is running in raspberry pi because it has only poor cpu and I/O.
