### ISSUE TITLE
Building DlibDotNet.Native with VisualStudio 2019

### ISSUE THREAD

**Issue by GioviQ** [takuya-takeuchi/DlibDotNet#271]
# Summary of your issue
![image](https://user-images.githubusercontent.com/7103057/158776616-e41500fe-ca04-4358-9351-99ec4825d019.png)

# Environment
Windows 10 x64
CMake 3.23
Visual Studio 2019

The second time I run the script the error change (unable to find [Config]). Why?

**Comment by takuya-takeuchi** [comment]
@GioviQ 
you must use powershell core rather than builtin powershell.

**Comment by GioviQ** [comment]
Thank you
On my computer I have the default Windows PowerShell and PowerShell 7.
From https://github.com/PowerShell/PowerShell I understand that PowerShell 7 is a recent PowerShell Core, isn't it?

**Comment by GioviQ** [comment]
![image](https://user-images.githubusercontent.com/7103057/158830515-ced262d5-8135-4484-87ef-7dcdab11f71a.png)
This is with PowerShell 7, so I have to change something to get it working with Visual Studio 2019.

**Comment by takuya-takeuchi** [comment]
@GioviQ 
DlibDotNet does not use VS2019.
You must install VS 2017 but you may able to get it work by changing the following script.

https://github.com/takuya-takeuchi/DlibDotNet/blob/master/nuget/BuildUtils.ps1#L125

**Comment by GioviQ** [comment]
thank you, the compilation was very long, but succeded. Maybe you can write the above tip in your wiki.
My goal is making https://github.com/takuya-takeuchi/FaceRecognitionDotNet work without AVX on Celeron CPU.

**Comment by GioviQ** [comment]
It works.
