### ISSUE TITLE
 Dlib.ChineseWhispers labels.Length  double  facecount on centos7. but on Windows it works fine.

### ISSUE THREAD

**Issue by falsebo** [takuya-takeuchi/DlibDotNet#272]
Hello.
# Summary of your issue
I run examples on Centos7 .   Dlib.ChineseWhispers return labels.Length  double  facecount . on Windows it works fine.
# Environment
Centos7  x64 .  CPU:  Intel(R) Xeon(R) CPU E7- 4820  @ 2.00GHz

# What did you do when you faced the problem?
examples/DnnFaceRecognition 

//write here

## Example code:

```

                Console.WriteLine($"faceDescriptors of people found in the image: {faceDescriptors.Count}");

                Dlib.ChineseWhispers(edges, 100, out var numClusters, out var labels);

                // This will correctly indicate that there are 4 people in the image.
                Console.WriteLine($"number of people found in the image: {numClusters},labels.length:{labels.Length}");

```

## Output:

```
faceDescriptors of people found in the image: 12
number of people found in the image: 4,labels.length:24

Unhandled Exception: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at DnnFaceRecognition.Program.Main(String[] args)
```

**Comment by falsebo** [comment]
I check return if labels.Length == face.Count*2 ;
then
 var newlabels =  new uint[face.Count] ; 
 for(var i =0;i<face.Count,i++) { 
        newlabels[i] =  labels[2*i];
  } 
is it the Interim solution?

**Comment by takuya-takeuchi** [comment]
I think so.
But it could not resolve underlying factor.

**Comment by falsebo** [comment]
I looked at the source code and tried to find out why, but I couldn't find it.

**Comment by takuya-takeuchi** [comment]
I have no time to go though issue but I could be able to take time on this weekend.
So I prepare centos and check it.
thank you for your patient.

**Comment by takuya-takeuchi** [comment]
OK, I can reproduce it.

## Windows by DlibDotNet CPU

faces has 4items.
edges has 83 items.
Dlib.ChineseWhispers returns 4 numClusters and 24 labels

## CentOS 7.6 by DlibDotNet CPU

faces has 4items.
edges has 83 items.
Dlib.ChineseWhispers returns 4 numClusters and 48 labels

And labels content  is different between windows and centos.
But dlib example program does not occur this issue.

**Comment by takuya-takeuchi** [comment]
In DlibDotNetNative, library return proper result;

````cpp
DLLEXPORT unsigned long clustering_chinese_whispers(std::vector<sample_pair*>* edges,
                                                    std::vector<unsigned long>* labels,
                                                    const unsigned long num_iterations = 100)
{
    std::vector<sample_pair*>& e = *(static_cast<std::vector<sample_pair*>*>(edges));
    std::vector<sample_pair> edges_tmp;
    for (int index = 0; index < e.size(); index++)
    {
        sample_pair& edge = *(static_cast<sample_pair*>(e[index]));
        edges_tmp.push_back(edge);
    }

    std::vector<unsigned long>& l = *(static_cast<std::vector<unsigned long>*>(labels));
    const auto ret = dlib::chinese_whispers(edges_tmp, l, num_iterations);
    cout << "chinese_whispers return edges_tmp: " << edges_tmp.size() << ", l: " << l.size() << endl;
    return ret;
}

chinese_whispers return edges_tmp: 83, l: 24
````

In conclusion, StdVector should have any problem.

**Comment by takuya-takeuchi** [comment]
OK, I understand. I used wrong type std::vector.

````cpp
    unsigned long chinese_whispers (
        const std::vector<ordered_sample_pair>& edges,
        std::vector<unsigned long>& labels,
        const unsigned long num_iterations,
        dlib::rand& rnd
    );
````

* Windows
  * sizeof(unsigned long) is 4
* Linux
  * sizeof(unsigned long) is 8

 So I fix clustering_chinese_whispers.

**Comment by falsebo** [comment]
Thank you for your reply.
it works fine.
thanks again.
