### ISSUE TITLE
[Memory Leak] Disposing an Array2D<RgbPixel> does not dispose of contained RgbPixels

### ISSUE THREAD

**Issue by GNUGradyn** [takuya-takeuchi/DlibDotNet#289]
# Summary of your issue
Adding RgbPixels to an Array2D and then disposing the Array2D leaves the RgbPixels in unmanaged memory causing a memory leak.

Disposing an empty Array2D<RgbPixel> works as expected

# Environment

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x64

Host:
  Version: 6.0.6
  Commit:  7cca709db2

# What did you do when you faced the problem?

Created a new Array2D of RgbPixels, added some RgbPixels, then disposed of the Array2D

## Example code:
The following code works as expected
```csharp
using DlibDotNet;

while (true)
{
    var test = new Array2D<RgbPixel>(10, 10);
    test.Dispose();
}
```
the following code leaks memory rapidly
```csharp
using DlibDotNet;

while (true)
{
    var test = new Array2D<RgbPixel>(10, 10);
    test[0][0] = new RgbPixel
    {
        Red = 0,
        Green = 0,
        Blue = 0
    };
    test.Dispose();
}
```
## Output:

![image](https://user-images.githubusercontent.com/20762604/182201105-5b68a0a9-4f79-4c34-ae36-ae734a7940be.png)

## What did you intend to be?
Disposing an Array2D<RgbPixel> should also dispose contained RgbPixels

Side note: I'm not sure if this is intended behavior but Array2Ds will also not get cleaned up by GC.  You have to dispose of them manually

**Comment by takuya-takeuchi** [comment]
@GNUGradyn 
Thank you for your good investigation.
I'll try to reproduce it,

**Comment by takuya-takeuchi** [comment]
NOTE
return of `NativeMethods.array2d_row` would not be disposed

**Comment by takuya-takeuchi** [comment]
Row<T> should receive `row` in constructor and Row<T>[index] use `row` and `columns`.
It should take a bit more time but does not use unnecesarry memory.

**Comment by takuya-takeuchi** [comment]
@GNUGradyn 
Could you try the following code?

````csharp
using DlibDotNet;

while (true)
{
    var test = new Array2D<RgbPixel>(10, 10);
    var row = test[0];
    row[0] = new RgbPixel
    {
        Red = 0,
        Green = 0,
        Blue = 0
    };
    row.Dispose();
    test.Dispose();
}
````

I think it works.

**Comment by GNUGradyn** [comment]
@takuya-takeuchi thank you for the quick response. This does work, but it feels like more of a workaround then a solution. When using an Array2D<RgbPixel> to store an image for facial recognition for an example, you would have to iterate thru and dispose every row when you are done (could be over 1000 rows for a higher resolution image). This could really start to add up if you are processing several frames to track a moving face, especially considering how often GC has to run when you are disposing of thousands of objects constantly. 

If this is unavoidable, the library should at least do this automatically when you dispose the Array2D

**Comment by GNUGradyn** [comment]
I'm not really sure why but this solution also does not appear to work when creating/disposing rows in a loop
```csharp
using DlibDotNet;

while (true)
{
    var test = new Array2D<RgbPixel>(10, 10);

    // Make some rows
    for (var i = 0; i < 10; i++)
    {
        var row = test[i];
        row[0] = new RgbPixel
        {
            Red = 0,
            Green = 0,
            Blue = 0
        };
    }
    
    // Delete all the new rows
    for (var j = 0; j < 10; j++)
    {
        var row = test[j];
        row.Dispose();
    }

    test.Dispose();
}
```
![image](https://user-images.githubusercontent.com/20762604/182438292-a6683eeb-b23b-4f1c-804c-a6c2601bbda3.png)

**Comment by GNUGradyn** [comment]
`Matrix` does not appear to have the same issue. Simply disposing of a `Matrix` works as you'd expect.

**Comment by GNUGradyn** [comment]
Using a `Matrix` appears to hit the garbage collector pretty hard, but not quite hard enough to create a GC pressure memory leak. This is an acceptable workaround 
![image](https://user-images.githubusercontent.com/20762604/182443264-9bbd9df1-d483-462b-8654-4374d75a0332.png)

**Comment by takuya-takeuchi** [comment]
> var row = test[i];

After execute this, Row<T> is generated. Row<T> has unmanaged object.
So this object shall be disposed every time.

> If this is unavoidable, the library should at least do this automatically when you dispose the Array2D
Yes, I agree with you.
So I will fix Array<T>[int][int].

Thanks.

**Comment by takuya-takeuchi** [comment]
@GNUGradyn 
I fixed issue.

## 1. Keep current interface Array2D[int row]

This interface intents to let developer access to column value efficiently.
For example

````csharp
using (var row = array[0])
{
    for (var c = 0; array.Columns; c++)
        Console.WriteLien(row[c]);
}
````

Row<TElement> holds native pointer to improve performance.
So developer shall take care of usage of this property.

## 2. Add new interface Array2D[int row, int column]

For example

````csharp
var test = new Array2D<RgbPixel>(10, 10);
test[0,0] = new RgbPixel
{
    Red = 0,
    Green = 0,
    Blue = 0
};
````

![image](https://user-images.githubusercontent.com/6241854/183150996-bcf44300-9379-4b23-af1a-33dd5a0b785b.png)

**Comment by GNUGradyn** [comment]
Thanks. I ended up just using a Matrix instead but I appreciate the fix
