### ISSUE TITLE
cuda

### ISSUE THREAD

**Issue by ivarbratberg** [takuya-takeuchi/DlibDotNet#296]
# Summary of your issue

# Environment

Write your environment.

# What did you do when you faced the problem?

//write here

## Example code:

```
paste your core code
```

## Output:

```
paste your output
```

**Comment by ivarbratberg** [comment]
I am missing support for Cuda 12. Is there a recipe on how to do it yourself ? I tried to use DlibDotNet.Cuda.11.2 but it did not work.

**Comment by takuya-takeuchi** [comment]
ok, I'll try it but I have only legacy gpu. So I may not check if it works well.

**Comment by takuya-takeuchi** [comment]
Now, nvidia does not provide cuDNN for CUDA 12.0.
So we can not work on support cuda 12.0.

**Comment by ivarbratberg** [comment]
I was able to run on Nvidian 12 CUDA card using Cuda 11.2 and DLibDotNetCuda11.2,
Not sure what I did wrong in the first place, but I just followed the usual procedure, installing NVidiat tools and the CudNN for 11.2
So at least this post can serve for one thing
