### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by doczoidberg** [takuya-takeuchi/DlibDotNet#3]
Hi,

Is the lib compatible with WPF applications?

Can I use it with image classes of WPF?

**Comment by takuya-takeuchi** [comment]
Thank you for your interest in this projects and suggest good question.

Sample application is created by .NET core. It means that you need not to worry about problem for WPF usage.
However, current DlibDotNet does NOT provide usefull classes. Eg. Convert Dlib image to BitmapSource.

So I have just decided to implement classes to convert DlibDotNet.Array2D to  System.Windows.Media.Imaging.BitmapSource or System.Drawing.Bitmap.
Maybe these functioons will be provided as Extension method.

**Comment by takuya-takeuchi** [comment]
#4

**Comment by takuya-takeuchi** [comment]
Create related issue #4

**Comment by takuya-takeuchi** [comment]
Commit 44698e913c3627a53b89658736bb3230cf65acab.
Support converting Bitmap/WritableBitmap to Array2D and vice versa.
But for now, there is few support format. I'm so sorry :(

**Comment by doczoidberg** [comment]
I try to save an extracted imagechip but struggle with conversions.

  using (var faceChips = Dlib.ExtractImageChips<RgbPixel>(img, chipLocations))
 {
          using (var tileImage = Dlib.TileImages(faceChips))
                                {
                                              // 	Argument 1: cannot convert from 'DlibDotNet.Matrix<DlibDotNet.RgbPixel>' to 'DlibDotNet.Array2D<DlibDotNet.RgbPixel>'

          var tt=   DlibDotNet.Extensions.BitmapExtensions.ToBitmap<RgbPixel>(tileImage);
    ...

**Comment by takuya-takeuchi** [comment]
Oh, I forgot to support Matrix<T> class.
For now, DlibDotNet can only convert Array2D class to Bitmap/WritableBitmap and vice versa.
I guess it is not difficult to implement converting method for Matrix.

**Comment by takuya-takeuchi** [comment]
Reopen #4

**Comment by takuya-takeuchi** [comment]
Close by commit e9d3b3383fe06adfde4ddb0ccbf0e7ce2e1e57c0
