### ISSUE TITLE
Help using dlib with unity3d

### ISSUE THREAD

**Issue by tnw513** [takuya-takeuchi/DlibDotNet#30]
# Summary of your issue
I've compiled dlib as stated in the wiki but adding the dlls to the Assets/Plugins folder "doesn't work". I've tried DLLs with a simple C# program and works fine.

# Environment
Windows 10 Anniversary
Unity 2017.4.1f1 64 bit, Microsoft Visual Studio Community 2017

## Example code:

...
using DlibDotNet; // error
...

## Output:

The type or namespace name 'DlibDotNet' could not be found (are you missing a using directive or an assembly reference?)

## What did you intend to be?
How can I use your library with Unity3D? Probably it's my fault,

**Comment by takuya-takeuchi** [comment]
I have never used Unity3D.
So I have no idea to resolve issue.

DlibDotNet does not link any UnityEngine library and it may occur this issue.

**Comment by tnw513** [comment]
Thank you for your reply.

Maybe @minhkhue can help. He have opened issue #15

**Comment by takuya-takeuchi** [comment]
Actually, #15 does not relate to Unity3D.

For the beggining, I will install and touch Unity3D.
However, I can not afford the time to go through it.
And I can not promise to resolve this issue and give the advice.

**Comment by tnw513** [comment]
Thank you for your help.
If I'll success in using doin with unity I'll update this issue

**Comment by takuya-takeuchi** [comment]
You must change *Scripting Runtime Version* and *Api Compability Level*.

![2018-07-26 21 43 19](https://user-images.githubusercontent.com/6241854/43263063-2c37b3d2-911d-11e8-9e6c-454daa305539.png)

At least, the problem you faced will be vanished.

**Comment by tnw513** [comment]
Unfortunately I can't do that. It seems not stable with MixedRealityToolkit.

However thank you for your help

**Comment by valerysntx** [comment]
> Seems that .net 4.x is not stable with MixedRealityToolkit.
 could You please reference any issues related? https://github.com/Microsoft/MixedRealityToolkit-Unity

**Comment by Luuuuuuuu5b25** [comment]
Open any c# script you creat and use nuget to install. Than move the dlls from package into the asset/plugins.
Finally just using Dlibdotnet;

But unity crashed for many times when using dlibdotnet, don't ask me why I know that(

**Comment by takuya-takeuchi** [comment]
I will not use Unity and I have no motivation to resolve this issue.
