### ISSUE TITLE
DlibDotNet with FaceRecognitionDotNet Not working

### ISSUE THREAD

**Issue by Visualbench** [takuya-takeuchi/DlibDotNet#300]
# Summary of your issue
I have installed DlibDotNet (19.21.0.20220724) and FaceRecognitionDotNet (1.3.0.7) in intel i5 cpu. It works perfectly. The same code I tried to install in an intel pentium Gold it throws error

Unable to load DLL 'DlibDotNetNative': A dynamic link library (DLL) initialization routine failed. (Exception from HRESULT: 0x8007045A)

# Line throwing error
FaceRecognitionDotNet.FaceRecognition.Create(Environment.GetFolderPath(Environment.SpecialFolder.ProgramFiles) + "\\VVision\\Resources");

The Resources folder contains
dlib_face_recognition_resnet_model_v1.dat
mmod_human_face_detector.dat
shape_predictor_5_face_landmarks.dat
shape_predictor_68_face_landmarks.dat

# Call Stack of the error
   at DlibDotNet.NativeMethods.get_frontal_face_detector()
   at FaceRecognitionDotNet.FaceRecognition..ctor(String directory)
   at FaceRecognitionDotNet.FaceRecognition.Create(String directory)
   at VEnroll.MainWindow..ctor() in C:\VEnroll\VEnroll\MainWindow.xaml.cs:line 114

# Environment
Worked Environment:-
Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz   2.50 GHz
RAM :- 8 GB
Type:- 64 bit
OS:- Windows 10 22H2

Errored Environment:-
Intel(R) Pentium(R) Gold G6405 CPU @ 4.10GHz   4.10 GHz
RAM :- 8 GB
Type:- 64 bit
OS:- Windows 10 21H2

Thank you for your help.

**Comment by takuya-takeuchi** [comment]
@Visualbench 
Intel Pentium Gold G6405 does not support AVX2.
Please check https://github.com/takuya-takeuchi/DlibDotNet/issues/153
