### ISSUE TITLE
Error Loading Projects

### ISSUE THREAD

**Issue by Samehvan** [takuya-takeuchi/DlibDotNet#31]
# Summary of your issue
When loading the solution to VS 2015 it doesnt load all projects and some are unavailable 
all dlibdotnet.dll references are yellow marked creating errors in code lines

# Environment
Windows 10 64 

# What did you do when you faced the problem?
I redo everything all over again walkingthrough the wiki steps , same thing

**Comment by takuya-takeuchi** [comment]
Please refer #20.
.NET Standard 2.0 does not support VS2015.

FYI
[Ship .NET 4.6.1 support for .NET Standard 2.0 for VS 2015](https://github.com/dotnet/cli/issues/6739)

But you can use it on other projects by VS2015 after you built on VS2017 at once.

**Comment by Samehvan** [comment]
i already searched and passed through the post you mentioned , it is not my case 
i had no problems with CMake , 
as i said at the first post  too many projects unavailable like
3DPointCloud
DnnFaceRecognition
...........

and when expanding the loaded projects like
FaceLandmarkDetection.csproj

it has a yellow mark on the reference  dlibdotnet.dll

**Comment by takuya-takeuchi** [comment]
Ok, i misunderstood what you said.
I thought you are talking about only DlibDotNet project.

> as i said at the first post too many projects unavailable like


The sample projects target .NET Core 2.0.
It means that Visual Studio 2015 can not treat with them.

Yeah, I must mention about it on GitHub top page.

> it is not my case i had no problems with CMake

You compiles sample projects by CMake, right?
I have never done so.

Basically, I expect developers to do the following steps.

1. Build DlibDotNet.Natieve and DlibDotNet.Natieve.Dnn by CMake (Windows, Linux and Mac)
1. Build DlibDotNet by Visual Studio IDE (Windows only) or .NET Core SDK (Windows, Linux and Mac)
1. Execute sample projects by Visual Studio IDE (Windows only) or .NET Core SDK (Windows, Linux and Mac)

If I have any misunderstands yet, please let me know!! Thank you.
