### ISSUE TITLE
Any plans for the DlibDotNet .nuget package /s? 

### ISSUE THREAD

**Issue by valerysntx** [takuya-takeuchi/DlibDotNet#32]
Any plans for the DlibDotNet .nuget package /s? 
Or maybe there are any motivations to ignore packaging totally,
Best Regards!

**Comment by takuya-takeuchi** [comment]
It’s not like I have no motivations to do.
I have to consider the following

* Visual C++ Runtime version
* CUDA Version
* Version management

It may be difficult but I’ll give it a try.

**Comment by takuya-takeuchi** [comment]
I created 2 packages for cpu and gpu build.

* https://www.nuget.org/packages/DlibDotNet/
* https://www.nuget.org/packages/DlibDotNet-WithCUDA/

I had no time checking whether package works fine.
Please notify if you face to any problem.
