### ISSUE TITLE
Using other library as base types

### ISSUE THREAD

**Issue by AustinFelipe** [takuya-takeuchi/DlibDotNet#33]
Hey guys, how's doing?

Well, I'm wondering if is possible to use **other libraries** to deal with math instead of DlibDotNet related.

E.g: can I use Matrix from [MathDotNet library](https://numerics.mathdotnet.com/matrix.html) instead of using DlibDotNet's ```Matrix<TElement>```

Any direction on how to do it?

Thanks!

**Comment by takuya-takeuchi** [comment]
The following pseudo code

````
byte[] array = MathDotNet.ToArray();
var array2 = Dlib.LoadImageData(array);
var mat = new Matrix(array2);
````

Or

````
byte[] array = mat.ToArray();
var matrix = new MathDotNet(array);
````

Does MathDotNet.Matrix provide constructor which can accept T[] and provide interface to convert T[]?
If so, I can add Matrix.ToArray method.

**Comment by AustinFelipe** [comment]
Hey @takuya-takeuchi, thanks!

Well, it seems to have the following
```
Matrix<T> Dense<T>(int rows, int columns, T[] storage)
Matrix<T> Dense<T>(int rows, int columns, T value)
Matrix<T> DenseOfArray<T>(T[,] array)

Vector<T> Dense<T>(T[] array)
Vector<T> Dense<T>(int length, T value)
```

[Vector Creator](https://numerics.mathdotnet.com/api/MathNet.Numerics.LinearAlgebra/CreateVector.htm)
[Matrix Creator](https://numerics.mathdotnet.com/api/MathNet.Numerics.LinearAlgebra/CreateMatrix.htm)

I'm not sure if is what you're looking for. Is that something like those builders?

Thanks!
