### ISSUE TITLE
Possibility to train with DlibDotNet?

### ISSUE THREAD

**Issue by AntonioCaroppos** [takuya-takeuchi/DlibDotNet#38]
I'm looking for a way to train models with DlibDotNet because working in VS and WinForms is extremely convinient. Working with C++ is cumbersome and development time is long. 
DlibDotNet is wonderful, very convinient and easy to operate. 

Windows 10, VS 2017

I was looking for some example on how to improve an existing model (as requested here: https://github.com/davisking/dlib/issues/63)  or train a new model using DlibDotNet but I didn't find any.

It would be great if this could be added, perhaps with conversion of imglab tool to .NET.
I know it's a big wish, but I wanted to mention it anyway, I think it would be amazing for a lot of people.

**Comment by takuya-takeuchi** [comment]
Thank you for your interest in project.

As you know, dlib is huge library to support vary machine learning method.
Yes. DlibDotNet supports yet only a part of them.

But there is train model sample for dlib samples.

* https://github.com/davisking/dlib/blob/master/examples/train_object_detector.cpp
* https://github.com/davisking/dlib/blob/master/examples/train_shape_predictor_ex.cpp
* https://github.com/davisking/dlib/blob/master/examples/fhog_object_detector_ex.cpp
  * You may have to create test and train dataset as xml format

And there is few C# sample which are ported from C++ sample.

* https://github.com/takuya-takeuchi/DlibDotNet/tree/master/examples/FHogObjectDetector

Perhaps, you are interest in face objection and the above fhog_object_detector_ex and FHogObjectDetector may help you.

> It would be great if this could be added, perhaps with conversion of imglab tool to .NET.

Ah, I forgot to think about imglab.
But I glance over img source and it lets me found it is hard to port to C# code.
However, it is worth to challenge.

**Comment by takuya-takeuchi** [comment]
Ah, I'm sorry. You look for how to train existing model data, right?
I don't know how to do and I cannot find any sample C++ code in dlib repository.
If you find C++ sample, please let me know!!

**Comment by AntonioCaroppos** [comment]
> Ah, I'm sorry. You look for how to train existing model data, right?

In [this issue](https://github.com/davisking/dlib/issues/63) a user tells that open mouths are not detected correctly. I have the same issue. Therefore I want to follow Davis King's advice to use the original dataset, add new images with variations of mouths and retrain the model. I was hoping that I could do this with DLibDotNet alone.

**Comment by turowicz** [comment]
@AntonioCaroppos need to use the cpp, it's not that hard. Which OS are you on?
