### ISSUE TITLE
Implement function to convert Array2D<T> and Matrix<T> to .NET image classes

### ISSUE THREAD

**Issue by takuya-takeuchi** [takuya-takeuchi/DlibDotNet#4]
# Summary of your issue

There is no function to convert DlibDotNet.Array2D to  System.Windows.Media.Imaging.BitmapSource and System.Drawing.Bitmap.

# Environment

Windows

# What did you do when you faced the problem?

Almost developer want to treat image data in WinForms and WPF. But they can not image data from DlibDotNet.

## Example code:

```
var array = DlibDotNet.Dlib.LoadImage<RgbPixel>("test.bmp");
var bitmap = array.ToBitmapSource();
```

## Output:

N/A

## What did you intend to be?

N/A

**Comment by doczoidberg** [comment]
it should also work in the other direction

**Comment by takuya-takeuchi** [comment]
OK. Is the following code what you expect?

    var bitmap = BitmapSource.Create(width, height, dipx, dpiy, format, palette, array, stride);
    var array2D = array.ToArray2D<RgbPixel>();

**Comment by doczoidberg** [comment]
yes

**Comment by takuya-takeuchi** [comment]
Commit 44698e913c3627a53b89658736bb3230cf65acab and close

**Comment by takuya-takeuchi** [comment]
Need to support Matrix class converting

**Comment by takuya-takeuchi** [comment]
Cimmit e9d3b3383fe06adfde4ddb0ccbf0e7ce2e1e57c0 and close
