### ISSUE TITLE
Compiling error for DlibDotNet.Native.Dnn

### ISSUE THREAD

**Issue by YangLiu-Guangzhou** [takuya-takeuchi/DlibDotNet#42]
I encountered a problem while compile DlibDotNet.Native.Dnn, it turned out that the heap space reached os's limit while compiling the code loss_multiclass_log_per_pixel.cpp
# Environment
Windows 10,  16G memory, Cmake 3.12.2 and Visual Studio 2017 Community Edition 

execute the command  cmake --build . --config Release under DlibDot.Native.Dnn\build directory

CustomBuild:
  Building Custom Rule C:/code/DlibDotNet/src/DlibDotNet.Native.Dnn/CMakeLists.txt
  CMake does not need to re-run because C:/code/DlibDotNet/src/DlibDotNet.Native.Dnn/build/CMakeFiles/generate.stamp is
   up-to-date.
ClCompile:
  D:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.12.25827\bin\HostX86\x64\CL.exe /c /I"
  C:\code\dlib-19.16\dlib\.." /nologo /W3 /WX- /diagnostics:classic /O2 /Ob2 /D WIN32 /D _WINDOWS /D NDEBUG /D DLIB_HAV
  E_SSE2 /D DLIB_JPEG_SUPPORT /D DLIB_PNG_SUPPORT /D "CMAKE_INTDIR=\"Release\"" /D DlibDotNet_Native_Dnn_EXPORTS /D _WI
  NDLL /D _MBCS /Gm- /EHsc /MD /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"DlibDotNet.Native.Dnn.dir\Re
  lease\\" /Fd"DlibDotNet.Native.Dnn.dir\Release\vc141.pdb" /Gd /TP /wd4819 /errorReport:queue  /bigobj C:\code\DlibDot
  Net\src\DlibDotNet.Native.Dnn\dlib\dnn\input.cpp C:\code\DlibDotNet\src\DlibDotNet.Native.Dnn\dlib\dnn\loss\loss_metr
  ic.cpp C:\code\DlibDotNet\src\DlibDotNet.Native.Dnn\dlib\dnn\loss\loss_mmod.cpp C:\code\DlibDotNet\src\DlibDotNet.Nat
  ive.Dnn\dlib\dnn\loss\loss_multiclass_log.cpp C:\code\DlibDotNet\src\DlibDotNet.Native.Dnn\dlib\dnn\loss\loss_multicl
  ass_log_per_pixel.cpp C:\code\DlibDotNet\src\DlibDotNet.Native.Dnn\dlib\dnn\output.cpp C:\code\DlibDotNet\src\DlibDot
  Net.Native.Dnn\dlib\dnn\tensor.cpp C:\code\DlibDotNet\src\DlibDotNet.Native.Dnn\dlib\dnn\trainer.cpp
  input.cpp
  loss_metric.cpp
  loss_mmod.cpp
  loss_multiclass_log.cpp
  loss_multiclass_log_per_pixel.cpp
c:\code\dlib-19.16\dlib\dnn\core.h(912): fatal error C1060:  Compiler is out of heap space [C:\code\DlibDotNet\src\DlibDotNet.Native.Dnn\bui
ld\DlibDotNet.Native.Dnn.vcxproj]
  output.cpp
  tensor.cpp
  trainer.cpp

**Comment by YangLiu-Guangzhou** [comment]
Any comments on the compiling issue? Thanks folks!

**Comment by takuya-takeuchi** [comment]
It could be duplicate issue.

Please refer to https://github.com/takuya-takeuchi/DlibDotNet/issues/26#issuecomment-405109928

**Comment by YangLiu-Guangzhou** [comment]
Thank you takuya! Get it solved!

**Comment by zhengshuangstar** [comment]
Could any one tell me how to resovle it? I have meet the same problem in the Win7 x86 environment. Even I add the -T host x64 to the cmake command, it also occure the error "compiler is out of heap space" Thanks！

**Comment by zhengshuangstar** [comment]
Could any one tell me how to resovle it? I have meet the same problem in the Win7 x86 environment. Even I add the -T host x64 to the cmake command, it also occure the error "compiler is out of heap space" Thanks！

**Comment by takuya-takeuchi** [comment]
Dnn module requires huge memory to compile. It is not issue of DlibDotNet but dlib.
You must prepare x64 machine which has large RAM if you build it as x86.
Beucase x86 machine can not provide more than 2GB memory space to C++ compiler.

**Comment by zhengshuangstar** [comment]
Thank you very much for the reply.

I will use another x64 machine and have a try.

Best wishes.

**Comment by zhengshuangstar** [comment]
> Dnn module requires huge memory to compile. It is not issue of DlibDotNet but dlib.
> You must prepare x64 machine which has large RAM if you build it as x86.
> Beucase x86 machine can not provide more than 2GB memory space to C++ compiler.
Now in the x64 machine the build is ok.Thank you takuya!

**Comment by takuya-takeuchi** [comment]
It's my pleasure
