### ISSUE TITLE
# sample for desctop win10 vs2017 C# FW4.6

### ISSUE THREAD

**Issue by EugenyNews** [takuya-takeuchi/DlibDotNet#44]
Hello, are there any examples of using the library for desctop win10 vs2017 C# FW4.6
Thank you

**Comment by takuya-takeuchi** [comment]
DlibDotNet are built as .NET Standard 2.0 project.
It is supported by .NET Framework 4.6.1, .NET Core 2.0 and more.
If you use 4.6.0, you must upgrade to 4.6.1. Then you could able to convert all samples to .NET framework application.
https://github.com/takuya-takeuchi/DlibDotNet/tree/master/examples

Please refer the following document.
https://github.com/dotnet/standard/blob/master/docs/versions.md

**Comment by EugenyNews** [comment]
Thank you for your reply.
