### ISSUE TITLE
SEHException in DnnMmodFaceDetection example

### ISSUE THREAD

**Issue by edwinckc** [takuya-takeuchi/DlibDotNet#45]
# Summary of your issue
Hello again!
I compiled the libraries for CUDA support, and was able to run the DnnFaceRecognition fine. Using the same libraries with DnnMmodFaceDetection however, I run into an SEHException (see output below). I think I'm not the only one, since in #26, another user (postacik) mentions getting an error at this line:
`var ret = Native.loss_mmod_deserialize(str, networkType);`

It appears that when they got things working, they were using DnnFaceRecognition, but perhaps DnnMmodFaceDetection still had some problem?

I came upon this issue because I was using the built-in face detection/alignment through FaceRecognitionDotNet.

# Environment

VS2017 (15.7.4)
CMake 3.12.3
DlibDotNet 19.15.0
Tried building CUDA libs with Dlib 19.8, 19.15, and 19.16 + CUDA 9.2.
Also tried Dlib 19.8 + CUDA 9.0.
XPS15 laptop with GTX1050

# What did you do when you faced the problem?

I just tried to run the DnnFaceRecognition, DnnMmodFaceDetection, and DnnInception examples, with different combinations of CUDA/Dlib versions. Only the DnnMmodFaceDetection example kept failing.

## Example code:

```
dotnet run --configuration Release mmod_human_face_detector.dat 2007_007763.jpg
```

## Output:

```
Unhandled Exception: System.Runtime.InteropServices.SEHException: External component has thrown an exception.
   at DlibDotNet.Dnn.LossMmod.Native.loss_mmod_operator_matrixs(IntPtr obj, Int32 type, MatrixElementType element_type, IntPtr matrixs, Int32 templateRows, Int32 templateColumns, UInt64 batchSize, IntPtr& ret)
   at DlibDotNet.Dnn.LossMmod.Operator[T](IEnumerable`1 images, UInt64 batchSize) in C:\Users\edwin\Desktop\cuda test\DlibDotNet-master\src\DlibDotNet\Dnn\LossMmod.cs:line 139
   at DnnMmodFaceDetection.Program.Main(String[] args) in C:\Users\edwin\Desktop\cuda test\DlibDotNet-master\examples\DnnMmodFaceDetection\Program.cs:line 36
```

## What did you intend to be?

Probably some detected faces (I'm guessing). Thanks for your time!

**Comment by takuya-takeuchi** [comment]
Thank you for your report.
Please give me time to go through issue.

**Comment by takuya-takeuchi** [comment]
I was not be able to reproduce issue but it could be similar with.
I have 2 develop machines.

## machine 1 (Main - GTX 1080)
1. clone https://github.com/takuya-takeuchi/DlibDotNet/tree/19.15.0.20180916
1. Build DlibDotNet.Native and DlibDotNet.Native.Dnn by using MSVC 2017 x64 and CUDA
   * use cuDNN is v7.0 for CUDA 9.1 (Win10) but installed CUDA is 9.2
1. Build DnnMmodFaceDetection and run. It works.
1. The following CUDA drivers is installed
````
C:\Users\TAKUYA>set CUDA
CUDA_PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.2
CUDA_PATH_V9_0=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0
CUDA_PATH_V9_1=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.1
CUDA_PATH_V9_2=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.2
````

## machine 2 (Sub - GTX 550 Ti)
1. Copy the DnnMmodFaceDetection contains built binaries from machine 1
1. Run DnnMmodFaceDetection but It doesn't work.
````
D:\Works\OpenSource\DlibDotNet\19.15.0.20180916\examples\DnnMmodFaceDetection>dotnet run --configuration Release mmod_human_face_detector.dat 2007_007763.jpg

Unhandled Exception: System.Runtime.InteropServices.SEHException: External component has thrown an exception.
   at DlibDotNet.Dnn.LossMmod.Native.loss_mmod_deserialize(Byte[] fileName, Int32 type)
   at DlibDotNet.Dnn.LossMmod.Deserialize(String path, Int32 networkType) in D:\Works\OpenSource\DlibDotNet\19.15.0.20180916\src\DlibDotNet\Dnn\LossMmod.cs:line 65
   at DnnMmodFaceDetection.Program.Main(String[] args) in D:\Works\OpenSource\DlibDotNet\19.15.0.20180916\examples\DnnMmodFaceDetection\Program.cs:line 56
````
1. The following CUDA drivers is installed
````
C:\Users\TAKUYA>set CUDA
CUDA_PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0
CUDA_PATH_V9_0=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0
CUDA_PATH_V9_1=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.1
````

The current code may occur issue depends on CUDA and cuDNN environmental.

**Comment by takuya-takeuchi** [comment]
ah, 550Ti is not supported by CUDA 9.X.
https://en.wikipedia.org/wiki/CUDA#GPUs_supported

**Comment by takuya-takeuchi** [comment]
## machine 3 (Sub - GTX 750 Ti)
1. Copy the DnnMmodFaceDetection contains built binaries from machine 1
1. Run DnnMmodFaceDetection but It doesn't work.
````
D:\Works\OpenSource\DlibDotNet\19.15.0.20180916\examples\DnnMmodFaceDetection>dotnet run --configuration Release mmod_human_face_detector.dat 2007_007763.jpg

Unhandled Exception: System.Runtime.InteropServices.SEHException: External component has thrown an exception.
   at DlibDotNet.Dnn.LossMmod.Native.loss_mmod_deserialize(Byte[] fileName, Int32 type)
   at DlibDotNet.Dnn.LossMmod.Deserialize(String path, Int32 networkType) in D:\Works\OpenSource\DlibDotNet\19.15.0.20180916\src\DlibDotNet\Dnn\LossMmod.cs:line 65
   at DnnMmodFaceDetection.Program.Main(String[] args) in D:\Works\OpenSource\DlibDotNet\19.15.0.20180916\examples\DnnMmodFaceDetection\Program.cs:line 56
````
3. The following CUDA drivers is installed
````
D:\Works\DlibDotNet\19.15.0.20180916\examples\DnnMmodFaceDetection>set CUDA
CUDA_PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.2
CUDA_PATH_V7_5=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.5
CUDA_PATH_V8_0=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0
CUDA_PATH_V9_2=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.2
````

**Comment by takuya-takeuchi** [comment]
MmodFaceDetection requires huge memory for both cpu and gpu.
![image](https://user-images.githubusercontent.com/6241854/46581170-c24f7280-ca6e-11e8-9de4-101b103067f5.png)

It looks like MmodFaceDetection requires 5-6GB GPU memory while running.
GTX 1080 has 8GB RAM but 550 Ti and 750 Ti have few memory.
And I was able to run it by using CPU mode on machine 1 and 3. Sure, it requires huge memory too.

So program may throw exception if running machine has poor gpu board even though it got over LossMmod.Deserialize method.

Do you have GTX 1060 which has 6GB memory?
I heard that there is 2 models for GTX 1060, 3GB and 6GB.

**Comment by takuya-takeuchi** [comment]
dlib throw cuda exception if occurs error.

````cpp
// Check the return value of a call to the CUDA runtime for an error condition.
#define CHECK_CUDA(call)                                                       \
do{                                                                              \
    const cudaError_t error = call;                                            \
    if (error != cudaSuccess)                                                  \
    {                                                                          \
        std::ostringstream sout;                                               \
        sout << "Error while calling " << #call << " in file " << __FILE__ << ":" << __LINE__ << ". ";\
        sout << "code: " << error << ", reason: " << cudaGetErrorString(error);\
        throw dlib::cuda_error(sout.str());                                          \
    }                                                                          \
}while(false)

// ----------------------------------------------------------------------------------------

#ifdef __CUDACC__
````
So I may be able to handle it and notify to C# domain..

**Comment by takuya-takeuchi** [comment]
I tried to handle cuda_error. loss_mmod_deserialize says
````
Error while calling cudaGetDevice(&the_device_id) in file d:\works\lib\dlib\19.15\dlib\cuda\gpu_data.cpp:178. code: 35, reason: CUDA driver version is insufficient for CUDA runtime version
````

**Comment by takuya-takeuchi** [comment]
After install latest Nvidia driver, I was able to reproduce issues you faced.

````
Unhandled Exception: System.Runtime.InteropServices.SEHException: External component has thrown an exception.
   at DlibDotNet.Dnn.LossMmod.Native.loss_mmod_operator_matrixs(IntPtr obj, Int32 type, MatrixElementType element_type, IntPtr matrixs, Int32 templateRows, Int32 templateColumns, UInt64 batchSize, IntPtr& ret)
   at DlibDotNet.Dnn.LossMmod.Operator[T](IEnumerable`1 images, UInt64 batchSize)
   at DnnMmodFaceDetection.Program.Main(String[] args)
````

**Comment by takuya-takeuchi** [comment]
Oh, you took energy drink? Wow, do you live in japan? Or this drink is available in canada?
Please tale care of yourself. 

Just in case, please get and try latest develop branch. I added code to throw CudaException if Dnn.Operator or Deserialize method faces cuda error.
So you could be able to confirm real reason that sample crashes.

**Comment by edwinckc** [comment]
Partner is Japanese, so I have lots of Japanese things in my house haha. Feeling better after some okayu, watching QTube グランプリ now =P

I tried the latest develop branch, and I'm getting a CudaException now:

```
C:\DlibDotNet\examples\DnnMmodFaceDetection>dotnet run --configuration Debug mmod_human_face_detector.dat 2007_007763.jpg

Unhandled Exception: DlibDotNet.CudaException: Exception of type 'DlibDotNet.CudaException' was thrown.
   at DlibDotNet.Dnn.Cuda.ThrowCudaException(ErrorType error) in C:\DlibDotNet\src\DlibDotNet\Dnn\CUDA.cs:line 37
   at DlibDotNet.Dnn.LossMmod.Operator[T](IEnumerable`1 images, UInt64 batchSize) in C:\DlibDotNet\src\DlibDotNet\Dnn\LossMmod.cs:line 143
   at DlibDotNet.Dnn.LossMmod.Operator[T](Matrix`1 image, UInt64 batchSize) in C:\DlibDotNet\src\DlibDotNet\Dnn\LossMmod.cs:line 112
   at DnnMmodFaceDetection.Program.Main(String[] args) in C:\DlibDotNet\examples\DnnMmodFaceDetection\Program.cs:line 43
```

I don't see the error code you have, but it's most likely the memory error as well. Every time the GPU RAM usage reaches 2GB, the error appears. I guess there's not much I can do other than get a better GPU haha. =S Thank you very much for all your help in diagnosing the issue!

**Comment by takuya-takeuchi** [comment]
Ups, I'm sorry. I didn't override ToString method.
Please check CudaException.Code property.

>  Thank you very much for all your help in diagnosing the issue! I think the issue can be closed now, but I'll leave that up to you. m(_ _)m

Thank you, too. I'm looking forward you submit issue and request!!!
