### ISSUE TITLE
Trying to use DlibDotNet in x86 

### ISSUE THREAD

**Issue by matheusdelvalle** [takuya-takeuchi/DlibDotNet#47]
Hello!

I'm trying to use Dlib in a project with x86 Target. 
I already build DlibDotNet.dll and DlibDotNet.Native.dll , but i couldn't build the DlibDotNet.Native.Dnn.dll  :(

Do you have any ideia do help me?

**Comment by takuya-takeuchi** [comment]
Hi. Davis E. King says on http://dlib.net/compile.html
>Finally, note that when using Visual Studio, CMake will by default generate a 32bit executable. This means the programs you compile will only be able to use 2GB of RAM. To avoid this, you need to tell CMake to generate a 64bit executable.
````
cmake -G "Visual Studio 14 2015 Win64" -T host=x64 ..
````

But I guess you can use the following command to generate x86 binary.

````
cmake -G "Visual Studio 14 2015" -T host=x64 ..
````

However, I do not recommend using x86.

**Comment by kotoneme** [comment]
Could you please provide DlibDotNet.Native.Dnn.dll ? 
My computer only 6 GB free memory(throw error C1060)
Thanks.

**Comment by zlyxm** [comment]
Me too. When I build DlibDotNetNativeDnn.dll, I am prompted "The heap space of the compiler is insufficient". Can you help me?

**Comment by takuya-takeuchi** [comment]
@zlyxm 
I was succeeded to build DlibDotNetNativeDnn.dll as cpu-x86.
There is not x86 cuda binary and it means that we cannot create dlibdotnet.cudaXXX for x86 platform.

### NOTE
I use Visual Studio 15 2017.

**Comment by zlyxm** [comment]
Thank you, I have compiled successfully. It is enough to have cpu-x86. I found two places to pay attention to:
one, you need VS x64 to run compile, start menu open x64_x86 Cross Tools Command Prompt for VS 2019
`>F:\GitHub\DlibDotNet-master\src\build\DlibDotNetNativeDnn.sln`

two, the computer memory needs 32g, because the compilation takes up 28g of memory.

**Comment by takuya-takeuchi** [comment]
@zlyxm 
Thank you for your feedback.
Now, I will provide win-x86 package for CPU and MKL package.

linux-x86 and osx-x86 are not supported on dotnet.
And CUDA does not provide x86 binary. so CUDA package will not be provided.

**Comment by takuya-takeuchi** [comment]
@zlyxm 
Hi, I uploaded x86 packages.
The following packages contain x86 and x64 for windows.

* https://www.nuget.org/packages/DlibDotNet
* https://www.nuget.org/packages/DlibDotNet.MKL

Have a try!!

**Comment by zlyxm** [comment]
Good!!
