### ISSUE TITLE
How to Load Image From Stream Or SoftwareBitmap ?

### ISSUE THREAD

**Issue by zhuxb711** [takuya-takeuchi/DlibDotNet#48]
It seems that DlibDotNet could only load image from file ? However I want to know that if we could load image from Stream Or SoftwareBitmap ? Sometimes I need to process the camera frame in realtime.
Thanks a lot.

**Comment by takuya-takeuchi** [comment]
Not support to load image data from Stream.
But DlibDotNet.Extensions supports to load from Bitmap.
https://github.com/takuya-takeuchi/DlibDotNet/tree/master/src/DlibDotNet.Extensions

However, these days. I did not take care of it and it may be include issues.
If you face issue, please let me know.

**Comment by zhuxb711** [comment]
It seems that DlibDotNet.Extenstions could not be used in UWP ?

**Comment by takuya-takeuchi** [comment]
Yes.
For now, it support WinForms and WPF's Bitmap.

So you have to convert UWP writeablebitmap to byte array.

**Comment by zhuxb711** [comment]
Hi ! I make a DlibDotNet.Extenstions  by using .NET Core , However, it still don't work beacuse 
In DlibDotNet.Extenstions, the WriteableBitmap is
namespace:

"System.Windows.Media.Imaging"

But in UWP, the WriteableBitmap is 
namespace:

"Windows.UI.Xaml.Media.Imaging"

UWP could only use "Windows.UI.Xaml.Media.Imaging" rather than "System.Windows.Media.Imaging"

In short , DlibDotNet.Extentions could not convert WriteableBitmap in UWP to Array2D properly

So, How could I use Dlib to process the camera frame in UWP without save and read Image file frequently. The I/O cost too much

Thanks.

**Comment by zhuxb711** [comment]
I tried every method that I thought.
In UWP, convert WriteableBitmap(parameter name "writeableBitmap")  to byte[] (parameter name "ByteArray")

Use this method:
`Dlib.LoadImageData<RgbPixel>(ByteArray ,  writeableBitmap.PixelHeight , writeableBitmap.PixelWidth , 1)` to load image from WriteableBitmap.
Result:"No faces detected".

Then I tried to overload your methods `Dlib.LoadImage(byte [] str)`
Removed some parts of your methods such as `File.Exist()` and get byte[] from parameter `str` directly
Result: SEHException 

Oh, I don't want to do this : CameraImage->SaveImage-> `Dlib.LoadImage(string path)` LoadImage->FaceDetect


What I expect is : CameraImage->Load Image in Memory(Without Disk I/O)->FaceDetect

Please help me .Thank you very much.

**Comment by takuya-takeuchi** [comment]
How dou you convert WPF WriteableBitmap to byte[]?
If you get Array2d from WriteableBitmap, you can check whether image is valid by using ImageWindow.

And If you can, please show sample code and sample image.

**Comment by zhuxb711** [comment]
Sample Code Like this
temp is the Image that need to process
```
SoftwareBitmap temp;
WriteableBitmap wb = new WriteableBitmap(temp.PixelWidth, temp.PixelHeight);
temp.CopyToBuffer(wb.PixelBuffer);
var img = Dlib.LoadImageData<RgbPixel>(wb.ToByteArray(), (uint)wb.PixelHeight, (uint)wb.PixelWidth, 3);
ImageWindow im = new ImageWindow(img);
im.WaitUntilClosed();
```
ImageWindow show this:
![image](https://user-images.githubusercontent.com/42038175/47763571-3098f500-dcfc-11e8-94aa-52bf7ef3303f.png)


![image](https://user-images.githubusercontent.com/42038175/47763227-d481a100-dcfa-11e8-95c0-aae1a5543c77.png)
WriteableBitmapEX provide the method to convert WriteableBitmap to byte[]

Tips: WriteableBitmap in UWP is different from WPF
By the way, I'm not quite understand "steps" parameter in
`LoadImageData<T>(byte[] data, uint rows, uint columns, uint steps)`

**Comment by takuya-takeuchi** [comment]
Thank you for your good report.
I'm in office now.
please wait untill I go home and check code :)

**Comment by zhuxb711** [comment]
Here is the result
Because WriteableBitmap in UWP is RGBA8, So the Image has 4 channels 
`if (stride % 4 != 0)` Always False
And we can see the result is gray and separate
![image](https://user-images.githubusercontent.com/42038175/47865206-8ec9f300-de36-11e8-9a81-f99830eaa979.png)

Thanks for your great work, but it still need to improve
What do you think ?

**Comment by takuya-takeuchi** [comment]
Ok. I guess library may not make a correct interpretation of image.

I do not expect different type buffer is passed for type argument.

Perhaps, you convert rgba to rgb before you use LoadImageData.
It is work around.

Basically I think I should provide convert api.

**Comment by takuya-takeuchi** [comment]
FYI. I was able to reproduce issues you faced on not UWP but WinFroms. This issue is not only for UWP.

![image](https://user-images.githubusercontent.com/6241854/47914397-cdb58280-dee2-11e8-9ba8-2dbac8272e38.png)

````
using (var bitmap = new Bitmap("Lenna.png"))
{
    Console.WriteLine(bitmap.PixelFormat);

    var data = bitmap.LockBits(new System.Drawing.Rectangle(0, 0, bitmap.Width, bitmap.Height),
        System.Drawing.Imaging.ImageLockMode.ReadOnly, bitmap.PixelFormat);
    try
    {
        var array = new byte[data.Stride * data.Height];
        Marshal.Copy(data.Scan0, array, 0, array.Length);
        using (var array2D1 = Dlib.LoadImageData<RgbPixel>(array, (uint)bitmap.Height, (uint)bitmap.Width, (uint)data.Stride))
        using (var window1 = new ImageWindow(array2D1))
        using (var array2D2 = Dlib.LoadImage<RgbAlphaPixel>("Lenna.png"))
        using (var window2 = new ImageWindow(array2D2))
        {
            window1.WaitUntilClosed();
            window2.WaitUntilClosed();
        }
    }
    finally
    {
        bitmap.UnlockBits(data);
    }
}
````

**Comment by takuya-takeuchi** [comment]
Added new overload of LoadImageData. Commit is fd00056edc2cbef7815607f8bd2fdda69fb6fca6 on develop branch.

````
Array2D<T> LoadImageData<T>(ImagePixelFormat format, byte[] data, uint rows, uint columns, uint steps)
````

The format can be Bgr, Bgra, Rgb or Rgba. It means the pixel format of data argument.
So you can treat Rgba value as Rgb as the following.

````
[BGRA][BGRA[[BGRA]...
````
to

````
[RGB][RGB][RGB][RGB]...
````

And the next is sample code.

![image](https://user-images.githubusercontent.com/6241854/47919038-afa34e80-def1-11e8-8208-061b525d0334.png)

````
using (var bitmap = new Bitmap("Lenna.png"))
{
    Console.WriteLine(bitmap.PixelFormat);

    var data = bitmap.LockBits(new System.Drawing.Rectangle(0, 0, bitmap.Width, bitmap.Height),
        System.Drawing.Imaging.ImageLockMode.ReadOnly, bitmap.PixelFormat);
    try
    {
        var array = new byte[data.Stride * data.Height];
        Marshal.Copy(data.Scan0, array, 0, array.Length);
        using (var array2D1 = Dlib.LoadImageData<RgbPixel>(array, (uint)bitmap.Height, (uint)bitmap.Width, (uint)data.Stride))
        using (var window1 = new ImageWindow(array2D1))
        using (var array2D2 = Dlib.LoadImage<RgbAlphaPixel>("Lenna.png"))
        using (var window2 = new ImageWindow(array2D2))
        using (var array2D3 = Dlib.LoadImageData<RgbPixel>(ImagePixelFormat.Bgra, array, (uint)bitmap.Height, (uint)bitmap.Width, (uint)data.Stride))
        using (var window3 = new ImageWindow(array2D3))
        using (var array2D4 = Dlib.LoadImageData<RgbAlphaPixel>(ImagePixelFormat.Bgra, array, (uint)bitmap.Height, (uint)bitmap.Width, (uint)data.Stride))
        using (var window4 = new ImageWindow(array2D4))
        {
            window1.Title = "window1";
            window2.Title = "window2";
            window3.Title = "window3";
            window4.Title = "window4";
            window1.WaitUntilClosed();
            window2.WaitUntilClosed();
            window3.WaitUntilClosed();
            window4.WaitUntilClosed();
        }
    }
    finally
    {
        bitmap.UnlockBits(data);
    }
}
````

**Comment by zhuxb711** [comment]
Sorry late,
I'm very appreciate your improvment
It helps me a lot !
Thank you very much
