### ISSUE TITLE
It doesn't seem to be compatible with OpenCVSharp's face detection module.

### ISSUE THREAD

**Issue by superowner** [takuya-takeuchi/DlibDotNet#49]
# Summary of your issue
It doesn't seem to be compatible with OpenCVSharp's face detection module.
# Environment
Win10x64，OpenCVSharp 3.4.1，DlibDotNet19.15.0.20181008

# What did you do when you faced the problem?

just init OpenCVSharp CascadeClassifier and init ShapePredictor(when start to load shape_predictor_68_face_landmarks.dat)

## Example code:
        frontalface_cascade = new CascadeClassifier(Application.streamingAssetsPath + @"/haarcascades/haarcascade_frontalface_alt.xml");
        eye_cascade = new CascadeClassifier(Application.streamingAssetsPath + @"/haarcascades/haarcascade_eye_tree_eyeglasses.xml");//haarcascade_eye

 _ShapePredictor = ShapePredictor.Deserialize(@"E:\U3Dproject\OpenCVSharp\Assets\StreamingAssets" + @"\shape_predictor_68_face_landmarks.dat");

**Comment by takuya-takeuchi** [comment]
Yes. There is no compatibilitiy between dlib and opencv's face detector.

There is some reason. But the major reason is difference of feature type.

dlib uses HOG feature but opencv uses Haar Like feature.

I have never heared dlib has function to load opencv's model file.
