### ISSUE TITLE
DlibDotNet .nuget packaging enhancements

### ISSUE THREAD

**Issue by valerysntx** [takuya-takeuchi/DlibDotNet#51]
# Thank You for making #32 real
 compiling native dlib for dll's deployment is a trick that could be improved!
 Trying to figure out how different issues occur, eg.
 https://github.com/takuya-takeuchi/DlibDotNet/issues/50#issuecomment-440692454,  let check that feeling of 'broken' package here?

Could You please check .nuspec [https://github.com/valerysntx/DlibDotNet.Nuget](https://github.com/valerysntx/DlibDotNet.Nuget )I propose to discuss

**Comment by takuya-takeuchi** [comment]
Thank you for your great proposal!!
I want to confirm some points.

1. Why do you name runtime directory as 'win10-x64'? DlibDotNet does not limit to use only Win10. I think that ’windows’ is better.
1. You changed DlibDotNet.nuspec looks like the following. What does it mean?
````diff
- <group targetFramework="netstandard2.0" />
+ <group targetFramework=".NETStandard2.0" />
````
1. You changed DlibDotNet.nuspec looks like the following. What does it mean?
````diff
+ <group targetFramework="native0.0" />
````

I'm sure your proposal is helpful!!!

**Comment by valerysntx** [comment]
- Your nuget package is targeted both for `.native` and `.netstandard2.0`, that's why having two dependencies groups
- `native0.0 moniker is compatible with `native`, I beleive, 
- the sources I've used for native, - https://docs.microsoft.com/en-us/nuget/create-packages/native-packages
- Currently it seems implementing 'native' isn't needed, but it needs for for proper https://docs.microsoft.com/en-us/nuget/create-packages/supporting-multiple-target-frameworks spec. implementation

Please investigate the package, with fixes I've made, uploaded, to myget:
[https://www.myget.org/feed/nuget-dotnet/package/nuget/DlibDotNet](https://www.myget.org/feed/nuget-dotnet/package/nuget/DlibDotNet)

**Comment by takuya-takeuchi** [comment]
Fantastic!!! Thank you for your kindly contribution!!

Ok. I agree with your improvement.
Could you create PR?
I want to add your contribution to development history.

**Comment by valerysntx** [comment]
okay, so You wan't me to make changes for /nuget folder?
