### ISSUE TITLE
I Get  An  error   ‘pyramid_type’ is not a class   in  Linux Arm 32bit 

### ISSUE THREAD

**Issue by haojielyb** [takuya-takeuchi/DlibDotNet#52]
I  build  in linux but get  an error 
 /DlibDotNet.Native/dlib/image_transforms/image_pyramid.h:110:14: error: ‘pyramid_type’ is not a class, namespace, or enumeration

I  do'nt know C++   so Can you help me

**Comment by takuya-takeuchi** [comment]
Could you tell me the followings?

* dlib version
* compiler version
* build os
  * I may be able to reproduce your issue by using docker

**Comment by haojielyb** [comment]
thank you  for help 

my dlib version  I tryed   19.8  19.8  19.16   and got the  same  error 
cmake version  is  3.51
make version is GNU Make 4.1
OS is  Ubuntu 16.04.2 LTS  

and thank you again

**Comment by takuya-takeuchi** [comment]
ok. I'll check.
but i have not arm device running ubuntu.
so I will use hyper-v.

Thank you for your cooperations.

**Comment by haojielyb** [comment]
I get the same  error   on   CentOS Linux release 7.4.1708 (Core)  64 bit
dlib version is 19.9 
cmake 3.6.2
make  3.8.2

mybe I take some misstake  but  I don't know where is it

**Comment by takuya-takeuchi** [comment]
hi, everyone.
I confirmed the build error on linux machine. It was not same error message.
But I could resolve issue if fix this error.

Just now, I am in business trip and it is difficult to concentrate development. so sorry.
Please give me time to resolve.

**Comment by haojielyb** [comment]
I  enabled C++11 then this error not happend agin but   get anohter error   can you tell me what is need

**Comment by takuya-takeuchi** [comment]
Hi everyone. I'm very sorry to delay response.
I fixed build error for Linux.
Just in case, I confirmed whether build works fine for Native and Native.Dnn on the following environmentals.

* Ubuntu 16.04.5
* CentOS 7.5
* Windows 10 Ver1803
* MacOSX 10.14

Give it a try!!
https://github.com/takuya-takeuchi/DlibDotNet/tree/develop
