### ISSUE TITLE
Unable to load image

### ISSUE THREAD

**Issue by trittsv** [takuya-takeuchi/DlibDotNet#58]
### Code
`var img = Dlib.LoadImage<RgbPixel>("D:\\Bibliothek\\Bilder\\IMG_3385.jpg");`

### Error
System.BadImageFormatException
  HResult=0x8007000B
  Message=Es wurde versucht, eine Datei mit einem falschen Format zu laden. (Ausnahme von HRESULT: 0x8007000B)
  Source=DlibDotNet
  StackTrace:
   at DlibDotNet.Dlib.Native.array2d_new(Array2DType type)
   at DlibDotNet.Array2D`1..ctor()
   at DlibDotNet.Dlib.LoadImage[T](String path)
   at ConsoleApp1.Program.Main(String[] args) in C:\Users\Sven Trittler\Desktop\ConsoleApp1\ConsoleApp1\Program.cs:line 197

## Environment
* DlibDotNet 19.15.0.20181008
* Windows 10 Education
* Microsoft Visual Studio Community 2017 
* VisualStudio.15.Release/15.9.4+28307.222
* Microsoft .NET Framework Version 4.7.03056
* C# Tools   2.10.0-beta2-63501-03+b9fb1610c87cccc8ceb74a770dba261a58e39c4a

**Comment by takuya-takeuchi** [comment]
Your application is built as x86 but DlibDotNet.Native is as x64.
Please check your application build configuration.
