### ISSUE TITLE
dlls dependencies

### ISSUE THREAD

**Issue by doczoidberg** [takuya-takeuchi/DlibDotNet#6]
I try to transfer my app (facelandmark) to run on another pc than my dev machine.
```
Unhandled Exception: System.DllNotFoundException: Unable to load DLL 'DlibDotNet.Native.dll': Modul was not found. (Exception from HRESULT: 0x8007007E)
   at DlibDotNet.ImageWindow.Native.image_window_new()

```
the dlls are there? Do I need dlib dlls? or additional .NET installs?

**Comment by doczoidberg** [comment]
I needed to install ,NET core 1.1 runtime packages frome here. I thought core 2 runtime would be enough but this was not the case.

**Comment by Azizgaamouz** [comment]
Hi doczoidberg
did you find a way to fix the exception ? i run into the same error...
Any idea ?

**Comment by doczoidberg** [comment]
yes, Just read my last message?!

**Comment by Azizgaamouz** [comment]
Hi again
I'm getting a headhack to understand what's happened. I really appreciate if you can help...
Just have a look on this image when you have a moment:
https://user-images.githubusercontent.com/36734999/36944886-c6647f1e-1f9c-11e8-8357-e6859fed105c.png
thanks a lot
Aziz

**Comment by Azizgaamouz** [comment]
Hi
I'm using dotnet core 2.0, windows 8.1 and visual studio 2017... for informations if usefull
Thanks again

**Comment by doczoidberg** [comment]
> I needed to install ,NET core 1.1 runtime packages
