### ISSUE TITLE
Nuget do not copy DlibDotNet.Native libraries to bin directory

### ISSUE THREAD

**Issue by takuya-takeuchi** [takuya-takeuchi/DlibDotNet#61]
# Summary of your issue

Native libraries are not copied to bin directory.

# Environment

Windows 10
.NET Framework 4.7.2

# What did you do when you faced the problem?

Add reference of DlibDotNet.Native and build project.
But DlibDotNet.Native.dll and DlibDotNet.Native.Dnn.dll are not copied to bin directory.

**Comment by valerysntx** [comment]
@takuya-takeuchi
Fixed with https://github.com/valerysntx/DlibDotNet/commit/ad671efb9c547bd4dd538ffe138333a775bef742

**Comment by valerysntx** [comment]
@takuya-takeuchi, please review: https://github.com/takuya-takeuchi/DlibDotNet/pull/65

**Comment by takuya-takeuchi** [comment]
@valerysntx 

I already reported on https://github.com/takuya-takeuchi/DlibDotNet/pull/66.
.NET Framework is ok but .NET core is bad.
My result produced opposite result.

> they are mapped using deps.json which points to relative paths from local NuGet cache
I tried OpenCVSharp about this.
Native binary is not copieed to when use dotnet build and run.
But all libraries are copied to publish directory after use **dotnet publish**.
Sure. .NET Framework is no problem.

In conclusion, we need not to worry about deployment when use @valerysntx nuget package.

**Comment by takuya-takeuchi** [comment]
@valerysntx 

You uploaded DlibDotNet.Native to https://www.nuget.org/packages/DlibDotNet.Native.
Will you be responsible for management it?

**Comment by takuya-takeuchi** [comment]
Close.

**Comment by valerysntx** [comment]
> @valerysntx
> 
> You uploaded DlibDotNet.Native to https://www.nuget.org/packages/DlibDotNet.Native.
> Will you be responsible for management it?

I will keep myget sources to keep the history of  #66 consistent. 
Also, I will not promote to list any of above onto nuget. 
I've made you an owner of https://www.nuget.org/packages/DlibDotNet.Native, so You decide if it should be removed (now its' jut unlisted)

**Comment by takuya-takeuchi** [comment]
Either way, we must prepare package for cpu and cuda and only 'DlibDotNet.Native' cannot satisfy it.
So I need not to use this repo.

I would not have been able to complete cross platform support without your help.
Thank you for your great contirbutions.
