### ISSUE TITLE
Bitmap.tomatrix () and dlib. LoadImageAsMatrix(" tom_cruise_avp_2014_4.jpg ")

### ISSUE THREAD

**Issue by TrojanOlx** [takuya-takeuchi/DlibDotNet#67]
Var img = Dlib. LoadImageAsMatrix (" Tom_Cruise_avp_2014_4. JPG ");
The detector. The Operator (img);
You can detect faces

But I use
Var img = bitmap. ToMatrix < RgbPixel > ()
The detector. The Operator (img);
No face detected

**Comment by takuya-takeuchi** [comment]
Thank you for reporting. And I'm verry sorry to delay response.

Yes, it is library bug. I fixed it on 995e079380b9445f64a75c49c872b968f2584f1a.

**Comment by TrojanOlx** [comment]
> 谢谢你的报道。而且我很遗憾地推迟回复。
> 
> 是的，它是库bug。我把它固定在[995e079上](https://github.com/takuya-takeuchi/DlibDotNet/commit/995e079380b9445f64a75c49c872b968f2584f1a)。

**Comment by takuya-takeuchi** [comment]
Why did you reopen? Does it relate with #68?

**Comment by TrojanOlx** [comment]
> Why did you reopen? Does it relate with #68?
I'm not very familiar with using github, which was accidentally opened。
