### ISSUE TITLE
PNG images,   bitmap. ToArray2D (); There is an error

### ISSUE THREAD

**Issue by TrojanOlx** [takuya-takeuchi/DlibDotNet#68]
Hi, I'm back to asking questions.

Using (var stream = new FileStream(filePath, filemode.openorcreate))
{
Await the file. CopyToAsync (stream);
Stream. Flush ();
Bitmap = new Bitmap(stream);
Bitmaps. The Add (bitmap);
}

var img = bitmap. ToArray2D ();
Image format is PNG,
Bitmap.toarray2D () , error: "Specified method is not supported."

It is good to use the following methods
var img = Dlib. LoadImage (" PNG. PNG ")

**Comment by TrojanOlx** [comment]
> 请给我时间通过!! 谢谢！！
Okay

**Comment by takuya-takeuchi** [comment]
Question.
Did you specify RgbAlphaPixel as type argument for ToArray?
If you pass 24Rgb bitmap and try to convert Array2D<RgbAlphaPixel>, it will fail.
If you want to use Array2D<RgbAlphaPixel>, you must pass 32bppArgb bitmap.

**Comment by TrojanOlx** [comment]
> Question.
> Did you specify RgbAlphaPixel as type argument for ToArray?
> If you pass 24Rgb bitmap and try to convert Array2D, it will fail.
> If you want to use Array2D, you must pass 32bppArgb bitmap.

using (var img = bitmap.ToArray2D<RgbAlphaPixel>())
{
     dets = detector.Operator(img);
}

error: Input RgbAlphaPixel is not supported.

**Comment by takuya-takeuchi** [comment]
OK. It is not bug of DlibDotNet but it is specification of dlib.
FaceDetector does not support image with alphachannel.

**Comment by TrojanOlx** [comment]
I know that Dlib does not support PNG images,
But Dlib.LoadImage<RgbPixel>("png. PNG ") can be read;
I was confused

**Comment by takuya-takeuchi** [comment]
I guess current dlib support png image without any passing flag when build.
Therefore, DlibDotNet removed DLIB_PNG_SUPPORT flag from CMakeLists.txt.

By the way, did you resolve issue?

**Comment by TrojanOlx** [comment]
This is a problem with Dlib. I think I can save the image locally and then load the path.Thank you very much.
