### ISSUE TITLE
Build guide or nuget?

### ISSUE THREAD

**Issue by akade** [takuya-takeuchi/DlibDotNet#7]
Do you have a short build guide?

I have a few problems with building it:
* class "dlib::random_cropper" has no member "get_min_object_size"	[...]\DlibDotNet\src\DlibDotNet.Native\dlib\image_transforms\random_cropper.h	85	
* 'dlib::random_cropper::set_min_object_size': function does not take 1 arguments[...]\dlibdotnet\src\dlibdotnet.native\dlib\image_transforms\random_cropper.h	119	
* it also took me a while to figure out where to place the built dlib library
* against which version of dlib did you write your wrapper?

Another, even cooler option would be having a Nuget package.

-----
That said/asked, it looks really well-done and I would love to use it and maybe even contribute.

**Comment by takuya-takeuchi** [comment]
Hi akade.
I provide wiki. https://github.com/takuya-takeuchi/DlibDotNet/wiki
Could you go through document?

**Comment by akade** [comment]
Thanks, I'm really sorry that I missed it! I figured it out myself yesterday night though. The compile errors still happen but I changed the signatures of all the wrapper functions...

By the way, Visual Studio now has native CMake support, if you fix the conditions in the CMake file, you can open the folder in Visual Studio and build from there. 

Also I will later try if I can get it running for Xamarin and if you'd want I can update you how and if it works. Interested?
