### ISSUE TITLE
Linux break build

### ISSUE THREAD

**Issue by turowicz** [takuya-takeuchi/DlibDotNet#71]
This new line breaks the build

https://github.com/takuya-takeuchi/DlibDotNet/blob/30cc5396bc7490d8919d18898b543b6aca7f80d3/src/DlibDotNet.Native/CMakeLists.txt#L94

```
CMake Error at CMakeLists.txt:94 (include):
  include could not find load file:

    /DlibDotNet/src/DlibDotNet.Native/build/dlib_build/config/dlibConfig.cmake
```

**Comment by turowicz** [comment]
cc @takuya-takeuchi

**Comment by valerysntx** [comment]
https://github.com/takuya-takeuchi/DlibDotNet/blob/30cc5396bc7490d8919d18898b543b6aca7f80d3/src/DlibDotNet.Native/CMakeLists.txt#L54

put the original dlib sourcetree into `./src/dlib` folder via `git submodule` command
_I beleive I'm spelling it properly :)_
` git submodule update --init --remote --reference https://github.com/davisking/dlib -- src`

**Comment by takuya-takeuchi** [comment]
I'm sorry for my late response.

I agree with your proposal.

@valerysntx 
I checked dlib repository. But I did not see 19.16.99.20190105 branch.
I will use dlib offiial release revision. So I do NOT use 19.16.99.20190105 even though it exists.

P.S.
The 19.17 release day is close?

**Comment by takuya-takeuchi** [comment]
I merged #72. But 

https://github.com/takuya-takeuchi/DlibDotNet/blob/30cc5396bc7490d8919d18898b543b6aca7f80d3/src/DlibDotNet.Native/CMakeLists.txt#L94

occurs cmake error.

I guess this line is not necessary. Is it corret?

**Comment by Kirbyrawr** [comment]
That line gives an error also in OSX, removing it fix the issue.

**Comment by takuya-takeuchi** [comment]
Fixed.
Confirmed on Win(CPU/CUDA), Ubuntu(CPU/CUDA) and Mac(CPU).
