### ISSUE TITLE
Release for 19.16

### ISSUE THREAD

**Issue by takuya-takeuchi** [takuya-takeuchi/DlibDotNet#74]
19.16 is very important release because nuget package support cross platform (Thanks @valerysntx)
I worry about developer face to deployment issue after release 19.16.

### Windows

- [x] nuget package MUST work fine 
   - [ ]  ~~For .NET Framework, DlibDotNet, DlibDotNet.Native and DlibDotNet.Native.Dnn are copied to output directory after build~~
   - [x]  For .NET Core application, DlibDotNet, DlibDotNet.Native and DlibDotNet.Native.Dnn are copied to output directory after publish
   - [x]  For .NET Core application, application can run by dotnet run command by using nuget package w/o manual library deployement

### Mac and Linux

- [x] nuget package MUST work fine 
   - [x]  For .NET Core application, DlibDotNet, DlibDotNet.Native and DlibDotNet.Native.Dnn are copied to output directory after publish
   - [x]  For .NET Core application, application can run by dotnet run command by using nuget package w/o manual library deployement

**Comment by TrojanOlx** [comment]
Has this version been released yet?
Why I can't get it in Nuget.
