### ISSUE TITLE
The image read from sqlite (BLOB) turns green

### ISSUE THREAD

**Issue by Arqenza** [takuya-takeuchi/DlibDotNet#75]
When you display the image of rgbpixel output from dlib (C ++) to sqlite with ImageWindow of DlibDotNet, the image becomes green.
Displaying this image from sqlite in dlib (C ++) will display it correctly.

Please tell me if you have any solution tips on this situation.

# Environment
 Windows7 SP1
 DlibDotNet 19.15
 dlib 19.16
 .Net 4.6.1

# Detailed explanation
## Step1:[dlib(C++) Insert]
Step 1 inserts images into sqlite with dlib (C ++).
The result is no problem.
```
int imageno = 1;
array2d<rgb_pixel> image;
Testdb.exec("create table TestFace (imageno integer PRIMARY KEY, image blob)");
statement st1(Testdb, "insert into TestFace VALUES(?,?)");)
load_image(image, "bruce1.bmp");
st1.bind(1, imageno);
st1.bind(2, image);
st1.exec();
```

## Step2:[dlib(C++) Show]
Step 2 displays the image of sqlite inserted with dlib (C ++).
The result is no problem.
```
int imageno;
array2d<rgb_pixel> image;
statement st1(Facedb, "select * from TestFace");
st.move_next();
st.get_column(0, imageno);
st.get_column(1, image);
image_window faceWin;
faceWin.set_image(image);
```
[Normal image](https://drive.google.com/file/d/1WY6IhUDHtUUgNa4_qrWCIHej4VRwoc-N/view?usp=sharing)

## Step3:[DlibDotNet(C#) Show]
Step 3 displays the image which is dull in ImageWindow of DlibDotNet.
The displayed image is changing to green.
I am very confused.
```
string sql = "select * from TestFace";
SQLiteCommand com = new SQLiteCommand(sql, con);
SQLiteDataReader sdr = com.ExecuteReader();
sdr.Read();
var array2D1 = Dlib.LoadImageData<RgbPixel>((byte[])sdr["image"], 150, 150, 450);
var myWindow = new ImageWindow(array2D1, "Bruce Image");
```
[Abnormal image](https://drive.google.com/file/d/1OBJuJf43pjsSN5cX_Of7OuiiNWmUEIcj/view?usp=sharing)

I am deeply grateful for DlibDotNet.
Thank you.

**Comment by takuya-takeuchi** [comment]
I gonna check above code.

## SQLiteDataReader

I found that (byte[])sdr["image"].Length is invalid.
5 byte is added to head of (byte[])sdr["image"].

## Dlib.LoadImageData<RgbPixel>(byte[])

This method treat that byte[] is

````
BGRBGRBGR....
````

But (byte[])sdr["image"] returns RGBRGBRGB actually. So Blue and Red will be swapped in LoadImageData.

However, this behavior may be neither not bad.
Because, pixel data of bitmap file lines BGRBGRBGR. So If developer access System.Drawing.Bitmap pixel data and convert to byte[], LoadImageData can convert it to Array2d<RgbPixel>.

**Comment by takuya-takeuchi** [comment]
## Answer

````
var array2D1 = Dlib.LoadImageData<RgbPixel>(ImagePixelFormat.Rgb, (byte[])sdr["image"], 150, 150, 450);
````

## Future

1. Implement sqlite to DlibDotNet
1. Implement Array2D<RgbPixel>.Deserialize(byte[])
   * st1.bind(2, image) is serialize process, so this approach is better.

**Comment by Arqenza** [comment]
Thank you for your early reply.
I could not solve it without your help.
I am very grateful.
