### ISSUE TITLE
Android and iOS libraries

### ISSUE THREAD

**Issue by Kirbyrawr** [takuya-takeuchi/DlibDotNet#76]
# Summary of your issue
Hi there, it's possible to compile Android and iOS libraries for the wrapper?

# Environment
Android, iOS

**Comment by takuya-takeuchi** [comment]
It could be ok. But I have never try it.

TBH, your requirements is not DlibDotNet issue.
Because Androdi and iOS device require arm binary. So it means that it requires to be able to compile dlib as arm assembly.

But I have never hear dlib can be compiled as arm.

**Comment by Kirbyrawr** [comment]
Actually i know that it's possible since i saw in other places where they use it inside Unity for example, i have succesfully ran this on Unity on OSX but now i'm going to try to compile the iOS and Android.
I asked just in case you knew anything about it.

Thanks!!

**Comment by takuya-takeuchi** [comment]
I have no time to consider it.
