### ISSUE TITLE
MSBuild cannot detect MacOSX

### ISSUE THREAD

**Issue by takuya-takeuchi** [takuya-takeuchi/DlibDotNet#77]
# Summary of your issue

In build/DlibDotNet.Native.props, $(OS) does not work on MacOSX.
https://github.com/Microsoft/msbuild/pull/538

It does not occur errror.
Because *.so and *.dylib will be copied porperly.
But *.so files are extra and it consumes disk space.

# Environment

On MacOSX.

**Comment by valerysntx** [comment]
Consider using `$([MSBuild]::IsOsPlatform("osx")))` put into `Condition=` attribute, like 


```
 <PropertyGroup>
    <OsEnvironment Condition="$([MSBuild]::IsOSPlatform('windows'))">windows</OsEnvironment>
    <OsEnvironment Condition="$([MSBuild]::IsOSPlatform('linux'))">linux</OsEnvironment>
    <OsEnvironment Condition="$([MSBuild]::IsOSPlatform('osx'))">osx</OsEnvironment>

    <OsUnixLike>false</OsUnixLike>
    <OsUnixLike Condition="$([MSBuild]::IsOsUnixLike())">true</OsUnixLike>

```
taken from [Directory.Build.props](https://github.com/Microsoft/msbuild/blob/b8c6ea84bd0e0710691cf47f83fd3ce36b03a71a/Directory.Build.props#L13) in [Microsoft/msbuild](https://github.com/Microsoft/msbuild/) repo 


Also, here is much longer version, found around

       '$([System.Runtime.InteropServices.RuntimeInformation]::IsOSPlatform(
                    $([System.Runtime.InteropServices.OSPlatform]::OSX))
        )'

**Comment by takuya-takeuchi** [comment]
Close by e096e965d498a67ca4d11e0b9995126c50f81745
