### ISSUE TITLE
Dlibdotnet-withcuda 19.16.0.20190115 is not compatible with NETCoreApp 2.0 (.netcoreapp,Version=v2.0).The package dlibdotnet-withcuda 19.16.0.20190115 does not support any target framework.DnnFaceRecognition

### ISSUE THREAD

**Issue by TrojanOlx** [takuya-takeuchi/DlibDotNet#78]
After installing DlibDotnet 19.16.0.20190115, I tried to install dlibdotnet-withcuda 19.16.0.20190115 and the following error occurred:

Dlibdotnet-withcuda 19.16.0.20190115 is not compatible with NETCoreApp 2.0 (.netcoreapp,Version=v2.0).The package dlibdotnet-withcuda 19.16.0.20190115 does not support any target framework.DnnFaceRecognition

**Comment by takuya-takeuchi** [comment]
all right. I was able to reproduce issue. please give me time to check.

**Comment by TrojanOlx** [comment]
Thank you, this problem has been solved, but I found a new one.
When I updated the version to 19.16.0.20190119,
Var.net = DlibDotNet. Within Dnn. LossMetric. Deserialize (" dlib_face_recognition_resnet_model_v1. Dat ")

This line of code has the following error.

8. Name of the class: 8 to load DLL 'DlibDotNetNativeDnn' or one of its dependencies: 8 to find the named module.(the Exception from HRESULT: 0 x8007007e)

I wonder if this is a problem with Cmake C++ Dlib.

**Comment by takuya-takeuchi** [comment]
Thank you for reporting and I'm sorry to trouble you again.
DlibDotNetNativeDnn depends on cudnn library.

![image](https://user-images.githubusercontent.com/6241854/51540475-e1490780-1e99-11e9-9e12-c259459f0db6.png)

Could you check whether there are CuBLAS64_92.dll and CuDNN64_7.dll in you machine?

I was not able to reproduce your issue. But I faced another issue.

````cmd
dotnet run -c Release "D:\Works\Lib\DLib\19.9\examples\faces\bald_guys.jpg"
D:\Works\OpenSource\Temp\DnnFaceRecognition\Properties\launchSettings.json からの起動設定を使用中...

Unhandled Exception: System.EntryPointNotFoundException: Unable to find an entry point named 'cstd_memcpy' in DLL 'DlibDotNetNative'.
   at DlibDotNet.NativeMethods.cstd_memcpy(IntPtr dest, IntPtr src, Int32 count)
   at DlibDotNet.Interop.InteropHelper.Copy(IntPtr ptrSource, UInt32[] dest, UInt32 elements)
   at DlibDotNet.StdVector`1.StdVectorUInt32Imp.ToArray(IntPtr ptr)
   at DlibDotNet.Dlib.ChineseWhispers(IEnumerable`1 edges, UInt32 iterations, UInt32& clusters, UInt32[]& labels)
   at DnnFaceRecognition.Program.Main(String[] args) in D:\Works\OpenSource\Temp\DnnFaceRecognition\Program.cs:line 93
````

Please do not hesitate to contact us if you need any further information.
