### ISSUE TITLE
Txt file of float to matrix<float> 

### ISSUE THREAD

**Issue by omarkacem** [takuya-takeuchi/DlibDotNet#81]
# Summary of your issue
hi , how can i pass a txt file of face_Descriptors of person to List<matrix<float>>
# Environment

Write your environment.

# What did you do when you faced the problem?

//write here
face_Descriptors of person:
## Example code:
-0.0728652
0.125478
0.0771245
-0.0323962
-0.0760731
-0.0236171
-0.0220402
-0.0322135
0.146855
-0.0788332
0.144657
0.0332424
-0.175483
0.11879
-0.133859
0.0716011
-0.173214
-0.0573085
-0.160498
-0.112159
0.00628921
0.107657
-0.0416287
-0.0062419
-0.0745062
-0.245731
-0.019343
-0.0376715
0.171376
-0.100312
0.0269609
0.00802182
-0.203221
-0.0295105
-0.0304787
-0.0137016
-0.0202408
-0.0276844
0.232657
0.0716619
-0.183852
0.109678
0.0347387
0.336639
0.178102
0.052335
-0.0407937
-0.0418292
0.0726556
-0.270274
0.0771214
0.196706
0.110542
0.0882336
0.0372529
-0.197185
0.0351236
0.0761103
-0.158683
0.113021
0.123702
-0.0209622
0.0345114
-0.00968692
0.135747
0.0394064
-0.100659
-0.102901
0.0712848
-0.216823
0.007498
0.0324899
-0.0330862
-0.131566
-0.227976
0.094208
0.371431
0.229263
-0.163305
0.0219972
-0.0804735
-0.059611
0.122126
0.0553043
-0.132317
-0.0506794
-0.0486051
0.0198884
0.15738
0.0752635
-0.0521619
0.210796
0.0431191
-0.0791324
-0.0222362
0.0483826
-0.198013
-0.0338433
-0.0743503
0.00268906
0.0201779
-0.0871436
-0.00506844
0.164835
-0.20545
0.239726
-0.0466641
-0.0290071
0.0416153
0.0974849
-0.0544099
-0.0443341
0.169994
-0.160148
0.216269
0.198078
-0.00143639
0.121161
0.112145
0.0737676
0.00544236
0.0969032
-0.132508
-0.144602
-0.0259586
-0.105246
0.0821894
0.039851

```
paste your core code
```

## Output:

```
paste your output
```

**Comment by takuya-takeuchi** [comment]
You can cast above txt to float[] and pass it to Matrix(TElement[] array, int row, int column).

**Comment by omarkacem** [comment]
Many thanks, I have just tested and works perfectly!!!
I could not solve it without your help.
I am very grateful.
