### ISSUE TITLE
 Unable to load DLL "DlibDotNet.Native.dll" 

### ISSUE THREAD

**Issue by CROSP** [takuya-takeuchi/DlibDotNet#82]
# Summary of your issue

I get errors whenever I try to run my web applicaton. 
The first error that I got is

> Unable to load DLL "DlibDotNet.Native.dll" The specified module could not be found. (Exception from HRESULT: 0x8007007E)

This error is was thrown only when accessing specific endpoints related to this library 

![image](https://user-images.githubusercontent.com/5072318/52477350-38ddb780-2baa-11e9-88a3-189e98de9551.png)

The second error I got after clearing cache and updating packages is 

> "Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information."

![2019-02-08_13-42-22](https://user-images.githubusercontent.com/5072318/52477611-3b8cdc80-2bab-11e9-9769-619a257f3698.png)

# Environment

Windows 10 x64. 

Target Framework -     `<TargetFrameworkVersion>v4.6.1</TargetFrameworkVersion>`

```
<packages>
  <package id="DlibDotNet" version="19.16.0.20190122" targetFramework="net461" />
  <package id="DlibDotNet-WithCUDA" version="19.16.0.20190122" targetFramework="net461" />
  <package id="FaceRecognitionDotNet" version="1.2.3.5" targetFramework="net461" />
  <package id="FaceRecognitionDotNet-WithCUDA" version="1.2.3.5" targetFramework="net461" />
  <package id="Microsoft.NETCore.Platforms" version="1.1.0" targetFramework="net46" />
  <package id="Microsoft.Win32.Primitives" version="4.3.0" targetFramework="net46" />
  <package id="System.AppContext" version="4.3.0" targetFramework="net46" />
  <package id="System.Console" version="4.3.0" targetFramework="net46" />
  <package id="System.Globalization.Calendars" version="4.3.0" targetFramework="net46" />
  <package id="System.IO.Compression" version="4.3.0" targetFramework="net46" />
  <package id="System.IO.Compression.ZipFile" version="4.3.0" targetFramework="net46" />
  <package id="System.IO.FileSystem" version="4.3.0" targetFramework="net46" />
  <package id="System.IO.FileSystem.Primitives" version="4.3.0" targetFramework="net46" />
  <package id="System.Net.Http" version="4.3.2" targetFramework="net46" />
  <package id="System.Net.Sockets" version="4.3.0" targetFramework="net46" />
  <package id="System.Runtime.InteropServices.RuntimeInformation" version="4.3.0" targetFramework="net46" />
  <package id="System.Security.Cryptography.Algorithms" version="4.3.0" targetFramework="net46" />
  <package id="System.Security.Cryptography.Encoding" version="4.3.0" targetFramework="net46" />
  <package id="System.Security.Cryptography.Primitives" version="4.3.0" targetFramework="net46" />
  <package id="System.Security.Cryptography.X509Certificates" version="4.3.0" targetFramework="net46" />
  <package id="System.Xml.ReaderWriter" version="4.3.0" targetFramework="net46" />
</packages>
```

# What did you do when you faced the problem?

We changed nothing in our configuration related to this package this problem suddenly appeared. Only deployment servers were updated, but the issue is reproducable on a local machine as well.

## What have you tried?

All DLLs (including `DlibDotNet.Native.Dll`) are present in the `bin` directory. 

I have tried to inspection `DlibDotNet.Native.Dll` using [https://github.com/lucasg/Dependencies](Dependencies) and didn't find any missing dependencies.

![image](https://user-images.githubusercontent.com/5072318/52477794-e8fff000-2bab-11e9-8ef6-6e5253cd71b5.png)

What could cause these problems and how can I deal with them?

Thanks.

**Comment by takuya-takeuchi** [comment]
````
  <package id="DlibDotNet" version="19.16.0.20190122" targetFramework="net461" />
  <package id="DlibDotNet-WithCUDA" version="19.16.0.20190122" targetFramework="net461" />
  <package id="FaceRecognitionDotNet" version="1.2.3.5" targetFramework="net461" />
  <package id="FaceRecognitionDotNet-WithCUDA" version="1.2.3.5" targetFramework="net461" />
````

You need not to refer both DlibDotNet and DlibDotNet-WithCUDA. Sure, Both FaceRecognitionDotNet and FaceRecognitionDotNet-WithCUDA are needed not to be refered.
At first, please remove either no-cuda or withcuda.

I guess DlibDotNet.Native.Dnn.dll will be replaced by one dependents cuda libs due to referring WithCUDA.

**Comment by CROSP** [comment]
@takuya-takeuchi  Thank you for your response!

I have tried to take your suggestions and currenlty my `package.config` has the following content.

```
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="DlibDotNet" version="19.16.0.20190122" targetFramework="net461" />
  <package id="FaceRecognitionDotNet" version="1.2.3.8" targetFramework="net461" />
  <package id="Microsoft.NETCore.Platforms" version="1.1.0" targetFramework="net46" />
  <package id="Microsoft.Win32.Primitives" version="4.3.0" targetFramework="net46" />
  <package id="System.AppContext" version="4.3.0" targetFramework="net46" />
  <package id="System.Console" version="4.3.0" targetFramework="net46" />
  <package id="System.Globalization.Calendars" version="4.3.0" targetFramework="net46" />
  <package id="System.IO.Compression" version="4.3.0" targetFramework="net46" />
  <package id="System.IO.Compression.ZipFile" version="4.3.0" targetFramework="net46" />
  <package id="System.IO.FileSystem" version="4.3.0" targetFramework="net46" />
  <package id="System.IO.FileSystem.Primitives" version="4.3.0" targetFramework="net46" />
  <package id="System.Net.Http" version="4.3.2" targetFramework="net46" />
  <package id="System.Net.Sockets" version="4.3.0" targetFramework="net46" />
  <package id="System.Runtime.InteropServices.RuntimeInformation" version="4.3.0" targetFramework="net46" />
  <package id="System.Security.Cryptography.Algorithms" version="4.3.0" targetFramework="net46" />
  <package id="System.Security.Cryptography.Encoding" version="4.3.0" targetFramework="net46" />
  <package id="System.Security.Cryptography.Primitives" version="4.3.0" targetFramework="net46" />
  <package id="System.Security.Cryptography.X509Certificates" version="4.3.0" targetFramework="net46" />
  <package id="System.Xml.ReaderWriter" version="4.3.0" targetFramework="net46" />
</packages>
```

But I still get an error when trying to load the `FaceRecognition` dependency.

![image](https://user-images.githubusercontent.com/5072318/52519130-836d3b80-2c5f-11e9-8e7e-d68e94cdc07e.png)

What else could be wrong?

**Comment by takuya-takeuchi** [comment]
[#82.zip](https://github.com/takuya-takeuchi/DlibDotNet/files/2847752/82.zip)

I created test program and tested it for .NET 4.6.1 and .NET Core.
They works fine.

````csharp
using System;
using System.Linq;
using FaceRecognitionDotNet;

namespace Test
{

    internal class Program
    {

        private static void Main()
        {
            // load FaceRecognitionDotNet.dll. But no error happens even though this statements are removed.
            var fr = typeof(FaceRecognition);
            Console.WriteLine(fr.FullName);

            // No outputs if there is not above statements.
            var types = AppDomain.CurrentDomain.GetAssemblies().SelectMany(item => item.GetTypes());
            foreach (var type in types.Where(t => t.FullName != null && t.FullName.StartsWith("FaceRecognitionDotNet")))
                Console.WriteLine(type.FullName);
        }
    }

}
````

At least, AppDomain.CurrentDomain.GetAssemblies() and GetTypes() did not throw exception.

However,  ReflectionTypeLoadException was thrown if DlibDotNet.dll was deleted from bin directory.

````
ハンドルされていない例外: System.Reflection.ReflectionTypeLoadException: 要求された型のうち 1 つまたは複数を読み込めませんでした。詳細については、LoaderExceptions プロパティを取得してください。
   場所 System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   場所 System.Reflection.RuntimeModule.GetTypes()
   場所 System.Reflection.Assembly.GetTypes()
   場所 Test.Program.<>c.<Main>b__0_0(Assembly item) 場所 D:\Works\OpenSource\Temp\DlibDotNet\#82\4.6.1\Test\Program.cs:行 18
   場所 System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   場所 System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   場所 Test.Program.Main() 場所 D:\Works\OpenSource\Temp\DlibDotNet\#82\4.6.1\Test\Program.cs:行 19
````

Could you check whether FaceRecognitionDotNet.dll. DlibDotNet.dll, DlibDotNet.Native.dll and DlibDotNet.Native.Dnn.dll exist in same directory?

**Comment by CROSP** [comment]
@takuya-takeuchi  thank you so much for your time testing this configuration. However, I have tried to remove everything from the `bin` directory and rebuild project again and all `dlls` seem to be there 

![image](https://user-images.githubusercontent.com/5072318/52521686-7c582480-2c83-11e9-87ce-0796eddcc990.png)

Except this one `DlibDotNet.dll`.

If there is anything I can try to find the problem?

**Comment by takuya-takeuchi** [comment]
No. There is not **DlibDotNet.dll**.
DlibDotNet nuget package is consist of DlibDotNet.dll. DlibDotNetNative.dll and DlibDotNetNativeDnn.dll.
I can not see **DlibDotNet.dll** in your picture.

**Comment by CROSP** [comment]
@takuya-takeuchi  thank you,

I have removed dependencies from nuget and reinstalled them, now I get all dlls in the bin directory, however whenever I try to access an endpoint it throws an error 

`System.DllNotFoundException: 'Unable to load DLL 'DlibDotNetNativeDnn': The specified module could not be found. (Exception from HRESULT: 0x8007007E)'`

![image](https://user-images.githubusercontent.com/5072318/52539684-d6dba880-2d89-11e9-82f7-104c5e7d7bf4.png)

I don't have any ideas what could be wrong with this

**Comment by takuya-takeuchi** [comment]
![2019-02-11 07 25 51](https://user-images.githubusercontent.com/6241854/52540564-4d9a9500-2dce-11e9-9059-a95ba6122064.png)

Could you check the property of DlibDotNetNativeDnn.dll?
I think your DlibDotNetNativeDnn.dll expects the machine has gpu and cuda installation.

If you will not use CUDA, please install FaceRecognitionDotNet rather than FaceRecognitionDotNet-WithCUDA.
If you want to use CUDA, download cuDNN7 dlls and deploy them into application directory.

**Comment by CROSP** [comment]
@takuya-takeuchi 
Thank you for answer.

I have just checked and it is 

![image](https://user-images.githubusercontent.com/5072318/52548378-087a6100-2dd6-11e9-9c4e-17be3ed2ac1b.png)

However I installed a simple version without `CUDA`.

Here are my dependencies.

```
  <package id="DlibDotNet" version="19.16.0.20190119" targetFramework="net461" />
  <package id="FaceRecognitionDotNet" version="1.2.3.8" targetFramework="net461" />
```

And another project in the solution 

```
  <package id="DlibDotNet" version="19.16.0.20190119" targetFramework="net461" />
  <package id="FaceRecognitionDotNet" version="1.2.3.8" targetFramework="net461" />
```

It seems that it took invalid DLLs from the Nuget Package Manager?

**Comment by takuya-takeuchi** [comment]
I'm very sorry.
I found that nuget 19.16.0.20190119 package contains wrong binary.
So I must update FaceRecognitionDotNet to link DlibDotNet 19.16.0.20190122.

Could you try the following binary?

[DlibDotNet.19.16.0.20190122.zip](https://github.com/takuya-takeuchi/DlibDotNet/files/2850014/DlibDotNet.19.16.0.20190122.zip)

You can only unzip and deploy including binaries to application folder for now.
If it works then I will create new package.

Thank you for your cooperation.

**Comment by CROSP** [comment]
@takuya-takeuchi 

Many thanks, I have just tested and works perfectly!!!
Everything is fine. 

Could you please update the library in the Nuget Package Manager repository?

Thanks again for your time and assistance!

**Comment by takuya-takeuchi** [comment]
you're welcome and I'm sorry to waste your precious development time :(

OK. I'll upload latest nuget package. It does not any modification except for link binary.

**Comment by takuya-takeuchi** [comment]
I updated packages. It may be indexing now.
https://www.nuget.org/packages/FaceRecognitionDotNet/1.2.3.9

**Comment by CROSP** [comment]
@takuya-takeuchi  please don't appologize. I am really grateful for your time and help. 
Thank you so much for such a great library, a lot of work was done.
