### ISSUE TITLE
Problem with model created by dnn_mmod_ex.cpp

### ISSUE THREAD

**Issue by turowicz** [takuya-takeuchi/DlibDotNet#85]
Hey @takuya-takeuchi

I'm having trouble using a model that I've trained using the [`dnn_mmod_ex.cpp`](http://dlib.net/dnn_mmod_ex.cpp.html) example. I tried deserializing it into `DlibDotNet.Dnn.LossMmod.Deserialize` but I get a padding error that most likely relates to the wrong DNN architecture that was used for training vs. what I'm trying to load that in to.

Can you point me towards reading that `.dat` file into DlibDotNet? 

cc @davisking

**Comment by turowicz** [comment]
It is my understanding that the network architecture from MMOD example is not present in DlibDotNet here: https://github.com/takuya-takeuchi/DlibDotNet/blob/00f8f71834fd4239f2d5c9bc072aa02efaa1a39f/src/DlibDotNet.Native.Dnn/dlib/dnn/loss/loss_mmod.h#L18

**Comment by turowicz** [comment]
@takuya-takeuchi is it OK if I add a network type 2 as a copy paste from mmod example?

**Comment by turowicz** [comment]
Tested the PR, the MMOD example now works.

**Comment by takuya-takeuchi** [comment]
Push dnn_mmod_ex example by b51b7acd6f1ecc83c14e64cea0aaa07708549c85
