### ISSUE TITLE
Exception in WebcamFacePose sample

### ISSUE THREAD

**Issue by jmtaijiquan** [takuya-takeuchi/DlibDotNet#87]
# Summary of your issue
The sample code of WebcamFacePose throws exception randomly. 
# Environment

Windows .NET 4.6.1

# What did you do when you faced the problem?

Run the application for multiple times and the application will throw exceptions randomly: "Attempted to read or write protected memory. This is often an indication that other memory is corrupt."

## What did you intend to be?
I modified the code with data type "Byte" for method call Dlib.LoadImageData<Byte>(). The application seems working fine now.

**Comment by takuya-takeuchi** [comment]
perhaps, temp Mat is 8bit channel sent from webcam.
sample code does not take care of channel value.

But I never seen 8 bit channel webcam.
Is it IR camera?

**Comment by jmtaijiquan** [comment]
I am using Logitech C920.

**Comment by jmtaijiquan** [comment]
Oops... I still see the same exception randomly on the same line of code. This method is called by another thread. 

        private List<Bitmap> DetectFacesWithDlib(Bitmap image)
        {
            List<Bitmap> detectedFaces = new List<Bitmap>();

            // Create Mat from image
            using (Mat srcImage = OpenCvSharp.Extensions.BitmapConverter.ToMat(image))
            using (Mat grayImage = new Mat())
            {
                // Convert to gray image
                Cv2.CvtColor(srcImage, grayImage, ColorConversionCodes.BGRA2GRAY);
                Cv2.EqualizeHist(grayImage, grayImage);

                // Turn OpenCV's Mat into something dlib can deal with.  Note that this just
                // wraps the Mat object, it doesn't copy anything. 
                var array = new byte[grayImage.Width * grayImage.Height * grayImage.ElemSize()];
                Marshal.Copy(grayImage.Data, array, 0, array.Length);
                using (var cimg = Dlib.LoadImageData<Byte>(array, (uint)grayImage.Height, (uint)grayImage.Width, (uint)(grayImage.Width * grayImage.ElemSize())))
                {
                    // Detect faces 
                    var faces = _faceDetector.Operator(cimg);

**Comment by takuya-takeuchi** [comment]
@jmtaijiquan I run WebcamFacePose once again for 10 min.
But it works fine. Sure, I didn't change any code.
Does issue you reported first use DetectFacesWithDlib method?

Could you show me all source code occur problem if you can?
