### ISSUE TITLE
How do I build and use the library with all the dependencies?

### ISSUE THREAD

**Issue by deepakkumar1984** [takuya-takeuchi/DlibDotNet#9]
Please provide with some list of steps on how to build the dependencies and then use the C# native version.

**Comment by takuya-takeuchi** [comment]
I assume you use Windows. Please refer https://github.com/takuya-takeuchi/DlibDotNet/wiki/Tutorial-for-Windows

**Comment by deepakkumar1984** [comment]
Thanks mate! I will give a try :)
