### ISSUE TITLE
OSX build error with Nuget

### ISSUE THREAD

**Issue by turowicz** [takuya-takeuchi/DlibDotNet#90]
Hey @takuya-takeuchi 

Small error, on OSX and Linux you may have incorrect file names when you copy the native libraries to build output folder.

On OSX, you include in the nuget package:
- libDlibDotNetNative.dylib
- libDlibDotNetNativeDnn.dylib

But during build you try to copy without the `lib` part. Unix systems have lib appended automatically.

``` 
/usr/local/share/dotnet/sdk/2.2.100/Microsoft.Common.CurrentVersion.targets(4365,5): error MSB3030: Could not copy the file "/Users/wojtek/.nuget/packages/dlibdotnet/19.16.0.20190313/build/../runtimes/osx-x64/native/DlibDotNetNativeDnn.dylib" because it was not found. [/Users/wojtek/Workspace/People.Backend/src/People.Console/People.Console.csproj]
/usr/local/share/dotnet/sdk/2.2.100/Microsoft.Common.CurrentVersion.targets(4365,5): error MSB3030: Could not copy the file "/Users/wojtek/.nuget/packages/dlibdotnet/19.16.0.20190313/build/../runtimes/osx-x64/native/DlibDotNetNative.dylib" because it was not found. [/Users/wojtek/Workspace/People.Backend/src/People.Console/People.Console.csproj]
```

**Comment by turowicz** [comment]
@takuya-takeuchi please also check if FaceRecognitionDotNet doesn't have a similar problem.

**Comment by turowicz** [comment]
@takuya-takeuchi looking at the CUDA nuget definition, osx is commented out?

**Comment by takuya-takeuchi** [comment]
@turowicz you are correct. thank you for your report!!

>looking at the CUDA nuget definition, osx is commented out?

Because I have no osx machine with gpu. so i am not able to test.

**Comment by turowicz** [comment]
Thanks @takuya-takeuchi !

**Comment by turowicz** [comment]
@takuya-takeuchi seems like this is still an issue with latest Nuget `19.16.0.20190313`.

I'll stay with a manual build then.

**Comment by takuya-takeuchi** [comment]
This issue could be fixed on 21th March. Unfortunately, 19.16.0.20190313 does not include this fix.

**Comment by turowicz** [comment]
Thanks
