### ISSUE TITLE
Add Label to rectangle overlay

### ISSUE THREAD

**Issue by Nekromancer** [takuya-takeuchi/DlibDotNet#94]
Have you considered adding label to rectangle overlay? I found this function in dlib documentation
```
void add_overlay(
            const rectangle& r, 
            pixel_type p, 
            const std::string& l
        );
```

Would it be hard to implement? As far as i can tell - usage of std::string is the biggest problem here:
https://github.com/davisking/dlib/blob/6b581d91f6b9b847a8163420630ef947e7cc88db/dlib/gui_widgets/widgets_abstract.h#L2951

**Comment by takuya-takeuchi** [comment]
ok. give a bit time to implenent.

**Comment by takuya-takeuchi** [comment]
I pushed the code to latest develop branch

````csharp
        public void AddOverlay(Rectangle rect, byte color, string str)
        public void AddOverlay(Rectangle rect, double color, string str)
        public void AddOverlay(Rectangle rect, float color, string str)
        public void AddOverlay(Rectangle rect, HsiPixel color, string str)
        public void AddOverlay(Rectangle rect, int color, string str)
        public void AddOverlay(Rectangle rect, RgbAlphaPixel color, string str)
        public void AddOverlay(Rectangle rect, RgbPixel color, string str)
        public void AddOverlay(Rectangle rect, sbyte color, string str)
        public void AddOverlay(Rectangle rect, short color, string str)
        public void AddOverlay(Rectangle rect, string str)
        public void AddOverlay(Rectangle rect, uint color, string str)
        public void AddOverlay(Rectangle rect, ushort color, string str)
````

**Comment by Nekromancer** [comment]
That's great! Are you planning on releasing NuGet version anytime soon?

**Comment by takuya-takeuchi** [comment]
Now I'm working on 19.17 release.
But I may be able to release as prerelease version   if you hope.

**Comment by Nekromancer** [comment]
That would be awsome, thanks in advance

**Comment by takuya-takeuchi** [comment]
Shortly, pre-release nuget package will be shown on nuget.

https://www.nuget.org/packages/DlibDotNet/19.17.0.20190408-pre
https://www.nuget.org/packages/DlibDotNet-WithCUDA/19.17.0.20190408-pre

There could have unexpected error but it contains what you hope. Have a try!!!

**Comment by Nekromancer** [comment]
Thanks, works like a charm :)
