### ISSUE TITLE
Unable to find an entry point named 'dnn_cuda_cudaDriverGetVersion' in shared library 'DlibDotNetNativeDnn'.

### ISSUE THREAD

**Issue by turowicz** [takuya-takeuchi/DlibDotNet#95]
Hey @takuya-takeuchi 

I'm trying to update to `19.16.0.20190313`.

Unfortunately I'm getting the following error on Ubuntu 18.04:

```
System.EntryPointNotFoundException: Unable to find an entry point named 'dnn_cuda_cudaDriverGetVersion' in shared library 'DlibDotNetNativeDnn'.
   at DlibDotNet.NativeMethods.dnn_cuda_cudaDriverGetVersion(Int32& version)
   at DlibDotNet.Dnn.Cuda.ThrowCudaException(ErrorType error)
   at DlibDotNet.Dnn.LossMmod.Operator[T](IEnumerable`1 images, UInt64 batchSize)
   at DlibDotNet.Dnn.LossMmod.Operator[T](Matrix`1 image, UInt64 batchSize)
   at FaceRecognitionDotNet.Dlib.Python.CnnFaceDetectionModelV1.Detect(LossMmod net, Image image, Int32 upsampleNumTimes)
   at FaceRecognitionDotNet.FaceRecognition.FaceLocations(Image image, Int32 numberOfTimesToUpsample, Model model)+MoveNext()


         8:     /usr/local/lib/libDlibDotNetNativeDnn.so: error: symbol lookup error: undefined symbol: dnn_cuda_cudaDriverGetVersion (fatal)
         8:     /usr/local/lib/libDlibDotNetNativeDnn.so: error: symbol lookup error: undefined symbol: dnn_cuda_cudaDriverGetVersionA (fatal)
```

**Comment by turowicz** [comment]
How I install dlib `.so` files:

```
# Install Dlib
WORKDIR /
ENV CUDA_PATH=/usr/local/cuda
RUN apt-get install -y libopenblas-dev liblapack-dev
RUN git clone --recurse-submodules -j8 --single-branch -b '19.16.0.20190313' https://github.com/takuya-takeuchi/DlibDotNet.git

WORKDIR /DlibDotNet/src/DlibDotNet.Native/build
RUN cmake ..
RUN cmake --build . --config Release
RUN cp /DlibDotNet/src/DlibDotNet.Native/build/libDlibDotNetNative.so /usr/local/lib

WORKDIR /DlibDotNet/src/DlibDotNet.Native.Dnn/build
RUN cmake ..
RUN cmake --build . --config Release
RUN cp /DlibDotNet/src/DlibDotNet.Native.Dnn/build/libDlibDotNetNativeDnn.so /usr/local/lib
```

How I install the `DlibDotNet.dll` and `FaceRecognitionDotNet.dll` files:

```
WORKDIR /

RUN git clone --single-branch -b '19.16.0.20190313' https://github.com/takuya-takeuchi/DlibDotNet.git
RUN cd DlibDotNet/src/DlibDotNet && dotnet restore
RUN cd DlibDotNet/src/DlibDotNet && dotnet msbuild -p:Configuration=ReleaseLinux

RUN git clone --recurse-submodules -j8 --single-branch -b 'master' https://github.com/takuya-takeuchi/FaceRecognitionDotNet.git
RUN cd FaceRecognitionDotNet/src/FaceRecognitionDotNet && dotnet restore
RUN cd FaceRecognitionDotNet/src/FaceRecognitionDotNet && dotnet msbuild -p:Configuration=Release
```

**Comment by turowicz** [comment]
I guess `FaceRecognitionDotNet` also needs upgrading to `19.16.0.20190313 `?

**Comment by takuya-takeuchi** [comment]
I'm very sorry to trouble you.
This issue is resolved on latest develop branch 40b6913c7dd829970e8b487e4198242d10d0f560

> I guess FaceRecognitionDotNet also needs upgrading to 19.16.0.20190313?

No. This modification was fixed after 13th March.
I will release DlibDotNet 19.17 at this month. And then, this issue should be removed!!

**Comment by turowicz** [comment]
Thank you very much @takuya-takeuchi, I will try `develop`!

**Comment by turowicz** [comment]
@takuya-takeuchi do you know the last release that this error wasn't in? I'm having trouble reverting back - I used to work of old master and now I can't figure out which commit that was.

**Comment by takuya-takeuchi** [comment]
If 'last release' means nuget package, there is no pacakge hasn't this error.
I guess this error was embeded since first commit of cuda function. So all released package has potential to occur this issue.

**Comment by turowicz** [comment]
It did work for me at some point but I lost the compiled binary file. I'm now going back release-by-release trying to get a working build. It was somewhere around 14th of January.

Building 15th of Jan release gives me the following error:

```
[ 99%] Building CXX object CMakeFiles/DlibDotNetNative.dir/dlib/svm/structural_object_detection_trainer/scan_fhog_pyramid.cpp.o
[100%] Linking CXX shared library libDlibDotNetNative.so
/usr/bin/ld: cannot find -lcudart_static
collect2: error: ld returned 1 exit status
CMakeFiles/DlibDotNetNative.dir/build.make:1285: recipe for target 'libDlibDotNetNative.so' failed
make[2]: *** [libDlibDotNetNative.so] Error 1
CMakeFiles/Makefile2:72: recipe for target 'CMakeFiles/DlibDotNetNative.dir/all' failed
make[1]: *** [CMakeFiles/DlibDotNetNative.dir/all] Error 2
make: *** [all] Error 2
Makefile:105: recipe for target 'all' failed
The command '/bin/sh -c cmake --build . --config Release' returned a non-zero code: 2
```

**Comment by turowicz** [comment]
@takuya-takeuchi do you perhaps know what this error means?

**Comment by takuya-takeuchi** [comment]
I removed the reference of cudart_static on 30th Jan d75679c8ce7cb948c7b34c4fb2de093519b24a9.
Because DlibDotNet and dlib did not require it.

But cmakelists.txt cotains what requires cudart_static and then cmake try to link it to compiled binary.
I guess your linux system does not contain proper env variable.
If you use libcudart_static.a. you must add /usr/local/cuda.....

**Comment by turowicz** [comment]
thanks!

**Comment by turowicz** [comment]
I do have the env var but the `lib` folder is called `lib64` in my CUDA 10.

I'll try to figure out a workaround.

**Comment by takuya-takeuchi** [comment]
FYI. I never try to use CUDA 10 on linux. So I may not give any helpful advice.

**Comment by turowicz** [comment]
No problem. Its funny because it all used to work perfectly a week ago. I messed up my versioning and lost the binaries.

**Comment by turowicz** [comment]
@takuya-takeuchi it looks like I'm getting this error because I'm running TensorFlowSharp in my application... When I disable TensorFlowSharp the error disappears.

Any ideas what might be happening? I have other libs that use GPU, like OpenCV and they never caused any trouble.

I added TensorFlowSharp last week.

**Comment by turowicz** [comment]
I don't get why a TF# addition would cause this:

```
/usr/local/lib/libDlibDotNetNativeDnn.so: error: symbol lookup error: undefined symbol: dnn_cuda_cudaDriverGetVersion (fatal)
```

**Comment by turowicz** [comment]
@takuya-takeuchi do you have any ideas why using another library would cause the problem?

**Comment by takuya-takeuchi** [comment]
Is it build error or runtime error?

### runtime error

When running application, does application links proper library?
I guess there is wrong DlibDotNetNativeDnn.so in anywhere.
It was linked to your application when TF# is enabled for strange reason.

### build error

Could you check the exported function of libDlibDotNetNativeDnn.so by nm command?
You must check whether dnn_cuda_cudaDriverGetVersion is.

**Comment by turowicz** [comment]
Its runtime.

So I swapped the execution around... and it started to work.

Before - throws dnn error:

```
DoTensorFlow();
DoDlib();
```

After - works fine:

```
DoDlib();
DoTensorFlow();
```

**Comment by turowicz** [comment]
I will try multiple threads with this workload to rule out any problems

**Comment by turowicz** [comment]
I also reverted `DlibDotNetNativeDnn.so` to the one from production server, where we don't have TF, and the problem is the same

**Comment by turowicz** [comment]
I actually reverted everything to the version from production server, TF is somehow messing up.

**Comment by turowicz** [comment]
Could it be GPU access?

**Comment by takuya-takeuchi** [comment]
> Could it be GPU access?

DlibDotNetNativeDnn uses GPU. so it is yes.

By the way, you built old DlibDotNetNativeDnn? I’m getting confused.
If so, this error should remain. 
On old one, runtime try to throw exeception when DlibDotNetNativeDnn faces CUDA error, but function is missing due to wrong name.

**Comment by turowicz** [comment]
I copied old `DlibDotNetNativeDnn.so` from a production server that is running without TF#.

Both new and old `DlibDotNetNativeDnn.so` throw this error when TF is enabled. When I disable TF I don't get the error on both new and old `DlibDotNetNativeDnn.so`.

**Comment by takuya-takeuchi** [comment]
New is not latest develop build, right?
I think this error is cuda memory error.

TF and dlib uses huge GPU memory.
If using TF first, TF cosumes most of GPU memory.
Then dlib try to use GPU memory, but CUDA can not allocate and notify error to dlib.
In this time, old and new (not latest develop build) failed to handle exception due to wrong p/invoke definition.

If using dlib first, dlib cosumes most of GPU memory.
Next, maybe TF fails to run. but TF handle CUDA error well.

**Comment by turowicz** [comment]
"New" is latest release tag from March.

I'm looking at the memory now.

**Comment by turowicz** [comment]
Interestingly tensorflow seems to be working fine even when Dlib is crashing out.

**Comment by turowicz** [comment]
I've added more RAM and the process is stable. Testing further.

**Comment by turowicz** [comment]
Seems like the problem is a mixture of 2 causes
- `DlibDotNetNativeDnn` error when GPU runs out of RAM
- Process Killed when system runs out of RAM

**Comment by turowicz** [comment]
I need a bigger GPU, closing the issue for now.

**Comment by takuya-takeuchi** [comment]
FYI, I release DlibDotNet 19.17.20190408-pre.
It fixed the p/invoke error and it can handle cuda error well.

**Comment by turowicz** [comment]
Thank you @takuya-takeuchi  - you're the best!

**Comment by turowicz** [comment]
@takuya-takeuchi which commit is the p/invoke error handling for `19.17.20190408-pre` on?

**Comment by turowicz** [comment]
@takuya-takeuchi can you tell me which commit handles the cuda error better so I can catch it?

**Comment by turowicz** [comment]
OK I've got it. Thanks for fixing the OSX build :)

**Comment by turowicz** [comment]
@takuya-takeuchi the problem was caused 100% by TensorFlow. By default TF takes all GPU RAM. 

Fixed by doing this:

https://github.com/migueldeicaza/TensorFlowSharp/issues/206
