### ISSUE TITLE
Not using CUDA

### ISSUE THREAD

**Issue by utarn** [takuya-takeuchi/DlibDotNet#96]
# Summary of your issue
I installed Dlibdotnet-cuda and facerecognitiondotnet-cuda from nuget to my Visual studio project. I also included necessary library files. The application runs without any errors. I investigated that it does not use any CUDA at all. Both with-cuda and without-cuda, takes the same processing time.

# Environment
Windows 10
Visual Studio 2019
Winform Project
Target x64

# What did you do when you faced the problem?

Through the package requires CUDA library files, it takes the same speed as cpu does.

## Example code:

```
paste your core code
```

## Output:

```
paste your output
```

**Comment by takuya-takeuchi** [comment]
Thank you for your reporting issue.
Could you tell me how to determine library does not use cuda?

**Comment by takuya-takeuchi** [comment]
Same speed as cpu. It means that your GPU does not use any memory, right?

**Comment by utarn** [comment]
Yes. As I am monitoring, cuda usage is 0% and there is memory consumption on gpu while the cpu is 100% for 1 core and RAM usage spikes.

**Comment by takuya-takeuchi** [comment]
Very weird.
I copied https://github.com/takuya-takeuchi/DlibDotNet/tree/master/examples/DnnFaceRecognition and modify to let it use nuget package and run.

It works fine and consume gpu memory (a little!!) on cuda pacakge. On cpu package, it did not consume gpu memory and took much time.

Could you try the following zip file?
You only download *.dat and jpg file and run bat file.
[DnnFaceRecognition.zip](https://github.com/takuya-takeuchi/DlibDotNet/files/3125067/DnnFaceRecognition.zip)

**Comment by takuya-takeuchi** [comment]
FYI.
My dev env has GTX 1080 and installs CUDA 9.2.
CUDA_PATH specifies 9.2

**Comment by utarn** [comment]
I got  this error.
```
Unhandled Exception: System.DllNotFoundException: Unable to load DLL 'DlibDotNetNativeDnn': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at DlibDotNet.NativeMethods.loss_metric_deserialize(Byte[] fileName, Int32 type, IntPtr& net)
   at DlibDotNet.Dnn.LossMetric.Deserialize(String path, Int32 networkType)
   at DnnFaceRecognition.Program.Main(String[] args) in D:\Downloads\DnnFaceRecognition\Program.cs:line 31
```

I also copy DlibDotNetNativeDnn.dll to D:\Downloads\DnnFaceRecognition\ and D:\Downloads\DnnFaceRecognition\bin\Release\netcoreapp2.0  but it shows the same.

FYI. I tried FaceRecognitionDotNet-WithCUDA. My GPU is GTX1080.
```
   public static void Run()
        {
            var obamaUrl1 = "https://upload.wikimedia.org/wikipedia/commons/3/3f";
            var obamaFile1 = "Barack_Obama_addresses_LULAC_7-8-08.JPG";
            var obamaUrl2 = "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/President_Barack_Obama.jpg";
            var obamaFile2 = "480px-President_Barack_Obama.jpg";
            var ImageDirectory = @"g:\\sampleface";
            var path1 = Path.Combine(ImageDirectory, obamaFile1);
            using (var faceRecognition = FaceRecognition.Create(@"g:\\facedata"))
            {
                if (!File.Exists(path1))
                {
                    var url = $"{obamaUrl1}/{obamaFile1}";
                    var binary = new HttpClient().GetByteArrayAsync(url).Result;

                    Directory.CreateDirectory(ImageDirectory);
                    File.WriteAllBytes(path1, binary);
                }

                var path2 = Path.Combine(ImageDirectory, obamaFile2);
                if (!File.Exists(path2))
                {
                    var url = $"{obamaUrl2}/{obamaFile2}";
                    var binary = new HttpClient().GetByteArrayAsync(url).Result;

                    Directory.CreateDirectory(ImageDirectory);
                    File.WriteAllBytes(path2, binary);
                }

                bool atLeast1Time = false;
                Stopwatch sw = new Stopwatch();
                using (var image1 = FaceRecognition.LoadImageFile(path1))
                using (var image2 = FaceRecognition.LoadImageFile(path2))
                {
                    sw.Start();
                    var endodings1 = faceRecognition.FaceEncodings(image1).ToArray();
                    var endodings2 = faceRecognition.FaceEncodings(image2).ToArray();
                    sw.Stop();
                    var t1 = sw.ElapsedMilliseconds;
                    var testJson = JsonConvert.SerializeObject(endodings1);
                    sw.Restart();
                    foreach (var encoding in endodings1)
                        foreach (var compareFace in FaceRecognition.CompareFaces(endodings2, encoding))
                        {
                            atLeast1Time = true;
                        }
                    sw.Stop();
                    var t2 = sw.ElapsedMilliseconds;
                    foreach (var encoding in endodings1)
                        encoding.Dispose();
                    foreach (var encoding in endodings2)
                        encoding.Dispose();
                    MessageBox.Show($"Process {t1} ms. Match {t2} ms.");
                }
            }
              

        }
```
I got the same performance here. t1 is 7 - 9 seconds. t2 is 3 ms.

**Comment by takuya-takeuchi** [comment]
Ok. I was able to reproduce your problem. And I can understand.
This is not issue.

Could you change the above code to the folloing code?

````
sw.Start();
var endodings1 = faceRecognition.FaceEncodings(image1).ToArray();
sw.Restart();
var endodings2 = faceRecognition.FaceEncodings(image2).ToArray();
sw.Stop();
````

First time of FaceEncodings is very slow. I guess initial running execute allocation memory and more.
So 2nd time should work fine.

## FYI

The followings are part of Benchmark sample.
And CUDA and Python sample consume about only 0.4GB GPU memory.

### CPU

````
Timings at 240p:
 - Face locations: 0.0572s (17.48 fps)
 - Face landmarks: 0.0014s (714.29 fps)
 - Encode face (inc. landmarks): 0.2684s (3.73 fps)
 - End-to-end: 0.3262s (3.07 fps)
````

### CUDA

````
Timings at 240p:
 - Face locations: 0.0574s (17.42 fps)
 - Face landmarks: 0.0014s (714.29 fps)
 - Encode face (inc. landmarks): 0.0040s (250.00 fps)
 - End-to-end: 0.0620s (16.13 fps)
````

### Python-CUDA (original face_recognition)

````
Timings at 240p:
 - Face locations: 0.0514s (19.46 fps)
 - Face landmarks: 0.0020s (509.74 fps)
 - Encode face (inc. landmarks): 0.0052s (192.03 fps)
 - End-to-end: 0.0571s (17.51 fps)
````

**Comment by utarn** [comment]
Thank you for you fast reply. I just know it's an issue.

**Comment by atabora1** [comment]
@takuya-takeuchi Hope all is well and that you are staying safe. Question. I'm running the benchmark example. Comparing the performance of Cuda (10.0) vs non Cuda nuget libraries I'm not seeing an improvement. I know Cuda is installed correctly because I was able to  run the Nvidia examples. Is there anything else I have to do besides include the nuget cuda version of facialrecognition? Your feedback would be appreciated. 

Using GTX 1050


NO CUDA

Timings at 240p:obama-240p.jpg
 - Face locations: 2.3846s (0.42 fps)
 - Face landmarks: 2.2594s (0.44 fps)
 - Encode face (inc. landmarks): 2.8420s (0.35 fps)
 - End-to-end: 2.9074s (0.34 fps)
 
 
 
 CUDA 10.0
 
Timings at 240p:obama-240p.jpg
Received this error message
DllNotFoundException: Unable to load DLL 'DlibDotNetNativeDnn': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
so I also installed the DlibDotNet Nuget package. Installing this package resolved the error above.
 
 
 - Face locations: 2.3452s (0.43 fps)
 - Face landmarks: 2.2798s (0.44 fps)
 - Encode face (inc. landmarks): 2.8062s (0.36 fps)
 - End-to-end: 2.8766s (0.35 fps)

**Comment by takuya-takeuchi** [comment]
@utarn 
Did you install DlibDotNet.CUDA100 instead of DlibDotNet?
And are you talking about FaceRecognitionDotNet?
If so, you must install FaceRecognitionDotNet.CUDA100 instead of FaceRecognitionDotNet.

You can check whether system or DlibDotNet support cuda by this code.

````
using DlibDotNet;

if (Cuda.TryGetDriverVersion(out var driver))
{
     Console.WriteLine(driver);
}
if (Cuda.TryGetRuntimeVersion(out var runtime))
{
     Console.WriteLine(runtime);
}
````

**Comment by atabora1** [comment]
Thanks for your reply. I tried the above code when using FacialRecognitionDotNet.CUDA100 and I receive this error. System.TypeInitializationException: 'The type initializer for 'DlibDotNet.NativeMethods' threw an exception.'
Inner Exception DllNotFoundException: Unable to load DLL 'DlibDotNetNativeDnn': The specified module could not be found. (Exception from HRESULT: 0x8007007E). This appears to be the same error @utarn had mentioned above regarding the missing DLL. 
Next I downloaded the "DnnFaceRecognition.zip" file you mentioned above and executed the ".bat" file. Here's a screenshot of that error. 
![afterrunning-bat](https://user-images.githubusercontent.com/33614374/77233352-334ff080-6b64-11ea-84ae-717fef178078.png)
![afterrunning-Cuda-bat-main-directory](https://user-images.githubusercontent.com/33614374/77233354-33e88700-6b64-11ea-90a2-599039a7a6b9.png)
![error-with-bat](https://user-images.githubusercontent.com/33614374/77233355-33e88700-6b64-11ea-901d-3b3c49c259ff.png)

**Comment by atabora1** [comment]
@takuya-takeuchi just following up. Any additional ideas? Your feedback would be appreciated.

**Comment by takuya-takeuchi** [comment]
@atabora1 
sorry , late response
could you try DlibDotNet-cuda101, 100 or 92?
withcuda is legacy

**Comment by atabora1** [comment]
I already tried the other 3 versions of Dlib with Cuda. I also tried it with a three different computers. I think the issue is that the NativeMethods and DlibDotNetNativeDnn DLLs are not being generated when I build with Cuda.

**Comment by takuya-takeuchi** [comment]
Could you confirm the following points?

* Install cudnn to CUDA_PATH
* Install VC ++ 2017 (2019 runtime could be alternative)
* Check dependencies of DlibDotNet.Native.Dnn by using dependency walker, dependencies, dumpbin or fusionlogvw (it may not work for native library)

**Comment by atabora1** [comment]
Hi @takuya-takeuchi , I was finally able to get CUDA to work and I'm seeing noticeable improvements in speed using your benchmark example. I tested with DLIBDOTNET Cuda 10.0 and FaceRecognitionDotNet cuda 10.0. It works fine with WPF applications using .NET Core 3.0. I think the issue is that my other application was a Windows Form application with .NET Frame 4.7.2 Framework. Thanks once again for all your help.
