### ISSUE TITLE
Project does not open in visual studio 2015

### ISSUE THREAD

**Issue by zeeshanliaqat50** [takuya-takeuchi/DlibDotNet#98]
# Summary of your issue
I downloaded the project and tried to open it in visual studio but it does not open successfully
# Environment
Visual studio 2015
Write your environment.

# What did you do when you faced the problem?

//write here

## Example code:

```
paste your core code
```

## Output:

```
paste your output
```

**Comment by takuya-takeuchi** [comment]
DlibDotNet uses .NET core 2.0. So It requires VS 2017 or earlier.

**Comment by zeeshanliaqat50** [comment]
I'm working on face recognition using c#.
Can you please guide me how to use dlibDotNet to do face detection and
recognition ? Please help me,I'm final year student working on final year
project

**Comment by takuya-takeuchi** [comment]
You can use https://github.com/takuya-takeuchi/FaceRecognitionDotNet.
It is my project which be ported face_recognition repository by C#. FRDN depends on DlibDotNet.

Or you can check DlibDotNet examples.
https://github.com/takuya-takeuchi/DlibDotNet/tree/master/examples/DnnFaceRecognition
https://github.com/takuya-takeuchi/DlibDotNet/tree/master/examples/FaceDetection
https://github.com/takuya-takeuchi/DlibDotNet/tree/master/examples/FaceLandmarkDetection

**Comment by zeeshanliaqat50** [comment]
so can i use DlibDOtNet with VS 2015 ? or do i need to only work with VS
2012 or earlier ?

**Comment by takuya-takeuchi** [comment]
You are student, aren't you? You can install Visual Studio 2017 or 2019 community edition. It is free and available for university, study and research.

Or If you want to ONLY build DlibDotNet, you can command line.

````
cd src\DlibDotNet
dotnet build -c Release
````

You can modify by favorite editor.

**Comment by zeeshanliaqat50** [comment]
great so you mean its better if i use VS 2017 or VS 2019 .right ?

**Comment by takuya-takeuchi** [comment]
yes. VS 2015 is already legacy software.

**Comment by zeeshanliaqat50** [comment]
Great.Thank you so much.I will surely work on it
